### ISSUE TITLE
Volunteer notifications configurable and by SMS

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#10]
- [x] As a volunteer texter, I want to create a profile without having a campaign assigned to me
- [ ] As a volunteer texter, I would like to be asked on sign up whether I want to let my volunteer coordinator notify me about my assignments via text or email
- [ ] As a volunteer texter, I'd like to have a profile in order to change my preferences in the future on list notifications

**Comment by arena** [comment]
Should this be broken down into 3 issues in the Problem, Solution, + Context format? I'm not really following what this is about --- Is it about streamlining texter sign up?

**Comment by ibrand** [comment]
@arena This centers around the idea that a volunteer would basically have a profile tab (that seems function a lot like the "account settings" section of slack) where they can set notification preferences. Does that make sense?

**Comment by ibrand** [comment]
#231 is a sub-issue of this one

**Comment by Arique1104** [comment]
Hello @shakalee14,

My name is Arique (they/them) and I am the Community Manager for Spoke.  First of all, thank you so much for creating this issue and for everyone’s contributions to this ticket.

I am going through all of our issues and beginning to close all issues created in 2018 or older.  Your issue qualifies.

I am giving everyone one week to answer the following question: 

- **Has this issue been resolved during the subsequent Spoke Updates?**

On November 16th I will be closing this issue if:
1. There is no response
2. You respond yes

If you are reading this message after November 16th, please note that if you tag me and answer the above question, I will be happy to reinstate the issue.

**Comment by Arique1104** [comment]
This issue is considered resolved.
