### ISSUE TITLE
High priority re: reassigning 

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#1005]
When texters are making egregious errors, I need to be able to take all the conversations they have not yet replied in and leave them with only corrections to make. I can’t afford to let them have the opportunity to keep repeating their errors. 
@lperson @joemcl @codygordon

**Comment by joemcl** [comment]
@suegibson I believe this can be accomplished already using the Needs Texter Response option and Reassign To option. You can reassign any convos to yourself or a different texter, taking those away from the original texter.

**Comment by suegibson** [comment]
No, @joemcl, because some that need texter response already have errors in them. 
cc: @lperson

**Comment by joemcl** [comment]
@suegibson just thinking about the 'workflow' for this.  Now that we can add tags/labels to a conversation in Message Review - and filter for convos with any or no tag -  if @lperson hardcodes a new tag/label  - called 'needs correction' maybe? - so you can tag/label/flag the convos you want to leave with the texter, then you could reassign all the *other* texter convos to yourself, or another texter. I think. Thoughts @suegibson @deasterdaywfp @lperson ? cc: @ibrand .

**Comment by joemcl** [comment]
Just tested that workflow, and yeah, it works. Just need a new tag added.

**Comment by suegibson** [comment]
I don’t see the ability to tag in message review.

**Comment by joemcl** [comment]
@suegibson - yup - it's Assign Tag to Selected. 

Before:
![SpokeTagBefore](https://user-images.githubusercontent.com/3912434/64134860-911f1580-cd97-11e9-9454-f00baee8744c.jpeg)

After:
![SpokeAddTagAfter](https://user-images.githubusercontent.com/3912434/64134864-95e3c980-cd97-11e9-8e25-fd7e2f8fb491.jpeg)

**Comment by suegibson** [comment]
I see. I was looking within a conversation, which would be handier.

**Comment by joemcl** [comment]
> I see. I was looking within a conversation, which would be handier.

@suegibson agree, would be handier. @lperson whaddya think?

**Comment by ibrand** [comment]
Hey @suegibson , @joemcl and @lperson this repo (MoveOn/main) doesn't have tags on it, so this solution doesn't work on. Should we rewrite this ticket to be a little more specific about a spec for solving this problem?

**Comment by lperson** [comment]
@ibrand see #1350.  That's how we solved this for WFP.  It's a WIP for MoveOn in the WFP parity project.  The way it works is that an admin can set a tester's status to SUSPENDED and then they can't send any more texts.  It needs some tweaking, such as a customizable message informing the user they're suspended.

**Comment by ibrand** [comment]
Oh this is awesome! I'll link to this issue there :)

**Comment by Frydafly** [comment]
Closing this due to suspended texter and other features that resolve this issue
