### ISSUE TITLE
Campaigns List sortable by time zone

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#1007]
Would be ideal to select campaigns list display by campaign number, candidate, or launch date. Please consult Dylan for preferred default setting. I prefer campaign # or launch date. By time zone would be awesome, too!
Order needs to accommodate campaigns ### and ###X; if that’s a problem, we can designate certain campaigns in a way other than by adding an X to the campaign number. 
@lperson @joemcl

**Comment by joemcl** [comment]
hey @suegibson - with @lperson's recent work, I *think* this can be closed, what do you think - once @lperson 's newer work we have on our production Spoke is merged 'upstream'. @ibrand @lperson I think this is in a test branch right - https://github.com/MoveOnOrg/Spoke/tree/stage-prettier2

**Comment by suegibson** [comment]
I haven’t seen anything about selecting by time zone, and that’s going to be important during the primaries. Would rather see everything in production before closing.

**Comment by joemcl** [comment]
@suegibson right. So @lperson - since we can select a time zone when creating a Campaign using Texting Hours - besides the default Eastern time zone - can Time Zone be added as a sort option for Campaigns - and while you're at it :) maybe add a way to filter by Time Zone as well, and/or add that as a Campaign value that can be searched?

**Comment by ibrand** [comment]
Where did we land here @lperson ? Was that sort implemented? I remember seeing other comments about TZ stuff somewhere in the pile

**Comment by suegibson** [comment]
I still need sort by time zone.

**Comment by lperson** [comment]
@ibrand this is #1341 in the WFP parity project.  @suegibson wants it enhanced to allow [filtering by timezone](https://github.com/MoveOnOrg/Spoke/issues/1013) and sorting the admin campaign page by timezone, for which, as far as I can tell, there is no issue open.  @suegibson feel free to open an issue for that.

**Comment by ibrand** [comment]
At this point, the specific task here is to add a sort type to the campaign page sorting options that sorts by timezone

**Comment by alliejones** [comment]
I'd be up for taking this on as a first issue! cc: @ibrand

**Comment by alliejones** [comment]
I think my PR is ready for review!
