### ISSUE TITLE
fix incoming message processing

### ISSUE THREAD

**Issue by mathemagica** [ProgressiveCoders/Spoke#101]
Sign in as an admin and create a campaign, assign contacts and a texter to this campaign, and a script, and then sign in as a the texter, and send the first message. As the message recipient, send a reply to this message. 

As the texter, on the texter's campaign page, the texter should see a response from the recipient, and currently does not see this. 

basically twilio sends back a message to /twilio which creates a record in pending_message_part table.  Then the src/works/incoming-message.....js file is supposed to convert the pending_message_part record into a Message object.  but that doesn't happen

**Comment by sandramchung** [comment]
Right now the incoming message handler is set to query the db every 100 ms for new pending_message_parts. Consider instead triggering the incoming message handler upon creation of new pending_message_parts.
