### ISSUE TITLE
Archiving multiple campaigns needs to be easier 

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#1014]
Need to be able to tick a box on each campaign to archive a bunch. As it is now, can archive only one at a time, then have to start over searching for more. @bdatkins 
@lperson @codygordon @joemcl

**Comment by azuzunaga** [comment]
Is this still open? If so, I can take it on.

**Comment by shakalee14** [comment]
i believe it is @azuzunaga !

**Comment by azuzunaga** [comment]
Great, thanks @shakalee14! I'll start working on it 🙌
