### ISSUE TITLE
Might automatic opt outs be possible?

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#1016]
When a contact replies with single word STOP, can it be arranged for Spoke to automatically opt out?
@lperson @joemcl @codygordon

**Comment by DinahSanders** [comment]
Recommendation: trigger only on replies which consist only of the single word 'stop'.

(We can't count on all-caps as a signifier because sometimes we get replies like "Count me in! We have got to STOP this terrible bill from passing!!")

**Comment by suegibson** [comment]
> Recommendation: trigger only on replies which consist only of the single word 'stop'.
> 
> (We can't count on all-caps as a signifier because sometimes we get replies like "Count me in! We have got to STOP this terrible bill from passing!!")

**Comment by suegibson** [comment]
Agreed!

**Comment by bdatkins** [comment]
@suegibson Followup question - should we silently opt them out?

**Comment by bdatkins** [comment]
**I'm grabbing this issue to work on!**  Opting folks out automatically if they use just STOP will increase our data quality and decrease the possibility of annoying those we text!  Especially for new texters, they don't always do the right thing and opt folks out as they should.

**Comment by DinahSanders** [comment]
To @bdatkins's question, I say: No, for this we should send a confirmation.

Our organization's policy is:

> We always send the 'Opt Out' message _except_ under three conditions:
>>The contact mentions texts costing them money;
>>The contact explicitly says, “Do not EVER contact me again”;
>>The contact explicitly says, “Don't text back”.

So, if we're triggering only off the single word 'stop' those don't apply.

Suggested default message: "I'm opting you out of our texts immediately. Have a great day."

**Comment by bdatkins** [comment]
Thanks for that feedback @DinahSanders.   The configured Opt out message be used (either default or the one set at the Organization level). 

I can see starting with a plain 'STOP' and perhaps making it more elegant in a later change, possibly dovetailing with the Profanity check work. (https://github.com/MoveOnOrg/Spoke/pull/938)

**Comment by suegibson** [comment]
Yes, opt out without sending confirmation message, please, @bdatkins. Thank you for thinking to ask!

**Comment by ibrand** [comment]
@bdatkins @suegibson I'm cleaning up our good first issuess and want to know if this one was completed (since it's pretty old) or if it's open for new contributors to claim!

**Comment by bdatkins** [comment]
@ibrand This has not been completed, so someone can grab it!

**Comment by joemcl** [comment]
@ibrand @bdatkins @suegibson we can now backspace and delete the opt out message text - which then causes an 'opt out without sending a message' button to appear. That option is perhaps not obvious/unknown to users, and if made so, might be the fix for this?

**Comment by ibrand** [comment]
This is available and a good one to claim

**Comment by bdatkins** [comment]
I believe this is addressed in 8.x? @ibrand

**Comment by ibrand** [comment]
Yes! This has been in the codebase since 7.1 but has been used by MoveOn in production since for a while. The extension needed is a [message-handler](https://moveonorg.github.io/Spoke/#/HOWTO-use-message-handlers?id=included-message-handlers) called auto-optout. You can code in your own regex to choose which phrases you want to trigger the auto optout functionality!

I'll go ahead and close this, but reach out if you have questions

**Comment by bdatkins** [comment]
Thanks @ibrand !
