### ISSUE TITLE
Heroku: No Create New Campaign Button

### ISSUE THREAD

**Issue by JessePresnell** [ProgressiveCoders/Spoke#1017]
After installing Spoke using the Heroku guide, I've successfully deployed, created an account, and created a new organization. This seems to be as far as I can get, because I don't seem to have any of the admin sidebar options or the ability to create a new campaign. 

I've confirmed my config vars, and redeployed with no change in outcome. Am I missing something?

![adminpanel](https://user-images.githubusercontent.com/2937734/48723884-dc47ad80-ebf5-11e8-9343-0e1c7c4e8b1a.png)

**Comment by 350co** [comment]
Having the same issue. Did you find a way to fix this?

**Comment by shakalee14** [comment]
Hey - so I believe this is related to the amount of user entries in the user_organization table:

it should actually only be a single entry with 'OWNER'

Can you look in the user_organization table and see if your user_id is listed multiple times - if it is, delete entries for your user_id that are NOT 'OWNER'.

The .env build log error isn't a breaking issue FYI @JessePresnell and just a warning. 

If you do this and then see a screen that says 'you are not part of any organization', i'd attempt to just go to the admin screen anyways so for example the url would like like : https://hosted_url/admin/1/campaigns

where 1 is the organization id

This should fix the issue @350co @JessePresnell

**Comment by shakalee14** [comment]
This should be fixed now that #1011 is merged
