### ISSUE TITLE
Marking conversations for reassigning 

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#1023]
I appreciate this feature, but after reassigning the conversations, the check marks don’t disappear. They attach themselves to the subsequent conversations in the list. When I scroll to another page of conversations, the check marks will be there, too, uninvited. Unticking all the boxes takes up more of my time and is annoying. 
@bdatkins @lperson @joemcl

**Comment by lperson** [comment]
@suegibson this is obviously a bug.  I'll look into it (at some point).

**Comment by suegibson** [comment]
Yeah, so after working with it for a while, I would like to add this to my priority list, @lperson

**Comment by joemcl** [comment]
thanks @lperson and @suegibson can you close this Issue?
