### ISSUE TITLE
Add ability to 'hold down thumb' (mobile) just like 'hold down enter key' for texting

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#1043]
On Desktop you can 'hold down the enter key' to continue texting, but on mobile you have to keep 'thumbing'.  It would be great if someone could keep the thumb down in the same way.

* Make sure the send button is stably placed'
* figure out how to carry over ontouchstart and remove for ontouchend (or what happens with ontouchstart, when the dom is swapped from underneath the event?)

This mostly relates to work in this file:
https://github.com/MoveOnOrg/Spoke/blob/main/src/containers/AssignmentTexterContact.jsx
which is the component connected to the texter's view per-contact.

**Comment by harpojaeger** [comment]
Are there compliance issues to consider here?

**Comment by schuyler1d** [comment]
Only if it doesn't stop when they lift their thumb -- whatever compliance issues would also be for holding down a key, which Spoke and several other P2P solutions do already.

**Comment by Anasauce** [comment]
Any screenshots so I can duplicate this issue?

**Comment by schuyler1d** [comment]
This is for the texter screen, so this one:
https://static1.squarespace.com/static/5783159f9f74568e00209d13/t/59fa255ae2c4833ff4b57a99/1518730391743/mobile_text_screen.png?format=500w
basically, this is for being able to keep the thumb down on the send button when the status is 'needsMessage' (i.e. there is no message thread) -- and in that context of needsMessage status, we can probably hide the canned responses and opt-out button (if that's not true already)

**Comment by kmanzana** [comment]
Is anyone working on this?

**Comment by ibrand** [comment]
@Anasauce and @schuyler1d I'm cleaning up our `good first issues`s and want to know if this one was completed (since it's pretty old) or if it's open for new contributors to claim!

**Comment by schuyler1d** [comment]
I believe this is still open.

**Comment by bdatkins** [comment]
Going to grab this one.

**Comment by arena** [comment]
@bdatkins 
any progress on this?

**Comment by bdatkins** [comment]
@arena yes, working on it!

**Comment by arena** [comment]
Eagerly awaiting sending my morning blast of texts from my phone instead of waiting until I've got a keyboard at my fingertips. (I suppose I could get fancy and connect a bluetooth keyboard to my phone in the meantime)

**Comment by ibrand** [comment]
@bdatkins did you end up getting this to a place where it'd be worth sharing a WIP PR for someone else to pick up? Otherwise I'll probably reassign it

**Comment by bdatkins** [comment]
@ibrand feel free to reassign!

**Comment by schuyler1d** [comment]
I'm going to close this based on our changes with enter key behavior
