### ISSUE TITLE
Enable Heroku Review Apps

### ISSUE THREAD

**Issue by jlegrone** [ProgressiveCoders/Spoke#1052]
This will make it easier to do incremental QA and give us some peace of mind about potential configuration drift issues.

Once review apps are enabled, it would also be great to set up a seed script with some standard dummy data.

**Comment by harpojaeger** [comment]
#683 will make this a lot easier, since Knex has nice seeding support. Resolving those merge conflicts and getting that one ready is next on my list.

**Comment by harpojaeger** [comment]
(#692 is the associated PR for that issue and has more up-to-date discussion of progress)
