### ISSUE TITLE
add ability to temporarily remove a sender from any or all Campaigns

### ISSUE THREAD

**Issue by joemcl** [ProgressiveCoders/Spoke#1055]
This is similar to but not exactly the same as #629 and perhaps related to #858 and #922 . At times, for 'quality control' reasons, we want to put a text sender 'on hold' - *temporarily* disable sending for any and all campaigns, and get that user better-trained. So, having a way to put senders 'on hold' in Spoke, via the People admin interface, by  changing user status in that, say from Texter to Texter - On Hold or whatever, seems to be better than having to remember who those folks are when moderating, and/or cross reference say a user list in Airtable or a spreadsheet, or remember a notification in Slack. @deasterdaywfp @suegibson

**Comment by suegibson** [comment]
What do you envision triggering that, @joemcl?

**Comment by joemcl** [comment]
@suegibson if you mean triggering putting someone on hold, whatever criteria you choose to use now. The difference with this is you could change the user status manually in People and temporarily disable all sending. Down the road, we might want to somewhat 'automate' changing a user status based on user experience or quality control issues identified - like, only allowing new users with status of Texter - Newbie to send say 50 or 100 or 200 texts at a time, even if sending in a campaign with Dynamic assigning enabled, and promote them to a regular Texter later.

**Comment by suegibson** [comment]
I would like their ability to reply as well as send to be halted.

**Comment by joemcl** [comment]
@suegibson right agreed - 'on hold' would mean cannot send anything - either new initial or replies.

**Comment by ibrand** [comment]
#1487 will create the SUSPENDED role which can be used to put a texter on hold. I'm going to close this and if there are further thoughts about the SUSPENDED role, they should go on #1487
