### ISSUE TITLE
Provide public docker images

### ISSUE THREAD

**Issue by jlegrone** [ProgressiveCoders/Spoke#1056]
Once #1053 is merged, we'll have a dockerfile that builds directly from source. This makes it possible to hook up a public docker repository with automatic builds.

I suggest dockerhub.io since it's free and builds can be triggered from branches and tags. Here is a sample repository that I've set up to build against my fork:

https://hub.docker.com/r/spokeapp/spoke

- [ ] Set up a public docker repository connected to https://github.com/MoveOnOrg/Spoke
- [ ] Give docker admin to Spoke Github admins
- [ ] Add build triggers for git tags (official releases) on git repository
- [ ] Add build trigger for `main` branch to update `latest` tag

**Comment by ibrand** [comment]
Our current dockerfile seems to be a little broken for dev environments (though works on Heroku) -- I'm marking this as blocked until our dockerfile is in a better state
