### ISSUE TITLE
does surveystats exclude opted out contacts? If so make that explicit

### ISSUE THREAD

**Issue by joemcl** [ProgressiveCoders/Spoke#1057]
We've been doing some SQL queries for external dashboards. We have one that is almost there, to calculate total texters, texts sent, replies, ID'd Yesses, Maybes and Nos, total texts and opt outs per campaign. We'll share that when we think it's ready. 

We're getting slightly higher Yesses, Maybes and Nos counts in that external dashboard chart compared to what shows in the Spoke campaign summary for Voter Disposition.

I'm thinking what *might* explain the difference is that Voter Disposition in Spoke survey stats counts exclude opt-outs, so, for example, someone who responded ''Yes I support candidate X but please stop texting me" and was recorded as a Yes, but also opted out, does not show in Voter Disposition counts as a Yes.

Diving into the code and docs for answer/clues too. 

@spakanati any tips appreciated, thanks!

**Comment by joemcl** [comment]
I've been looking here for some clues - https://github.com/MoveOnOrg/Spoke/blob/a99b5bf765a158637c2de31887abfe9458654d78/src/containers/AdminCampaignStats.jsx#L107 
and taking a look at past PRs by @spakanati .

**Comment by joemcl** [comment]
Also @schuyler1d @shakalee14 @benmort, thoughts appreciated...

**Comment by ibrand** [comment]
@schuyler1d do you know the answer to this? If so, we should document it and close this

**Comment by joemcl** [comment]
Also hey @saikat and @spakanati any help appreciated re ^^^ :) and thanks so much for creating Spoke in the first place.

**Comment by schuyler1d** [comment]
The code is here:
https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/question.js#L38
It doesn't exclude opt-outs.  I can debug your query if you put it in this issue.  Without the query, I don't think this issue should remain open.

**Comment by joemcl** [comment]
@schuyler1d sorry that I missed your comment back in January. Thanks for the answer and the pointer to the code. I believe this is the SQL I was using at the time, in Feb 2019. 
```
SELECT
    c.id AS campaign_id,
    c.title AS campaign,
    texters::int,
    texts_sent::int,
    replies::int,
    yesses::int,
    maybes::int,
    nonsupporters::int,
    total_texts::int,
    opt_outs::int,
    /* cost per texter = $1 / 30 days (est) */
    ROUND(((texters / 30)  + ((total_texts * .0375)*1.15)), 2) AS costid
FROM [carlosgarcia_campaigns AS c]

INNER JOIN organization AS o ON o.id = c.organization_id

INNER JOIN (
    SELECT
        a.campaign_id,
        COUNT (DISTINCT m.assignment_id) AS texters,
        COUNT(DISTINCT (
          CASE WHEN m.is_from_contact = 'f' THEN m.id END
        )) AS texts_sent,
        COUNT(DISTINCT (
          CASE WHEN m.is_from_contact = 't' THEN m.id END
        )) AS replies,
        COUNT(DISTINCT m.id) AS total_texts,
        COUNT(DISTINCT (
            CASE WHEN qr.value = 'Yes Vote' THEN qr.id END
        )) AS yesses,
      COUNT(DISTINCT (
            CASE WHEN qr.value = 'Maybe' THEN qr.id END
        )) AS maybes,
      COUNT(DISTINCT (
            CASE WHEN qr.value = 'Non supporter' THEN qr.id END
        )) AS nonsupporters,
        COUNT(DISTINCT o.id) AS opt_outs
    FROM assignment a
  
    INNER JOIN message AS m ON m.assignment_id = a.id
    INNER JOIN [campaign_contact_2019 AS cc] ON cc.assignment_id = a.id
    INNER JOIN question_response AS qr ON qr.campaign_contact_id = cc.id
    INNER JOIN interaction_step AS i ON qr.interaction_step_id = i.id 
 
    LEFT JOIN opt_out AS o ON o.assignment_id = a.id
    
    WHERE i.question = 'Voter Disposition'
    --  WHERE a.assignment_id = m.message_assignment_id
    GROUP BY 1
) AS m 
ON m.campaign_id = c.id
--WHERE c.is_archived = 'f' AND c.is_started = 't' 
--AND c.id IN (1082)
--AND c.id = 1030
ORDER BY 1,2
````
