### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#1060]
Add spoke logo as favicon.

**Comment by deasterdaywfp** [comment]
Love this! Can you share the Spoke logo @shakalee14 ? I don't think I've seen it before.

**Comment by joemcl** [comment]
@deasterdaywfp see https://opensource.moveon.org/spoke

**Comment by filafb** [comment]
Hey all! Just opened a PR #1135 for this. I got to work on this issue last progressive hacknight and forgot to report here (sorry)

**Comment by shakalee14** [comment]
Fixed with #1148
