### ISSUE TITLE
Twilio sending empty response

### ISSUE THREAD

**Issue by blairwigley** [ProgressiveCoders/Spoke#1069]
Twilio seemingly sending empty values on message reply to Spoke. This is what the logs are reporting: 

`[90mbackend [39m[31merror[39m error: insert into "pending_message_part" ("contact_number", "parent_id", "service", "service_id", "service_message", "user_number") values ($1, $2, $3, $4, $5, $6) returning "id" - null value in column "user_number" violates not-null constraint`

Running on heroku, looks like all my API keys are correct as the response is at least reaching Spoke. 

Any ideas?

**Comment by blairwigley** [comment]
I got around this by making user_number nullable on both the message and the pending_message_part table - any ideas for more robust fixes?

**Comment by ibrand** [comment]
@schuyler1d have we seen this before on our end?

**Comment by schuyler1d** [comment]
This sounds familiar and I think it was maybe fixed. But if it isn't, I think we'd need more detail (replies, original sends, etc)
Very few configurations now rely on message parts, so I think it's unlikely to be an issue
