### ISSUE TITLE
getContacts filters (probably) not really working

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#107]
getContacts here: https://github.com/MoveOnOrg/Spoke/blob/master/src/server/api/assignment.js#L17
is used lower down in the same file here:
https://github.com/MoveOnOrg/Spoke/blob/master/src/server/api/assignment.js#L101
Note that it has a query parameter for `contactsFilter`, e.g. from:
https://github.com/MoveOnOrg/Spoke/blob/master/src/containers/AdminCampaignEdit.jsx#L32

All of the logic in `if (contactsFilter) { ...` is making some subtle assumptions about how indexValues ends up used in getAll() below.  This function should probably start with a knex query on top, and then add filters properly conditioned on the contactsFilter options enumerated.

This relates to #100 (it's bullet 2)

**Comment by sandramchung** [comment]
ongoing work in fix-get-contacts branch
