### ISSUE TITLE
Review Created Campaign

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#108]
- [x] Admin should be able to review a campaign that is in process with correct response data
- [x] Admin should be able to receive a csv report

**Comment by shakalee14** [comment]
currently getting this error after clicking on an active campaign: 
`0|spoke-se | ReqlRuntimeError: Cannot convert `undefined` with r.expr() in:
0|spoke-se | r.table("question_response").getAll(undefined, {
0|spoke-se |                                     ^^^^^^^^^  ^
0|spoke-se |     index: "interaction_step_id"
0|spoke-se |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0|spoke-se | }).filter({
0|spoke-se | ^
0|spoke-se |     value: "ok "
0|spoke-se | }).count() `

which we think has to do with whats going on in ./src/server/api/question.js lines 19-50,  specifically on line 48 which is expecting an object. if line 48 (`question: ...`) assumes the full object, then we will probably need to turn that whole thing in the resolver into a knex query with a join and then change the result object

**Comment by shakalee14** [comment]
@schuyler1d also suggests:
https://github.com/MoveOnOrg/Spoke/blob/master/src/server/api/question.js#L37
changing where it says `answer.parent_interaction_step.id` to `answer.parent_interaction_id`

**Comment by sreynen** [comment]
All of this works as expected on an active campaign with no messages. Next testing with messages out, then incoming messages.

**Comment by sreynen** [comment]
With https://github.com/MoveOnOrg/Spoke/pull/110 everything in the original description works in my testing, but I never got the error in https://github.com/MoveOnOrg/Spoke/issues/108#issuecomment-321299356 so not sure if that's still an issue.

**Comment by shakalee14** [comment]
https://github.com/MoveOnOrg/Spoke/pull/113
