### ISSUE TITLE
test queries for campaign admin

### ISSUE THREAD

**Issue by sandramchung** [ProgressiveCoders/Spoke#109]
To aid in debugging other issues, e.g. #100 and #108

**Comment by sandramchung** [comment]
This is about reworking the existing tests for soup-to-nuts campaign creation that worked in Rethink to work with knex/postgres.

**Comment by ibrand** [comment]
Closing due to the fact that both issues referenced in the original description are now closed. If this should be re-opened @sandramchung let me know!
