### ISSUE TITLE
Disable or change "You've already messaged or replied to all of your assigned contacts for now." when still contacts left to text 

### ISSUE THREAD

**Issue by joemcl** [ProgressiveCoders/Spoke#1105]
When sending in a Campaign using Dynamic, and there are contacts still to text, and Spoke is apparently querying and loading up new assignments, the text "You've already messaged or replied to all of your assigned contacts for now." appears to a texter, with a link to 'Back to ToDos". This is confusing and unhelpful. 
Suggested message is something like "Hey thanks for sending texts! Hold on for a couple of seconds while we load up more contacts to text, please refresh this page...."

![bde19d65-a6c9-4b46-88f0-a4fd8e7b0211](https://user-images.githubusercontent.com/3912434/57199507-8a40dd00-6f34-11e9-8b8b-6185ed679427.jpg)

**Comment by joemcl** [comment]
@deasterdaywfp ^^^

**Comment by joemcl** [comment]
I think this has been fixed by #1110 ...

**Comment by ibrand** [comment]
@joemcl @schuyler1d is this changed to joe's suggested text? Can it be closed?

**Comment by schuyler1d** [comment]
I think while the text is the same, improvements on the frontend made it much less likely that someone would see this message incorrectly, so closing
