### ISSUE TITLE
Canned Responses - all disappearing after one or multiple saved

### ISSUE THREAD

**Issue by joemcl** [ProgressiveCoders/Spoke#1106]
So for awhile (months, at least) we have had a problem with all Canned Responses disappearing from some (not all) Campaigns after one or more Canned are created in a new Campaign and saved. It happened again earlier today, and I just recreated it. 
I cloned a campaign from earlier today that had Interactions save successfully and was having Canned added, which then disappeared.
I started adding all the same Canned. I was able to add all from the script, saving periodically, and when I finished adding all and Saved one last time, I refreshed Canned and all the Canned Responses had disappeared. 
I'm attaching an excerpt of the log from the time of the error. It seems a SQL error is being created - ```sql_error_code = 23505 ERROR:  duplicate key value violates unique constraint "canned_response_pkey" ``` . 

cc: @lperson @deasterdaywfp @codygordon  . 

[20190511-639PMPacificSpokeCannedResponseVanishingErrorLog.txt](https://github.com/MoveOnOrg/Spoke/files/3169638/20190511-639PMPacificSpokeCannedResponseVanishingErrorLog.txt)

**Comment by deasterdaywfp** [comment]
Thank you @joemcl this is a really big argument for the Google doc integration to load canned responses IMHO.

**Comment by joemcl** [comment]
@shakalee14 I'm wondering if it is something related to the random Canned IDs created via this - 
https://github.com/MoveOnOrg/Spoke/pull/122/commits/7e51f58338efe44a018e21eb4f1cf123846822ed  
 maybe they are not that random?

**Comment by joemcl** [comment]
> Thank you @joemcl this is a really big argument for the Google doc integration to load canned responses IMHO.

@deasterdaywfp yeah you mean #1102 - I think the 'insertion' method - from a Google Doc somehow, or from our current copying and pasting text from a Google Doc into the Canned Response UI - would not make a difference, something else is going on.

**Comment by joemcl** [comment]
So @shakalee14 see screenshot below - the Canned response ID created randomly in the new Campaign already existed as an ID for a Canned in an earlier Campaign. So rather than Canned response IDs being generated randomly - with apparently random dupes appearing - why can't Canned response IDs just be numbered sequentially on creation, i.e., autoincrement, to insure a unique value for each? 

![3884b1c7-7987-4303-a108-9b0624e2d795 (1)](https://user-images.githubusercontent.com/3912434/57577420-0e123200-742b-11e9-996c-4097ade2fc25.jpg)
