### ISSUE TITLE
add texterAliasfirstName as an option for sending

### ISSUE THREAD

**Issue by joemcl** [ProgressiveCoders/Spoke#1109]
Add an option for folks, especially women, to add a 'texterAliasfirstName' to their user record to optionally send as - like 'Frank' (alias) rather than 'Lydia' (actual First Name). Often, texters IDing as women receive harassing replies back, perhaps as a reaction to common 'gender association' of their first name.  
Would also necessitate a preferredTexterFirstName field to use for actual  message creation (like {preferredTexterfirstName} token), with user firstName as default, but alias as an option.

**Comment by deasterdaywfp** [comment]
Good idea, and in line with our needs to be inclusive of all identities/peoples using Spoke now or in the future.

**Comment by schuyler1d** [comment]
I would suggest implementing this by creating a new `alias` column on the user table:
https://github.com/MoveOnOrg/Spoke/blob/main/src/server/models/user.js
Add it as an editable field (with default = '') in the user edit form:
https://github.com/MoveOnOrg/Spoke/blob/main/src/containers/UserEdit.jsx

and then maybe just rename `{texterFirstName}` to `{texterFirstNameAlias}` which will always be filled in with the `alias` value if non-empty and falls back to first name here:
https://github.com/MoveOnOrg/Spoke/blob/main/src/lib/scripts.js#L40

Besides that it would need a migration (see https://github.com/MoveOnOrg/Spoke/blob/main/docs/EXPLANATION-development-guidelines.md#schema-changes)
and also to update the API so the frontend for the texter context gets the info
(src/server/api/user.js, src/api/user.js, and https://github.com/MoveOnOrg/Spoke/blob/main/src/containers/TexterTodo.jsx#L149 )

**Comment by ibrand** [comment]
I'm cleaning up our `good first issue`s. @deasterdaywfp and @joemcl, I'm noticing that this issue is a bit old but still seems like a good first issue. Has this been implemented somewhere? Or would it still be able to be claimed by a new person?

**Comment by deasterdaywfp** [comment]
This has not been implemented yet but would love for someone to claim it!

Thanks!

**Comment by joemcl** [comment]
Yes this would be handy to implement, and useful for (hopefully) cutting down on abuse received back by some texters. Thanks @ibrand for asking! cc: @deasterdaywfp .

**Comment by filafb** [comment]
Hi all!! I will take a look at it.

**Comment by deasterdaywfp** [comment]
Thanks Fila!

**Comment by joemcl** [comment]
great, thank you @filafb !

**Comment by filafb** [comment]
Hi @schuyler1d !

I’m working on this and figured out that just renaming {texterFirstName} to {texterFirstNameAlias} will break old messages stored in the DB using {texterFirstName}.

A few alternatives:

1. Go over all DB rows that contain {texterFirstName} and replace it. I could do it in a migration file;
2. Create a workaround inside React to show the right tag name when user is editing the message. And in [this line](https://github.com/MoveOnOrg/Spoke/blob/7383d084fe140dd08c848620002e0fb30bb27814/src/lib/scripts.js#L40), make the current conditional to check for "texterFirstName" or “texterFirstNameAlias”
3. Keep {texterFirstName} and add a new tag {texterAlias}.

I feel the last one is the best choice. It gives a chance for user creating the script to choose the most appropriate input. They might want the first name in some cases. The second one might have other edge cases I’m not seeing, and the first one can be time consuming. 

Let me know your thoughts.

Thanks!

**Comment by joemcl** [comment]
@filafb right, yeah {texterFirstNameAlias} would be a *new* field, it would not replace {texterFirstName}.

**Comment by ibrand** [comment]
@schuyler1d and @filafb where did you land with this ^ ?

**Comment by filafb** [comment]
Hi @ibrand! I got the answer below by @joemcl by email, but didn't have time to work on this. Planning to go to the next hacknight to finish it.

> @filafb right, yeah {texterFirstNameAlias} would be a new field, it would not replace {texterFirstName}.

**Comment by ibrand** [comment]
awesome @filafb I went ahead and assigned this issue to you so no one else picks it up for now.

**Comment by arena** [comment]
Any progress on this? I was going to add a feature request but found this existing issue.

⭐️One thing to add that is important to me, as a woman with an unusual name and a texter, is that I want my real name (the one I use on our Slack teams) to be what somebody sees when they assign me texts or try to review messages that I've received, etc. 

Right now, there is a lot of confusion about my Slack name not matching my Spoke name --- I use my real name on Slack and I use an alias (a common male name) on Spoke. ...And I hate explaining over and over why I need to do this ... because I don't like getting sexually harassed with "send photos" messages or asked stupid questions about my name "is that really your name?" "did you know your name means stadium?" ...these are the most irritating texts and having to explain that this is what happens to me over and over is also annoying.

**Comment by arena** [comment]
@filafb 
will you post a status update?

**Comment by filafb** [comment]
Hi @arena. I couldn’t have it done the first time I set to work in it. Will try to work on it again this weekend. If I don’t have it done by Monday, will ask @ibrand to assign to to other dev.
