### ISSUE TITLE
Edits to title in BASICS menu randomly don't save

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#1142]
When attempting to change the title of a campaign (most frequently a copied campaign) in the basics menu, Spoke often will not save the edits, or it will then revert back randomly. Example: you change the title, the Basics bar in the admin panel goes from yellow to green, then back to yellow again. Sometimes you have to try and fix the title multiple times.

**Comment by ibrand** [comment]
@ErikKirkstein Looks like this issue was in stage-main #1133, is it now resolved?

**Comment by shakalee14** [comment]
I moved this info to a new issue #1195
