### ISSUE TITLE
Save button freezes randomly when attempting to save Basics, Canned Responses or Interactions 

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#1143]
Spoke will arbitrarily "freeze" when using the admin side of the Basics, Canned Responses or Interactions menus. After adding information to the menu, when you click "Save" Spoke will not save it, but rather "freeze." To regain access, you either need to refresh your browser one or more times, or open a new browser window and open Spoke again. After doing this, you see that the information you added was not saved and has to be added again. This happens randomly but with increased frequency over the past month, I'd say with 1 of every 5 campaigns you interact with as an admin.

**Comment by ibrand** [comment]
Closing since we don't see this one anymore :)
