### ISSUE TITLE
Feature Request: Add truncated, expandable Camapaign-title to the Texter UI conversation view

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#1158]
new description per @arena:
**Problem**
Texters need a way to reference the Campaign Title (which would include the Campaign ID at the beginning on the WFP team) in the conversation interface while responding or reviewing replies.

**Solution**
Include a truncated version of the Campaign Title at the top of the interface (see mockup) that can expand on hover or tap to reveal the full title, description and other details of the Campaign (see second mockup)

**Context**
Moderators are asked questions by texters that require the Campaign ID for context and reference. For the texter, finding that campaign number can be next to impossible if they've been doing a lot of texting. If they simply return to their dashboard, and have twenty similar campaigns there, it takes too much effort to figure out which campaign needs the edit or whatever.

**Mockup @arena made**
https://www.figma.com/proto/cWMhQ9loHaXNPGXKnxeXkC/TexterUI-Convo-ShowCampaignTitle?node-id=0%3A2&viewport=1051%2C631%2C1.2889389991760254&scaling=min-zoom

**Comment by schuyler1d** [comment]
You could put this info in the custom HTML field for a campaign.  Or maybe that's only on the TODOs screen?

**Comment by suegibson** [comment]
Right @schuyler1d. It’s only on the dashboard.

**Comment by arena** [comment]
I've been thinking about this and one challenge is that those campaign names can get pretty long. So I think it should be truncated and expandable. ...the expansion offers lots of potential to link to things like the guide as well as show the full title of the campaign title.

This mockup has a lot going on, but focus on the truncated Campaign Title just to the right of the Home button. That could be tappable clickable to show the full info about the campaign.

![image](https://user-images.githubusercontent.com/411070/73093273-026c7b80-3e93-11ea-89f8-c19b28aec3fe.png)

**Comment by suegibson** [comment]
Campaign number (currently four digits) is all I want.

**Comment by arena** [comment]
What use does the campaign number have to the texter?

**Comment by suegibson** [comment]
Restate please. If you meant “What does the campaign number 
have to do with the texter?” we might be running 20 campaigns for one candidate and one has a typo in an interaction. The moderator needs the texter to tell them which one.

**Comment by arena** [comment]
In my experience texting, I want to know which campaign I'm in generally so that I can put context around the conversation... especially if we have had a good back and forth and I can't see the initial message. E.g. Is this person in FL or CA? Did I ask them to do voter reg or to make a call? ...
I can see the 4 digit number being something I'd want to look up to report a problem but not what I'd want to see at a glance to give me context. 

I'm thinking about how to fit everything into the Texting/Responding UI and am leaning toward the title truncated with a way to expand for full details (including the number.. which I didn't even know existed)

**Comment by suegibson** [comment]
Thank you for that perspective! I absolutely do *not* want a truncated title. Just campaign number. Currently it displays on a texter’s dashboard, but if they are texting in several campaigns for the same candidate, it’s difficult to discern from there.

**Comment by arena** [comment]
I get why you'd want that but the number doesn't add anything for the
person who is texting (other than the occasional reference when reporting
the occasional error). Am I mistaken?

**Comment by arena** [comment]
Also, thanks for pointing out that it exists on the campaign card ..I'll go take a look (hadn't noticed it)

**Comment by arena** [comment]
Actually, I can't find it anywhere. Are we using the same version of Spoke?

**Comment by suegibson** [comment]
It enables the texter to tell the moderator that (for instance) there’s a typo in an interaction in campaign 1970.
Sue
#WhiteSilenceIsViolence

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by suegibson** [comment]
Oh, right. That’s the only time we have encountered a need for it.

#WhiteSilenceIsViolence

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by joemcl** [comment]
Yeah, as @suegibson requested, just the campaign ID number is what's needed, for reference.

**Comment by arena** [comment]
After some back and forth on Slack it turns out that because of the WFP naming convention that including the first few characters of the title of the campaign with a way to expand it that this would accomplish different desired effects for different teams. 

For WFP, it would show the ID number on the campaign card (via the title like it already does) and inside the texting interface (via the first part of the title showing)

For MoveOn and others, it would show the first few characters of the Campaign/List title to give the texter some context at a glance (e.g. "Text Every.." vs "Call Your..."). So texters could have some idea of how to respond or why a reply came in the way it did.

And then, being able to expand would give texters full context: full campaign title, full description, any links, we could even add the ID number which may be useful to orgs that don't include it in the title. 

I'm going to suggest a re-wording with more details of this issue:

**Comment by arena** [comment]
**Suggested title change for this issue**
Feature Request: Add truncated, expandable Camapaign-title to the Texter UI conversation view
(currently "Please add campaign number to texters’ conversation screen")

With these details added to the description:

---

**Problem**
Texters need a way to reference the Campaign Title (which would include the **Campaign ID** at the beginning on the WFP team) in the conversation interface while responding or reviewing replies.

**Solution**
Include a truncated version of the Campaign Title at the top of the interface (see mockup) that can expand on hover or tap to reveal the full title, description and other details of the Campaign (see second mockup)

**Context**
Moderators are asked questions by texters that require the Campaign ID for context and reference. For the texter, finding that campaign number can be next to impossible if they've been doing a lot of texting. If they simply return to their dashboard, and have twenty similar campaigns there, it takes too much effort to figure out which campaign needs the edit or whatever.

---
(currently: @joemcl @lperson It would be great to see campaign number on the texters’ conversation screen. They ask me a question about a Cabán campaign, I need the campaign number, they return to their dashboard, and they might have twenty Cabán campaigns there. It takes too much effort to figure out which campaign needs the edit or whatever.)

**Comment by arena** [comment]
I need to add the mockup for what tapping on the truncated title would look like. ..for now, I'll describe it as a truncated title where we display the first n characters of the title (ideally enough for the first 2 words to show if they are reasonably short" ---> How about n=12

Then when you tap on those n character (which should be trailed by an ellipsis) you get a dismissible modal with the full campaign title, the description, texting guide link, and campaign ID) ...any thing else that I should get into the mockup?

**Comment by suegibson** [comment]
Updated issue description: 

new description:
**Problem**
Texters need a way to reference the Campaign Title (which would include the Campaign ID at the beginning on the WFP team) in the conversation interface while responding or reviewing replies.

**Solution**
Include a truncated version of the Campaign Title at the top of the interface (see mockup) that can expand on hover or tap to reveal the full title, description and other details of the Campaign (see second mockup)

**Context**
Moderators are asked questions by texters that require the Campaign ID for context and reference. For the texter, finding that campaign number can be next to impossible if they've been doing a lot of texting. If they simply return to their dashboard, and have twenty similar campaigns there, it takes too much effort to figure out which campaign needs the edit or whatever.

**Comment by arena** [comment]
Yay!!! 
Here's a clickable mockup:
https://www.figma.com/proto/cWMhQ9loHaXNPGXKnxeXkC/TexterUI-Convo-ShowCampaignTitle?node-id=0%3A2&viewport=1051%2C631%2C1.2889389991760254&scaling=min-zoom

**Comment by arena** [comment]
@suegibson 
🙌⭐️👍

**Comment by ibrand** [comment]
Closing because the new texter UI includes this! #1493
