### ISSUE TITLE
You must provide the domain configuration value to use passport-auth0

### ISSUE THREAD

**Issue by ShashiKumar-SignalWire** [ProgressiveCoders/Spoke#1171]
While starting with yarn dev-start-debug i am getting this issue `You must provide the domain configuration value to use passport-auth0`

**Comment by jabyess** [comment]
This is related to #805 and #1270

**Comment by ibrand** [comment]
Closing because this is a duplicate of #753

Also for now as a workaround you can set your local env to use local auth instead of auth0 when developing
