### ISSUE TITLE
Spoke populating initial texts in "Send Replies" menu

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#1188]
For each batch of texts a texter requests, Spoke does not allow a certain amount to send. 

Example: I request 500, I click SEND 500 times, then Spoke says I still have X amount left to send. No matter how many times to try to send X, they just repopulate as Initial Texts to send,

While this issue has be present for months, Spoke is now populating some of X into the SEND REPLIES menu. 

Example: I have 10 replies, I begin replying, then randomly an initial text appears to send. Sometimes a simple refresh of my browser fixes this, sometimes not.

This is causing confusion for texters, and is also leading to the SKIP REPLY button disappearing randomly when sending replies.

**Comment by shakalee14** [comment]
We confirmed that the contacts who have been populated into the replies workflow, but show an initial text - have indeed been sent an initial message, and have responded. Their message status is marked as 'needsResponse' in the backend, and after refreshing, you can see their response.

**Comment by schuyler1d** [comment]
I wonder if this could be attributed to send errors/retries -- this might be more visible after [error_code  schema changes](https://github.com/MoveOnOrg/Spoke/pull/1273)
