### ISSUE TITLE
Edits "Basics" menu of campaigns not always saving or staying saved

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#1195]
Hi team,

A couple issues recently with scripts in Spoke:

Titles/dates in Basics menu not always saving in a campaign. For example, an admin makes a copy of a campaign or a new campaign, adds a title, description and date, and Spoke's Basics bar will turn green, then go back to orange, sometimes then going back to green, other times staying orange, indicating the save did not take. Sometimes a "refresh" of the browser fixes this, other times not. Apart of the title not always saving is when a new campaign is copied and `COPY - ` randomly appearing in the campaign title.

Workflow:
When attempting to change the title of a campaign (most frequently a copied campaign) in the basics menu, Spoke often will not save the edits, or it will then revert back randomly. Example: you change the title, the Basics bar in the admin panel goes from yellow to green, then back to yellow again. Sometimes you have to try and fix the title multiple times.

**Comment by shakalee14** [comment]
hey @ErikKirkstein  - i made the interaction step bullet points into a separate issue, and kept the basics menu bug in this issue

**Comment by schuyler1d** [comment]
it's possible this will be fixed by https://github.com/MoveOnOrg/Spoke/pull/1211 (due to forced `await ...reload()` of the campaign cache.

**Comment by schuyler1d** [comment]
it was fixed with #1211
