### ISSUE TITLE
Feature Request: Documentation -- test enviornment

### ISSUE THREAD

**Issue by tanyastickles** [ProgressiveCoders/Spoke#1208]
**Is your feature request related to a problem? Please describe.**
When setting up my dev environment, it wasn't immediately clear how to run tests since the link was near the bottom of the page.  It also wasn't clear how to get Postgres up and running or how to debug problems with its installation. 

**Describe the solution you'd like**

* Add the testing section under *getting the app started* 
* can just link to the page [how to run tests](https://github.com/MoveOnOrg/Spoke/blob/main/docs/HOWTO-run_tests.md)
* in that page, include[ tips in getting postgres installed](https://www.codementor.io/engineerapart/getting-started-with-postgresql-on-mac-osx-are8jcopb)

**Comment by shakalee14** [comment]
hey @tstickles - thanks for the recommendations. are you interested in creating a branch/pr for this?

**Comment by tanyastickles** [comment]
Yep! @shakalee14
