### ISSUE TITLE
Bug: Change text in Invite New Texters link in People

### ISSUE THREAD

**Issue by joemcl** [ProgressiveCoders/Spoke#1218]
**Describe the bug**
Change
```Send your texting volunteers this link! Once they sign up, they'll be automatically assigned to this campaign.``` 
to
```Send your texting volunteers this link! Once they sign up, they'll be automatically assigned to this *Organization*.```

**To Reproduce**
go to People
Click on big + icon in lower right corner

**Expected behavior**
See #1022 

**Screenshots**
![SpokeNewTextersLink](https://user-images.githubusercontent.com/3912434/64132479-07fee300-cd85-11e9-86b1-3e32c1c99e94.jpeg)

**Platform (please complete the following information):**
 - OS: Ubuntu 
 - Browser: Chrome 
 - Desktop 
 - Version - ? 

**Additional context**

**Comment by WSINTRA** [comment]
I submitted a fix for this, this is my first contribution so I am a noob. I think I followed the correct procedures , thanks to Sky (hope I spelt it right) for the help.
