### ISSUE TITLE
Bug: Wrong indentation in ROLES_DESCRIPTION bullet points

### ISSUE THREAD

**Issue by azuzunaga** [ProgressiveCoders/Spoke#1232]
**Describe the bug**
Bullet points between items 3 and 4 are not indented.

**To Reproduce**
1. Go to https://github.com/MoveOnOrg/Spoke/blob/main/docs/ROLES_DESCRIPTION.md
2. See error

**Expected behavior**
Bullet points under item 3 should be indented one level.

**Platform (please complete the following information):**
 - Wherever docs are viewed.

**Comment by stevenfranks** [comment]
PR added, please review.
