### ISSUE TITLE
Bug: Missing syntax highlighting in graphql-debug doc

### ISSUE THREAD

**Issue by azuzunaga** [ProgressiveCoders/Spoke#1235]
**Describe the bug**
Fenced code blocks in [graphql-debug](https://github.com/MoveOnOrg/Spoke/blob/main/docs/graphql-debug.md) doc are missing syntax highlighting.

Fenced code blocks should have the appropriate syntax identifier, `gql`, `js`, or `json`. See [this](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) resource for more information on adding syntax highlighting to fenced code blocks.

Additionally, file name should be all UPPERCASE to match other docs.

**To Reproduce**
1. Go to https://github.com/MoveOnOrg/Spoke/blob/main/docs/graphql-debug.md
2. Scroll down to a fenced code block.
3. See missing syntax highlighting.

**Expected behavior**
Fenced code block syntax should be highlighted appropriately.

**Screenshots**
Current:
![image](https://user-images.githubusercontent.com/17498598/65529431-1479e580-dec4-11e9-8cc0-f8c5c1672aea.png)

Expected:
![image](https://user-images.githubusercontent.com/17498598/65529468-2a87a600-dec4-11e9-84ee-207c8283c3ca.png)

**Comment by winterlamon** [comment]
I've submitted a PR for this issue. https://github.com/MoveOnOrg/Spoke/pull/1256
