### ISSUE TITLE
Bug: Missing code syntax highlighting in TEXTER_ACTIVITIES_QUERIES

### ISSUE THREAD

**Issue by azuzunaga** [ProgressiveCoders/Spoke#1239]
**Describe the bug**
Similar to #1235.

Code blocks in [TEXTER_ACTIVITIES_QUERIES doc](https://github.com/MoveOnOrg/Spoke/blob/main/docs/TEXTER_ACTIVITY_QUERIES.md) are missing syntax highlighting. Code blocks should be fenced (with triple backticks) rather than be inlined (with a single backtick).

Fenced code blocks should have the appropriate `sql` syntax identifier. See [this](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) resource for more information on adding syntax highlighting to fenced code blocks.

**To Reproduce**
1. Go to https://github.com/MoveOnOrg/Spoke/blob/main/docs/TEXTER_ACTIVITY_QUERIES.md
2. Scroll down to a code section.
3. See missing syntax highlighting.

**Expected behavior**
Fenced code block syntax should be highlighted and indented appropriately.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/17498598/65653585-aff57e00-dfca-11e9-8a6a-77377df2e7a4.png)

After:
![image](https://user-images.githubusercontent.com/17498598/65653593-b84db900-dfca-11e9-8332-8d267b7fe4b8.png)

**Comment by winterlamon** [comment]
I raised a PR for this issue. https://github.com/MoveOnOrg/Spoke/pull/1257
