### ISSUE TITLE
Feature Request: Reduce amount of clicking to tag a conversation then send a pre-written response

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1262]
Scenario/example:
After sending lots of texts there are lots of *wrong number* or *wrong person* replies (this is a pretty common occurrence even with small sample sizes). In many cases the campaign would like these numbers tagged as wrong number so they can clean their list. 
They would also like volunteers to respond with a pre-written reply so they can have a consistent voice.

Problem: too much clicking (and it really adds up at volume)
Clicks: 1. click on manage tags, 2. click into text box, 3. type "wr", 4. click on wrong, 5. mouse over and click on save, 6. click pre-written replies, 7. scroll down to wrong number, 8. click send  = 8 clicks total (if you have 150+ wrong number like I just did, this starts to physically hurt)

Solution:
Reduce the number of clicks to apply a tag (see #1263), use a pre-written response, and send 

Suggestion 1:
Make it possible to set up a pre-written response that also applies a tag

Suggestion 2: 
Make keyboard shortcuts for pre-written responses

I'd be happy to sketch some UI flows if anybody wants to pickup this issue. It would be a huge time saver and a thumb saver.

**Comment by joemcl** [comment]
A common way to record wrong numbers and send a response is to have a Wrong Number answer choice and pre-written response as a choice in the initial ask. It's just one click for the texter. If you want to see this in action, head over to wfp4themany.org/text and sign up :) . 
When the campaign does an Export, those Wrong Number responses are in the export along with the others. Then, for example, if the campaign is using a flavor of VAN, and the VAN ID for each contact was uploaded with the .csv of the contacts, those can be mapped when importing back into VAN using Bulk Update.

**Comment by joemcl** [comment]
Also @arena for Tags that are, say, Activist Codes that exist (or can be added) in a VAN instance, for example, and mapping to those on script creation, using an API connection to VAN, check out this repo from @joshco -  https://github.com/joshco/Spoke/tree/osdi_key .

**Comment by arena** [comment]
@joemcl I think that's helpful information for organizers who are also power users of VAN and Spoke but if not, using Spoke is very hard on the texters.

**Comment by ibrand** [comment]
@arena That makes a lot of sense. We totally want to be accommodating to campaigns that don't use VAN too. Thanks for this write up!

**Comment by arena** [comment]
I added a separate issue that is related, just about tagging #1263

**Comment by joshco** [comment]
@arena could you post a screen shot by what you mean by 'manage tags'?  Maybe my spoke code is out of date, or i'm just confused.  

@joe I think arena is talking about something else, and it's a similar problem even with action handlers/responses (VAN, XYZ or others).  That said, there is less pain with the generalized action handler system (VAN vs CAN, FOO, is a red herring)

# UI

There's definitely some UI speed issues regardless of if you are using VAN or any other system.

The UI for interaction step answers requires first expanding the dropdown to show the possible answers, and while doing that helpfully hides the actual question text underneath, so when moving quickly it's hard to tell what question you are on. When sitting at a laptop or desktop, the mouse clickable area isn't even clearly bounded, so i have guess-click multiples before i succeed.

There's lots of screen real estate dedicated to the chat history, but the controls needed to quickly respond to the message at hand and move to the next are compressed into a very small space, even on mobile.

Keyboard shortcuts or other mnemonics would very helpful on non-touch devices.

# Automation

Automation can also be improved by having multiple actions invoked when the texter selects a interaction step response.  This is actually the same thing we ran into with the multiple survey questions on the same step response.

What could also be added to those action choices are some internal spoke actions like "trigger canned response X, mark this as wrong number etc.

**Comment by joemcl** [comment]
> @joemcl I think that's helpful information for organizers who are also power users of VAN and Spoke but if not, using Spoke is very hard on the texters.

Yeah adding in Wrong Number as a response choice for the initial question is part of script creation for a Campaigns, it is not something texters can do, it's an admin thing. But once it's in as an option, it's very easy for texters to use.

**Comment by arena** [comment]
@joshco I think I'm using a fork of Spoke that has a feature not in the root version --- didn't realize that the fork I'm using had custom features.

**Comment by arena** [comment]
I think getting texters to tag voters is a valuable feature that goes hand-in-hand with responding ... but I see how the feature not existing makes this feature improvement request a little impossible

**Comment by joemcl** [comment]
@arena totally agree with that, and there is stuff in https://github.com/politics-rewired/Spoke fork that would be handy to have in MoveOn/Spoke . See #1157 .

**Comment by arena** [comment]
Closing. This is only relevant to the Politics Rewired branch
