### ISSUE TITLE
Feature Request: Streamline tagging for texters

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1263]
**Problem**
Many clicks are required to apply a tag
It's difficult to see if a tag is applied to a conversation

**Proposed Solution**
Streamline tag management. I suggest taking inspiration from an app like Trello where the interaction is: (1) click on "TAGS", (2) click any applicable tags (make a checkmark appear on the clicked label), then (3) click outside --> 3 clicks to get tags, no more save button.
(Trello uses labels, not tags, but same thing)

Make applied tags show at the top of the conversation
Once a tag is applied, show it at the top (ideally color coded) and make it clickable to reveal the same tag menu that you can use to apply tags from the "TAGS" button. 

Wrinkle: the Escalate tag could be in a separate area with a note about how to use it. Something like: horizontal line, "Use this tag sparingly: [escalate]"

**Visuals**
I've started a Figma file with some screen shots of the current design (Fall 2019), some inspiration, and the beginning of some mockups. Let me know if you are going to work on this and I'll happily dial in the mockups based on available libraries, etc. 
https://www.figma.com/file/mx3shfewd8IETe10qaSMFu/Streamline-Tagging-in-Spoke?node-id=0%3A1

**Comment by joemcl** [comment]
@arena cool but you're looking at a different fork of Spoke than what's in branch main here. Branch main here does not (yet) have Manage Tags.  Which org are you texting with? cc: @ibrand .

**Comment by arena** [comment]
I'm using the instance deployed by ResistanceLabs, have no idea which fork it is

**Comment by joemcl** [comment]
OK then  - so let's find that on GitHub.

**Comment by joemcl** [comment]
so @arena looks like you wanna be filing Issues at https://github.com/politics-rewired/Spoke , and hi and FYI @ben-pr-p and @bchrobot  .

**Comment by joemcl** [comment]
@arena you're using this flavor of Spoke, right - https://rlabs.spokerewired.com ?

**Comment by arena** [comment]
I think we should close this issue here and ideally it could be packaged into a pr once the feature is streamlined. Would make texting for rlabs so much nicer for so many volunteer's thumbs.

**Comment by arena** [comment]
If nobody is opposed, I'm going to close this. (If you wanted it open, please open it up again)

**Comment by arena** [comment]
@joemcl I was just looking at this (as part of a design presentation about my contribution to Spoke) and I just wanted to say thank you for figuring out that I had posted to the wrong repo --- it seems like I didn't thank you properly then. And I'm so glad I found this community!! :)
