### ISSUE TITLE
Feature Request: allow csv required headers to be first_name, etc instead of firstName...

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#1272]
Many csv generators from CRMs, etc create headers list `first_name`, `last_name` and some do not support uppercase characters at all.  In order to avoid the need to manually edit csv headers before upload.

**Describe the solution you'd like**
Instead of blocking CSV uploads that have first_name, last_name instead of firstName, etc columns, either header-style should succeed in uploads.

This is entirely on the front-end -- the related code is here:
https://github.com/MoveOnOrg/Spoke/blob/main/src/lib/index.js#L127

Code will probably need to change the validation part a bit and then the function at the bottom `convertRowToContact`
And then, of course, we'll need to change the documentation in src/components/CampaignContactsForm.jsx

![spoke_uploadcontacts](https://user-images.githubusercontent.com/52117/68426636-88bbd000-0176-11ea-8e2f-d99a3f3644e3.png)

**Comment by tom-raley** [comment]
Mind if I give this a go?

**Comment by schuyler1d** [comment]
Go for it!

**Comment by tom-raley** [comment]
Apologies, I really haven't had much time to work on this and likely won't for some time. Someone else is welcome to try it out!

**Comment by schuyler1d** [comment]
> Apologies, I really haven't had much time to work on this and likely won't for some time. Someone else is welcome to try it out!

Sorry Tom -- please ping us here or in slack and we can find another issue when you're free.  Thanks for your interest in the project -- please come back soon :-)
