### ISSUE TITLE
Bug: TextingView (AssignmentTexterContact) does not show action buttons if screen is >= 450px and <750px 😢

### ISSUE THREAD

**Issue by lperson** [ProgressiveCoders/Spoke#1305]
# This is a placeholder.  I'll fill in the details later.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Desktop or Mobile?

**Additional context**

**Comment by arena** [comment]
I've noticed this too

**Comment by arena** [comment]
<img width="654" alt="Screen Shot 2020-01-08 at 7 33 00 PM" src="https://user-images.githubusercontent.com/411070/72035806-c2c85180-324d-11ea-9f83-76284f3dc2a5.png">
notice that there are no buttons at the bottom

**Comment by ibrand** [comment]
@arena is this a problem on any cellphones? Or is that a screensize that is mostly affecting tablets?

**Comment by arena** [comment]
I haven't used Spoke on a tablet, but I've noticed this issue while texting on desktop. E.g. split screen watching election results while responding to texts

**Comment by arena** [comment]
Note: to reproduce this you must reload.
@lperson I know you have been meaning to add the steps to reproduce.

**Comment by ibrand** [comment]
Closing because the new texter UI includes this! #1493
