### ISSUE TITLE
yarn install No such file or directory

### ISSUE THREAD

**Issue by eshaw** [ProgressiveCoders/Spoke#1316]
Hello, I'm trying to install Spoke on Ubuntu 19.04 and get an error at the point where I have to use yarn to install packages. I'm not exactly sure what I'm doing wrong. The error suggests that I'm missing a file.

**Comment by ibrand** [comment]
Hey @eshaw do you have the exact error message handy that you could paste here for more context? And could you step through what steps you've done so far? A terminal copy paste would work here

**Comment by eshaw** [comment]
I run the following command in the Spoke base directory:
yarn install
And get the following error:
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
So, far I've done steps 1 and 2 in the Downloading section and installed yarn with the following commands:
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update && sudo apt install --no-install-recommends yarn

**Comment by ibrand** [comment]
This sounds to me like your installation of yarn itself might have a problem since it's not recognizing the command "install" have you seen yarn work on your machine in the past?

Have you seen node or npm work on your machine in the past?

**Comment by ibrand** [comment]
@eshaw did you make any progress on this? Was it a problem with yarn itself?

**Comment by ibrand** [comment]
Closing because this looks to be a problem with yarn rather than Spoke
