### ISSUE TITLE
RFC: outgoing message handlers

### ISSUE THREAD

**Issue by lperson** [ProgressiveCoders/Spoke#1318]
## Proposal:
What I'm proposing will be like #1317 except for outgoing messages.

## Motivation:
**Profanity filter** -- don't send messages if the tester is using profane or abusive language.

## Detailed Design:
TBD.  This is a placeholder.

## Additional Context:
Not at this time.

**Comment by ibrand** [comment]
This is addressed in v7.0 🎉
