### ISSUE TITLE
RFC: reconcile features from the WFP fork

### ISSUE THREAD

**Issue by lperson** [ProgressiveCoders/Spoke#1320]
Related project: [Bring work in WorkingFamilies/Spoke fork into MoveOnOrg/Spoke](https://github.com/MoveOnOrg/Spoke/projects/14)

## Proposal:
We added [enhancements and features in the Working Families Party fork of Spoke](https://github.com/WorkingFamilies/Spoke/pulls?page=2&q=is%3Apr+created%3A%3E%3D2019-06-01&utf8=✓) during 2019.  Let's bring that work into the MoveOn fork in a manner consistent with the established change-management process.

## Motivation:
Some of the features and enhancements are building blocks for other features (such as profanity filter), the rest are improvements that are nice to have.

## Detailed Design:
These are the changes in question.  Not all WFP PRs are listed here.  Some have already been merged into the MoveOn fork.

Description|Feature, Enhancement, Fix?|WFP PRs|Future direction
-|-|-|-
Select multiple campaigns in message review|Enhancement|[96](https://github.com/WorkingFamilies/Spoke/pull/96) [97]( https://github.com/WorkingFamilies/Spoke/pull/97) [113](https://github.com/WorkingFamilies/Spoke/pull/113)|
Suspended texter status|Feature|[98](https://github.com/WorkingFamilies/Spoke/pull/98) Suspended texter cutoff [136](https://github.com/WorkingFamilies/Spoke/pull/136)|Suspended testers should not be able to text or reply, and it should not be possible to assign contacts to them|
Google doc interactions import|Fixes|[99](https://github.com/WorkingFamilies/Spoke/pull/99)|
Limit users available in texter filter to those in selected campaigns|Enhancement|[100](https://github.com/WorkingFamilies/Spoke/pull/100) Use of campaigns filter instead of campaignId not in MoveOn fork|
Paginated, searchable people page with other enhanements|Enhancement|[101](https://github.com/WorkingFamilies/Spoke/pull/101) [105](https://github.com/WorkingFamilies/Spoke/pull/105) [110](https://github.com/WorkingFamilies/Spoke/pull/110) [137](https://github.com/WorkingFamilies/Spoke/pull/137) [140](https://github.com/WorkingFamilies/Spoke/pull/140)|
Conversation permalink (useful when discussing a conversation in slack, for example)|Feature|[103](https://github.com/WorkingFamilies/Spoke/pull/103) [104](https://github.com/WorkingFamilies/Spoke/pull/104)|
Use auth0 to initiate password reset when not using local passport strategy|Enhancement|[106](https://github.com/WorkingFamilies/Spoke/pull/106)|
Various message review usability improvements|Enhancement|[107](https://github.com/WorkingFamilies/Spoke/pull/107) [108](https://github.com/WorkingFamilies/Spoke/pull/108) [109](https://github.com/WorkingFamilies/Spoke/pull/109)  [111](https://github.com/WorkingFamilies/Spoke/pull/111) [112](https://github.com/WorkingFamilies/Spoke/pull/112) [120](https://github.com/WorkingFamilies/Spoke/pull/120) [138](https://github.com/WorkingFamilies/Spoke/pull/138) [139](https://github.com/WorkingFamilies/Spoke/pull/139)|
Texter assignment usability|Enhancement|[114](https://github.com/WorkingFamilies/Spoke/pull/114)|
Conversation info dialog (on texter view, allows testers to get information about a conversation to use when discussing a conversation slack for example)|Feature|[115](https://github.com/WorkingFamilies/Spoke/pull/115)|
Paginated campaigns page with searching and sorting|Enhancement|[116](https://github.com/WorkingFamilies/Spoke/pull/116)|
Stop popups when loading interactions panel on Safari|Fix|[117](https://github.com/WorkingFamilies/Spoke/pull/117)|
Package updates|Enhancement|react-formal [121](https://github.com/WorkingFamilies/Spoke/pull/121) **_[MoveOn PR 1178](https://github.com/MoveOnOrg/Spoke/pull/1178)_**|
Improve performance of interaction steps editor|Enhancement|[122](https://github.com/WorkingFamilies/Spoke/pull/122) [124](https://github.com/WorkingFamilies/Spoke/pull/124)  **_[MoveOn PR 1179](https://github.com/MoveOnOrg/Spoke/pull/1179)_**|
Tagging|Feature|[123](https://github.com/WorkingFamilies/Spoke/pull/123) [128](https://github.com/WorkingFamilies/Spoke/pull/128) [131](https://github.com/WorkingFamilies/Spoke/pull/131) [132](https://github.com/WorkingFamilies/Spoke/pull/132) [133](https://github.com/WorkingFamilies/Spoke/pull/133) [134](https://github.com/WorkingFamilies/Spoke/pull/134) [135](https://github.com/WorkingFamilies/Spoke/pull/135)|We're going to want to put this feature in front of people who care about texter experience (organizers? a UX volunteer?).  Right now the only way for a texter to apply a tag is by skipping a response, meaning there's a user-facing change in response skipping.  Also, feedback from WFP indicates that in order to surface tags, they need to keep refreshing message review.  We may want to think about either making it a workflow, so there is a queue of new tags for organizers to look at, or creating a saved search feature in message review.
Fix message sending from message review (ensure it works in WFP fork)|Fix|[125](https://github.com/WorkingFamilies/Spoke/pull/125)|
Timestamps on messages in message preview|Enhancement|[129](https://github.com/WorkingFamilies/Spoke/pull/129) [130](https://github.com/WorkingFamilies/Spoke/pull/130)|

## Additional Context:
A simple merge of the MoveOn fork and the WFP fork is difficult.  WFP wanted to move quickly in 2019 so we made changes that went into production without code review and without the usual review-test-staging-merge process in the MoveOn fork.  (Note that WFP has been running a [branch](https://github.com/WorkingFamilies/Spoke/tree/staging_20191102) in production.) The WFP fork drifted far from the MoveOn fork, and attempts to merge have run into dozens of conflicts.

**Comment by Frydafly** [comment]
Does the WFP parity project completion also resolve this issue? @lperson @schuyler1d

**Comment by schuyler1d** [comment]
YES!
