### ISSUE TITLE
Select multiple campaigns in message review

### ISSUE THREAD

**Issue by lperson** [ProgressiveCoders/Spoke#1322]
As part of RFC #1320 and the project [Bring work in WorkingFamilies/Spoke fork into MoveOnOrg/Spoke](https://github.com/MoveOnOrg/Spoke/projects/14), merge the work in these WorkingFamiles/Spoke PRs:
- [96](https://github.com/WorkingFamilies/Spoke/pull/96) 
- [97]( https://github.com/WorkingFamilies/Spoke/pull/97) 
- [113](https://github.com/WorkingFamilies/Spoke/pull/113)

**Comment by ibrand** [comment]
Closing cause this has already been merged in #1339
