### ISSUE TITLE
Suspended texter status

### ISSUE THREAD

**Issue by lperson** [ProgressiveCoders/Spoke#1323]
As part of RFC #1320 and the project [Bring work in WorkingFamilies/Spoke fork into MoveOnOrg/Spoke](https://github.com/MoveOnOrg/Spoke/projects/14), merge the work in these WorkingFamiles/Spoke PRs:
- [98](https://github.com/WorkingFamilies/Spoke/pull/98) 
- [136](https://github.com/WorkingFamilies/Spoke/pull/136)

This allows an administrator to mark a user as suspended in the people page and suspended users can't send initial texts or replies.

**Comment by ibrand** [comment]
Closing in favor of work in flight on #1487
