### ISSUE TITLE
Paginated, searchable people page with other enhancements

### ISSUE THREAD

**Issue by lperson** [ProgressiveCoders/Spoke#1326]
As part of RFC #1320 and the project [Bring work in WorkingFamilies/Spoke fork into MoveOnOrg/Spoke](https://github.com/MoveOnOrg/Spoke/projects/14), merge the work in these WorkingFamiles/Spoke PRs:

- [101](https://github.com/WorkingFamilies/Spoke/pull/101) 
- [105](https://github.com/WorkingFamilies/Spoke/pull/105) 
- [110](https://github.com/WorkingFamilies/Spoke/pull/110) 
- [137](https://github.com/WorkingFamilies/Spoke/pull/137) 
- [140](https://github.com/WorkingFamilies/Spoke/pull/140)

**Comment by ibrand** [comment]
Currently in #1538 to be merged soon
