### ISSUE TITLE
Conversation permalink

### ISSUE THREAD

**Issue by lperson** [ProgressiveCoders/Spoke#1327]
Useful when discussing a conversation in slack, for example)

As part of RFC #1320 and the project [Bring work in WorkingFamilies/Spoke fork into MoveOnOrg/Spoke](https://github.com/MoveOnOrg/Spoke/projects/14), merge the work in these WorkingFamiles/Spoke PRs:
- [103](https://github.com/WorkingFamilies/Spoke/pull/103) 
- [104](https://github.com/WorkingFamilies/Spoke/pull/104)

**Comment by schuyler1d** [comment]
this is in https://github.com/MoveOnOrg/Spoke/pull/1538
`<assignmentId>/allreplies?contact=<contactId>` will work.

**Comment by ibrand** [comment]
This should be done!
