### ISSUE TITLE
RSVP Syncing with Action Kit

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#133]
- [ ] User rsvp for an event in spoke should sync with Action Kit

**Comment by mathemagica** [comment]
- [ ]  write a query that gives us a csv of contacts + page_id, event_id, user_id (ak id) from data warehouse (or make sure your test data includes these fields for your initial contact list)
See issue --> https://github.com/MoveOnOrg/Spoke/issues/176

- the admin imports that csv to spoke on campaign creation 

- [ ] in ${handler}.js load metadata associated with the contact (event_id, user_id, page_id)

- [ ] In ${handler}.js try making an http call that includes AK_USER, AK_PASSWORD, AK_BASEURL like https://github.com/MoveOnOrg/python-actionkit/blob/public-master/actionkit/api/base.py

- [x] 3.5 store AK_USER, AK_PASSWORD, AK_BASEURL in .env (and eventually the config we deploy prod with too)

- [ ] report the http post to create the event signup like https://github.com/MoveOnOrg/python-actionkit/blob/public-master/actionkit/api/event.py

**Comment by shakalee14** [comment]
lets split the last bullet point out.

**Comment by shakalee14** [comment]
Step 1, we want a query to return an actual csv? thats downloaded to your computer, and then we import that csv right back into spoke? 
(question about step 1 and 2). and the csv is campaign specific that includes info on folks who RSVP yes (so could just be akids and the event_id). What is a page_id - thats ak related? is that info that needs to be initially included in the contacts import?

And then would the user story for these 2 steps be, I as a owner, can click a button that downloads a csv of rsvp folks, and then click on an upload button and upload the csv I just downloaded?

**Comment by shakalee14** [comment]
- Custom fields is broken --> currently cant successfully use them if added which blocks implementation of this issue.  

Issue tracked here: https://github.com/MoveOnOrg/Spoke/issues/183
