### ISSUE TITLE
Fix message sending from message review

### ISSUE THREAD

**Issue by lperson** [ProgressiveCoders/Spoke#1337]
As part of RFC #1320 and the project [Bring work in WorkingFamilies/Spoke fork into MoveOnOrg/Spoke](https://github.com/MoveOnOrg/Spoke/projects/14), merge the work in this WorkingFamiles/Spoke PR:
- [125](https://github.com/WorkingFamilies/Spoke/pull/125)

**Comment by ibrand** [comment]
Does this mean that sending a message from message review is currently broken but should work?

**Comment by lperson** [comment]
I don't know.  This issue could be resolved with a code change or it could be resolved by determining that it is not broken.  It was broken at some point in the WFP fork though.

**Comment by ibrand** [comment]
<img width="878" alt="Screen Shot 2020-01-21 at 11 37 32 AM" src="https://user-images.githubusercontent.com/3953117/72823930-7106ca80-3c42-11ea-8461-3fa70a8c2388.png">


Can confirm that this is broken. I'll open a bug ticket for it if it doesn't already exist

**Comment by lperson** [comment]
@ibrand As you confirmed in an email it doesn't work.  I'm about to open a PR to fix it though.
