### ISSUE TITLE
Bug: Dynamic assignment should allow a blank MAX_CONTACTS_PER_TEXTER variable but does not

### ISSUE THREAD

**Issue by ibrand** [ProgressiveCoders/Spoke#1349]
**Describe the bug**
The intended usage of the env var `MAX_CONTACTS_PER_TEXTER` was to allow texters to choose as many texts as they'd like if the var was left blank. Instead leaving the var blank makes dynamic assign no longer an option.

**To Reproduce**
1. Set `MAX_CONTACTS_PER_TEXTER` either to nothing or to 0
2. See that dynamic assignment is no longer available

**Expected behavior**
We expect that if `MAX_CONTACTS_PER_TEXTER` is blank, a texter can text as many texts as they'd like and if `MAX_CONTACTS_PER_TEXTER` is 0, dynamic assign is off.

**Additional context**
This was first surfaced in #1066 and so the context of that discovery process is there.

**Comment by ibrand** [comment]
RFC #1533 would impact dynamic assign in a way where this might not be an issue anymore, but that's unclear

**Comment by schuyler1d** [comment]
I believe this is resolved, but we should confirm.  Note -- setting max contacts for a specific assignment to 0 should stop that texter from texting.  Setting MAX_CONTACTS env var to 0 doesn't make sense -- that would block all texters from texting.  Setting it to blank means there is no maximum.

**Comment by schuyler1d** [comment]
Realizing this shouldn't be an issue after the rewrite -- max contacts relates to dynamic assignment very differently now
