### ISSUE TITLE
Bug: Impossible to edit a reply when starting from a canned response on mobile (must delete and start from scratch)

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1356]
**Description**
When you (a texter) try to edit a canned response on your mobile device, the text gets selected-all for you and you can't un-select-all to edit. You either have to delete it and type from scratch or copy it ...if you can manage to click under all the overlapping buttons.. and then paste and then you can edit it if you are lucky... but even then it's hard to see what you are typing because of all the overlapping buttons. This is encountered in the Send Replies flow. 

**To Reproduce**
1. Go to 'Send Replies' on your mobile device (I'm using a Pixel 2 + Chrome)
2. Click on a canned response, either an answer to the current question or an other response option
3. Click on the text to edit it

**Expected behavior**
A cursor where you clicked 

**Actual behavior**
All text gets selected and when the keyboard slides up button completely overlap the text field making it impossible to deselect or edit the text unless you delete it and start from scratch. 

**Screenshots**
![un-editable-reply](https://user-images.githubusercontent.com/411070/72034009-b5f52f00-3248-11ea-811f-65cd39103c16.png)

**Platform**
Android 10
Mobile Chrome (Jan 2020)

**Additional context**
A scenario is something like 
recipient: "I can't, I'm really sick and I'm in the hospital about to get surgery."
texter: "Wishing you the best!" + "canned No response"

**Comment by ibrand** [comment]
Closing because the new texter UI includes this! #1493
