### ISSUE TITLE
Feature Request: Display the Account view with the user's current profile info in the appropriate form fields (instead of showing a blank form)

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1358]
**Problem**
The account information form gets cleared upon viewing (not sure why) but it's confusing to try to remember which email and phone you used. 

**Solution**
When the Account view is displayed, populate the form with the user's current profile info.

On the front end the fields are labeled First Name, Texting Alias (if it exists), Last Name, Cell Number, Email, and Password. The password is not displayed, of course. 

On the backend the fields are *placeholder for the names of these fields on the backend*

**Related Features**
Layout of the form: #1357
Texting Alias feature: #1109

**Comment by arena** [comment]
Anybody know what these variables are named? Please suggest an edit to the description above.

**Comment by arena** [comment]
@lperson is this a duplicate of an issue you created?

**Comment by arena** [comment]
This is fixed now.
I don't know who fixed it, but THANK YOU!!
Was it you, @filafb or @lperson ?
@ibrand , ok if I close it?

**Comment by arena** [comment]
I think @lperson had a similar issue that was redundant to this one. I'll try to find it later... but I think you can verify that the form gets populated and close this. Or take my word for it, and close this issue.

**Comment by ibrand** [comment]
Yay thanks for letting me know it's fixed @arena ! Closing this
