### ISSUE TITLE
Feature Request: Change the label on the "Send Replies" button to "Respond"

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1362]
**Problem**
The current label on the button a texter clicks to respond to replies doesn't align with the lexicon used in the documentation. Everything should align with these definitions
- response = something a spoke user sends 
- reply = incoming message from a contact

The current button confusingly reads, "Send Replies". Let's change it to say, "Respond".

**Solution**
Change the button label to "Respond"

![image](https://user-images.githubusercontent.com/411070/72180913-1301f980-339d-11ea-963d-602434a6f6fc.png)

**Comment by arena** [comment]
an added benefit is that the button becomes smaller and easier to fit in a smaller campaign todo card down the line and takes up less space on small mobile screens.

**Comment by DinahSanders** [comment]
I like this and just want Erik to weigh in on whether this is a change we can get rolled out in time to update documentation/onboarding and retrain our existing testers before things get too busy. (That countdown to election day weighs upon my mind... 🙂)

**Comment by arena** [comment]
I think code wise, it's a pretty light lift. (and I almost never assume something is easy)

**Comment by arena** [comment]
I'm going to set up my development environment so I can do this and run the tests... 
getting there
![image](https://user-images.githubusercontent.com/411070/73315461-0414a700-41e5-11ea-88aa-5e6ec140d60c.png)

**Comment by arena** [comment]
I'm giving this a shot.. I'll un-assign myself if I get too stuck

**Comment by ibrand** [comment]
@arena awesome!

**Comment by arena** [comment]
unassigned myself. ...am unable to put more hours into setting up a development environment right now and keep encountering errors.

**Comment by arena** [comment]
This is the part of the MoveOn docs that will need to be updated ...and there are screenshots... 
Copy: https://textteamhub.wordpress.com/faq/#respondingtoreplies
Screenshot: https://textteamhub.files.wordpress.com/2018/09/spokehomeexample.png
There are probably more screenshots. It would be nice to browse the directory of images used in the docs.

**Comment by arena** [comment]
🙌
