### ISSUE TITLE
Errors prohibiting Heroku deploy on v4.1

### ISSUE THREAD

**Issue by alexanderankin** [ProgressiveCoders/Spoke#1364]
None of the instructions on the README work, should i expand on this issue with the ways in which it fails, or is there just newer docs somewhere. Thanks all!

**Comment by alexanderankin** [comment]
heres what the heroku deploy shows for 4.1:

```
Step 17/17 : CMD ["npm", "start"]
 ---> Running in 35b621c683a8
Removing intermediate container 35b621c683a8
 ---> 40c485d2f4f5
Successfully built 40c485d2f4f5
Successfully tagged 231f79316f17cbb16c28969ea7192ff67608360f:latest
=== Pushing web (Dockerfile)
Tagged image "231f79316f17cbb16c28969ea7192ff67608360f" as "registry.heroku.com/unitespoke/web"
The push refers to repository [registry.heroku.com/unitespoke/web]
ffa32c3c2180: Preparing
a11ebcdb0bda: Preparing
82c01f95f66d: Preparing
9af892bcffdc: Preparing
28bf756b6f8e: Preparing
4c299e1e70d5: Preparing
f1b5933fe4b5: Preparing
4c299e1e70d5: Waiting
f1b5933fe4b5: Waiting
ffa32c3c2180: Pushed
28bf756b6f8e: Pushed
9af892bcffdc: Pushed
82c01f95f66d: Pushed
f1b5933fe4b5: Pushed
a11ebcdb0bda: Pushed
unknown blob
=!= Build failed due to an error:
=!= push step: exit status 1
If this persists, please contact us at https://help.heroku.com/.
```
![image](https://user-images.githubusercontent.com/8921892/72225011-6d8e8780-354e-11ea-8cb3-91d9276a5e7e.png)

**Comment by alexanderankin** [comment]
4.0 worked, however.

**Comment by alexanderankin** [comment]
when running docker from 4.0 image with docker daemon, not on heroku, even if passport strategy is local, the logout button on the admin screen takes you to whatever value is in the auth0 domain env var.

**Comment by ibrand** [comment]
@alexanderankin Did you resolve this issue? Does 4.1 deploy to heroku safely?

**Comment by alexanderankin** [comment]
@ibrand no, actually, I had to stick with 4.0 and so far, there is an issue with all forms showing "[Object object]" for their data instead of populating fields, also its difficult for a volunteer to identify who they are talking to (no last name). I think i'll have to try compiling it locally to break down what is happening, but i havent had a chance to do that yet.

**Comment by ibrand** [comment]
Ok, in that case, I'm going to reopen this as a flag to us since we'll be cutting 5.0 soon and I want to get Heroku running again for newer versions since it's a critical deployment platform. Thanks for flagging this issue!  Mind if I rename it to "Errors prohibiting Heroku deploy on v4.1" to be more explicit? @alexanderankin

**Comment by alexanderankin** [comment]
@ibrand do not mind. I will fill in will more details if i get any time whatsoever in the near future. some of the output to the log was confusing to me, where should i ask questions about that, is this the right place for that, for example what does it mean that its pushing in step 17?

**Comment by alexanderankin** [comment]
returning to this this weekend

**Comment by alexanderankin** [comment]
trying to simulate starting it on local, and usually i set my repositories up so there is a "db create" script and then a "build + run/watch" step, and frankly yesterday the scripts just kinda blew my mind and could not get the migrations to work or anything. working of the master branch.

**Comment by ibrand** [comment]
@alexanderankin by
> trying to simulate starting it on local

Do you mean you're trying to hook up Heroku scripts to look the same as the scripts for running your local dev env?

**Comment by alexanderankin** [comment]
i was trying to run the actual build steps that heroku would take, i know you can actually run the heroku image on your local machine but i wasnt trying to do that, i was trying to trace what would be run. The way i usually set up my projects, the scripts are very minimal, a watch, a build, a start, migrate. occasionally ill have some thing fancy likecode coverage.

What i really want to do is get a sense of how you guys run the code locally, surely you dont have docker as part of the way you run it to see if a visual change is successful?

**Comment by ibrand** [comment]
When I run code locally (which is totally separate from Heroku) I run `yarn dev` using the set up in the README. There are some folks who use Docker for that.

**Comment by ibrand** [comment]
@alexanderankin I haven't seen any trouble with Heroku deploys in newer Spoke versions (5.x) -- I would suggest upgrading to those if you're still having trouble.
