### ISSUE TITLE
Feature Request: Move the "Home" button to the far left (before the name and time of the conact)

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1375]
**Problem**
The home icon jumps around when texting and should feel more standard and stay in the same place so that it acts as reliable navigation.

**Solution**
Move the icon to the top left (see attached wireframe that has some other features ..but focus on the position of the home icon) 

This will stop it from jumping around, and keep it in a predictable location

![image](https://user-images.githubusercontent.com/411070/72652178-8924d400-393a-11ea-9aac-e9840a6b2292.png)

**Comment by arena** [comment]
I'm planning to update this so that it's buttons for a few common (ideally, short) responses and then a menu for overflow that would have all of them. 
(...maybe responses could have a shortcut label??)

**Comment by ibrand** [comment]
Closing because the new texter UI includes this! #1493
