### ISSUE TITLE
Feature Request: One-Click "Send Initial" for all assigned texts

### ISSUE THREAD

**Issue by allisonChilton** [ProgressiveCoders/Spoke#1376]
**Is your feature request related to a problem? Please describe.**
Having to click "Send" repeatedly for the first batch of texts is time consuming.

**Describe the solution you'd like**
A singular button to send the initial batch of texts.

**Comment by DinahSanders** [comment]
Note: federal law prohibits sending an automated blast message to those who haven’t opted in for it, thus Spoke is used for peer-to-peer texting. 

In addition to the legal side, peer-to-peer also offers great ability to interact with members and voters via conversations.

**Comment by arena** [comment]
There's a feature on desktop that does this sorta... Not a single press, but if you keep holding the return key down, Spoke keeps sending. I've been meaning to design and suggest a tooltip that shows up after 5 consecutive sends or something like that

**Comment by DinahSanders** [comment]
That feature is to provide accessibility support for sending by differently abled texters for whom separate pressing of the button is problematic.

MoveOn still requires continuous monitoring of outgoing texts in accordance with federal law and the Text Team Pledge:

> 9. In accordance with federal law, when texting with MoveOn, I will always send each text manually, never using devices such as auto clicker software.

**Comment by ibrand** [comment]
Thanks @DinahSanders I appreciate you filling in the context here. @allisonChilton thanks for writing up the issue unfortunately we can't make this change. Closing this one.
