### ISSUE TITLE
Feature Request: Add configurable Privacy Policy link to sign up page

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1392]
**Problem**
When signing up, potential users want to review the privacy policy.

**Solution**
A spot for the privacy policy on the sign up screen and notes about how to configure it in the deploy instructions. 

**Additional context**
Maybe somebody more familiar with how this might work on the dev side should fill in some details... I think the link should go at the bottom of the page along with Terms of Service. I assume the privacy policy varies by instance.. so no specific privacy policy should be hard-coded in the open-source repo.

**Comment by ibrand** [comment]
We'd need to add this to the auth0 log in flow and local log in flows. Currently auth0's custom login page comes from a copypaste of the code at the bottom of the page in the [Auth0 setup guide](https://github.com/MoveOnOrg/Spoke/blob/main/docs/HOWTO-configure-auth0.md)

This should be ready for someone to take on. Ask any questions here!

**Comment by Akash-Jairam** [comment]
I'd like to pick this up. I hope to make a pr in the next few days. Will reach out if I have questions

**Comment by arena** [comment]
Awesome!
I hardly remember creating this issue -- I have a feeling I was doing a user interview with an admin and they needed it but didn't have a github account. 
Thank you!!!

**Comment by Akash-Jairam** [comment]
Just adding my questions here for more visibility:
- Is it sufficient add a section in the UI to define the privacy policy as well the link? 
- Seeing that it might by instance, what kind of logic are we using to select the privacy policy that is going to be displayed?

**Comment by arena** [comment]
@ryanjcrump is it possible that this came up via a WFP need? 

My inclination is to suggest that it would be text file or markdown file that could be added to an instance and then a link to it gets toggled on during the process of setting up the instance. Does that sound right? That would make it pretty light in terms of UI (no UI) but still make the terms editable.

**Comment by arena** [comment]
also, just looking at this some more --- it seems that the terms of service and privacy policy are all one link on the sign up screen. So, I think that is the context. Someone was wondering why they needed to combine those two documents instead of having two separate links
![image](https://user-images.githubusercontent.com/411070/114469409-f2c57980-9ba1-11eb-86be-81f0d323e204.png)

**Comment by Akash-Jairam** [comment]
I don't quite recall seeing the TOS and privacy policy links when I was running the program locally with and without Auth 0. Can you please share the steps you performed to get to that screen?

**Comment by Frydafly** [comment]
@Akash-Jairam I believe it usually appears when you click the sign up tab in an auth0 login (@arena do you have more context for him?)

In https://github.com/MoveOnOrg/Spoke/blob/main/docs/HOWTO-configure-auth0.md  under "code to paste to Auth0", there is this blob that I think creates this? 

```
languageDictionary: {
        title: 'Spoke',
        signUpTerms: 'I agree to the <a href="YOUR_LINK HERE" target="_new">terms of service and privacy policy</a>.'
      },
```

**Comment by Akash-Jairam** [comment]
Ah, sorry I missed that when running the Auth 0. So all we need to do is to split the links for the Auth 0 code frag?

**Comment by Akash-Jairam** [comment]
Made a PR based on our discussion and I added an extra point to remind the user to update the Privacy Policy and TOS
