### ISSUE TITLE
Feature Request: Change the label on the "Skip Reply" button to "Skip"

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1398]
**Problem**
The interface has some clutter, I want to simplify and make things more compact wherever possible

**Solution**
Shorten the "Skip Reply" button label in the Responding flow to simply, "Skip"

**Screenshots (Current & Suggested)**
Currently:
![image](https://user-images.githubusercontent.com/411070/73562691-7f0dd580-4410-11ea-9fd0-e4ee5dcacea7.png)
Modified:
![image](https://user-images.githubusercontent.com/411070/73562939-06f3df80-4411-11ea-865b-6c38de9d03be.png)

**Comment by ibrand** [comment]
Closing because the new texter UI includes this! #1493
