### ISSUE TITLE
Bug: Send button is not aligned horizonally with other buttons

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1399]
**Bug**
The action buttons at the bottom of the Respond UI are misaligned horizontally.

**To Reproduce**
1. Respond to a message
2. Look at the SEND button
(Noticeable on desktop)

**Expected**
Alignment

**Screenshots & Clue**
![image](https://user-images.githubusercontent.com/411070/73562851-cf853300-4410-11ea-941b-8fb792163053.png)

![image](https://user-images.githubusercontent.com/411070/73562897-e75cb700-4410-11ea-807c-8168f67b1069.png)

**Comment by rahatarmanahmed** [comment]
I can try to tackle this. it's been bugging me as a texter :)

**Comment by arena** [comment]
I think it's covered by @schuyler1d  in his current work on the mobile friendly update

**Comment by arena** [comment]
But if it's easy and you don't mind doing it, then possibly seeing everything change, I agree --- it bugs.

**Comment by rahatarmanahmed** [comment]
Is there any documentation on testing scenarios? I want to get some fake replies to my campaign to repro the issue but not sure how. (I'd ask in the slack but it seems like there's a process to getting in, and I'm not really fully committed to being part of that community yet)

**Comment by ibrand** [comment]
@rahatarmanahmed I've been meaning to document this and need to figure out where is the best place. If you want fake replies, include the word "autorespond" in you initial script and make sure you're using fakeservice
