### ISSUE TITLE
Feature Request: Button for "Wrong Number" 

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1401]
**Problem**
Using the menu to pick the Wrong Number response requires extra clicking and slows me down.

**Solution**
I think it's safe to assume every campaign will have a wrong number response (or workflow) and there is room for a button on desktop. So, let's have an easy to click button labeled "Wrong Number" and a redundant link in the menu that might have a more expansive label like, "Wrong Number/Person"

**Additional context**
![image](https://user-images.githubusercontent.com/411070/73567357-1d9f3400-441b-11ea-99c1-b885a05c5d89.png)

![image](https://user-images.githubusercontent.com/411070/73567136-96ea5700-441a-11ea-9b21-9b6eb1db6e4a.png)

Look how long the "Other Responses" list can get -- lots of parsing, lots of scrolling, then the extra click...
![image](https://user-images.githubusercontent.com/411070/73567013-42df7280-441a-11ea-932d-45b8f59e50dd.png)

**Comment by DinahSanders** [comment]
Excellent use of the sparkles emoji. :D  
✨

**Comment by ibrand** [comment]
For what it's worth: we wouldn't have to assume the wrong number response even :) we could only render the button if there's a canned response with the title "Wrong Number"

**Comment by ibrand** [comment]
Closing because the new texter UI includes this! #1493

**Comment by arena** [comment]
🙌✨🏆✨🙌
This ✨saves me SO. Much. Time.✨ Thank you!!!!!
