### ISSUE TITLE
Bug: Missing indicators for required text inputs

### ISSUE THREAD

**Issue by winterlamon** [ProgressiveCoders/Spoke#1433]
**Describe the bug**
Required inputs don't have any indicators--visual or via assistive technology--that the fields are required prior to attempting to submit a form and receiving the form field error.

**To Reproduce**
1. Go to any required input and see that there are no visual indicators
2. Inspect the same input in devtools and observe that the input has no `required` attribute

On the admin dashboard, 
1. Go to the admin dashboard and initiate the creation of a new campaign
2. In the `Basics` section, select a date, save, and close the section. An icon appears to suggest something is wrong/incomplete, but there is no indication what is missing/incorrect.

**Expected behavior**
As a user, I would expect to know when a field is required.

**Screenshots**

<img width="1140" alt="Screen Shot 2020-02-22 at 12 59 02 AM" src="https://user-images.githubusercontent.com/16295605/75087874-ab020f80-5513-11ea-9d74-308bf62d5343.png">

<img width="1140" alt="Screen Shot 2020-02-22 at 12 59 23 AM" src="https://user-images.githubusercontent.com/16295605/75087875-ab9aa600-5513-11ea-92f4-eb464f79cdba.png">

**Platform (please complete the following information):**
 - OS: macOS Catalina (10.15.2)
 - Browser: Google Chrome v80
 - Desktop or Mobile? Desktop
 - Version: v3.1.0

**Comment by ibrand** [comment]
@winterlamon did you end up having any time to work on this?

**Comment by winterlamon** [comment]
@ibrand No. I was waiting for direction about how to best address it.

**Comment by ibrand** [comment]
Ah! I'n sorry for taking this one. It's been coming up really often in admin trainings so I took the easy route and added the word (required) to the end of the field titles
