### ISSUE TITLE
Bug: "Cannot read property 'assignmentId' of undefined" when texting from Message Review

### ISSUE THREAD

**Issue by pfletcherhill** [ProgressiveCoders/Spoke#1437]
**Describe the bug**
When an admin goes into Message Review, selects a conversation, writes a reply, and clicks "Send," an error message pops up saying `Cannot read property 'assignmentId' of undefined`.

**To Reproduce**
1. Go to Message Review
2. Click on any conversation
3. Type a message in the "Send a response" section
4. Click "Send"
5. See error in red

**Expected behavior**
The message should be sent as part of the conversation.

**Screenshots**
<img width="790" alt="Screen Shot 2020-02-27 at 4 50 54 PM" src="https://user-images.githubusercontent.com/1607180/75500363-8c6f9e80-5981-11ea-91e8-17b3069811f1.png">

**Platform (please complete the following information):**
 - OS: MacOS Sierra 
 - Browser: Chrome 80.0.3987.122

**Comment by majnu** [comment]
Hi, I am running into this problem as well. I looked into the table "message" and found that all assignment_id values are null. I just testing Spoke locally with  local authentication and fakeservice.

**Comment by ibrand** [comment]
@pfletcherhill this has been fixed! Upgrade to the latest Spoke and this should be working
