### ISSUE TITLE
Feature Request: Hide past texting assignments

### ISSUE THREAD

**Issue by mx60s** [ProgressiveCoders/Spoke#1438]
**Problem**
Those who have been texting for awhile accumulate a lot of past texting assignments, and have to scroll past all of them to get to the "Reassign replies" button

**Solution**
Hide texting assignments that haven't updated in a day or so, maybe add a link to see them on a different page.

**Comment by ben-pr-p** [comment]
Hey @mx60s , sounds like you're using the fork at https://github.com/politics-rewired/Spoke ! Want to open up the issue over there?

**Comment by ibrand** [comment]
Closing this because it's a Spoke Rewired issue!
