### ISSUE TITLE
Bug: Current Question responses disappearing

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#1442]
Multiple texters are reporting that Spoke is randomly removing options that are in the CURRENT QUESTION menu,

Example here shows only 3 appearing even though there are many more in the campaign, https://spoke.moveon.org/app/3/todos/72571/reply

This is happening at random, meaning will appear this way for some period of time, revery back to normal, then again get buggu.

**Comment by ibrand** [comment]
Closing cause this references an old version of Spoke
