### ISSUE TITLE
Bug: Multiple texters reporting they cannot access replies or texts (Spoke just spins)

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#1443]
When trying to send initial texts or replies, many texters are saying Spoke just spins and spins, never allowing them to access them. This is not happening in all campaigns but appears to be limited to a handful of them, and to a handful of the texters within them.

**Comment by ibrand** [comment]
Closing cause this is referring to an old version of Spoke
