### ISSUE TITLE
Bug: Remove flash of gray background between each sent message when sending

### ISSUE THREAD

**Issue by JesseWeinstein** [ProgressiveCoders/Spoke#1451]
**Describe the bug**
The way the whole screen gets a brief dark gray overlay while each **initial outbound** message is sent is very visually distracting and unpleasant. We should just not do that -- it serves no useful purpose.

**To Reproduce**
1. Send an initial outbound text

**Expected behavior**
The screen stays exactly the same, except that the word "Sending" appears briefly in the middle,
and the count of sent messages goes up. The overall color of the screen does *not* vary. When handling replies, the gray background is still displayed, to make it clear you are handling a different conversation.

**Platform (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Desktop or Mobile? Desktop
 - Version: Unknown

**Comment by JesseWeinstein** [comment]
I think the place to change this is: https://github.com/MoveOnOrg/Spoke/blob/main/src/containers/AssignmentTexterContact.jsx#L64

**Comment by ibrand** [comment]
@schuyler1d I know the "sending" screen is something you've historically liked. Curious for your thoughts there.

@arena I know the sending screen is something you feel 🤷‍♀ about. Curious for your thoughts here too

**Comment by arena** [comment]
The transition is important to meet the user's need to know that they are on a new conversation. It doesn't have to be gray... but it could be confusing if it felt like the message you sent just vanished, when actually you are on a new convo. Imagine the scenario where someone replies with a simple answer and the next person does the same (e.g. Yes) then it would look like you responded and then nothing happened. ...those are my thoughts. 

@JesseWeinstein what are your thoughts on what would be an ideal alternative to signify that the texter is viewing a new convo? If there is no transition how will they know they are on a new convo once they auto-advance? Open to helping with this.. definitely think green and gray are not the most harmonious and would love a more elegant transition.

**Comment by JesseWeinstein** [comment]
Oh, we should certainly leave the gray background when switching conversations when handling *replies* ! I'm only referring to when sending **initial** outbound messages, where people send a lot of them very quickly, in a row, and the gray background becomes a quick set of flashes, that is very visually painful.

**Comment by arena** [comment]
If you get inspired maybe add confetti when sending 🎆

**Comment by ibrand** [comment]
@schuyler1d any thoughts here before I mark this as ready to be worked on?

**Comment by schuyler1d** [comment]
we should wait for Spoke 6.0 (or they can branch off of stage-main branch currently).  But very PRO this.

**Comment by arena** [comment]
My .02 --- there needs to be some sort of feedback that hitting the send button did something even if there is latency. I think it's pretty safe to assume there will be latency at least sometimes and a texter needs to know that the app is responding.

**Comment by JesseWeinstein** [comment]
I'd recommend having just the *button* change color -- that should provide feedback, but not distract people with the whole page flashing.

**Comment by arena** [comment]
@JesseWeinstein I'm not convinced that would be enough visual feedback on mobile when my big finger is covering most of the button.

**Comment by JesseWeinstein** [comment]
Wait -- the **count** changes in any case! That should be plenty of feedback...

**Comment by schuyler1d** [comment]
Also, the name changes (which is pretty big, and at least normally what i'm looking at when sending first messages)

**Comment by arena** [comment]
Here's my take:

As a texter, when I'm sending initial texts, I need to know that they are being sent with via a visual change (a flash works well) that is obvious and not covered by my finger on mobile.

When responding, I need to know that a message is being sent even if there is significant latency. I need more than a name change and a button state change if there is latency and then, ideally, something to clearly communicate that I'm looking at a new convo even if the reply is exactly the same as the last one. 

In my mockups, where I have very limited options, I played with slide and I liked it on mobile. Perhaps an ideation/design session is in order. HMU on ProgCode?

**Comment by arena** [comment]
the hold time in this demo seems way too long, but this might be a good drag-and-drop component to explore
https://jakesidsmith.com/react-reorder/
