### ISSUE TITLE
Feature Request: Clicking campaign cards should open in a new tab

### ISSUE THREAD

**Issue by ibrand** [ProgressiveCoders/Spoke#1470]
**Problem**
When admins click a campaign card in the admin campaign list view, it opens in the same tab. This means that if an admin wants to scroll down the list and open a bunch of campaigns in tabs it's not very easy to do quickly.

**Solution**
Admins should be able to cmd+click (or ctrl+click on windows) to open campaigns in tabs to help with their workflow.

**Context**
<img width="1440" alt="Screen Shot 2020-03-31 at 4 52 15 PM" src="https://user-images.githubusercontent.com/3953117/78074134-2c00c200-7370-11ea-926b-409eeaa3fa67.png">

**Comment by jasmosez** [comment]
I'll work on this one this week!

**Comment by ibrand** [comment]
This was merged!
