### ISSUE TITLE
"Getting the App Running" steps incorrect example SQL

### ISSUE THREAD

**Issue by kylehotchkiss** [ProgressiveCoders/Spoke#1479]
In the `readme.md`'s "Getting the App Running" steps (https://github.com/MoveOnOrg/Spoke#getting-the-app-running), a sample SQL snippet implies any string can be used for invite codes:

```
echo "INSERT INTO invite (hash,is_valid) VALUES ('abc', 1);" |sqlite3 mydb.sqlite
# Note: When doing this with PostgreSQL, you would replace the `1` with `true`
```

While I was deploying to production with `passport_strategy=local`, I was getting error messages in the login API call headers saying invite code was invalid. I dived into the code and [found that the hash should be a UUIDv4 in order to initially register a login for Spoke](https://github.com/MoveOnOrg/Spoke/blob/8642cd3413101c2df5e5c4be5f550ebe63d10ac7/src/server/local-auth-helpers.js#L49-L59). Should the docs be updated to say this?

Thanks for your work developing Spoke,
Kyle

**Comment by ibrand** [comment]
Hey @kylehotchkiss I appreciate you noticing this! That would be a great edition to the docs 👍 would you be up for making a PR?
