### ISSUE TITLE
Saving Answer Options

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#148]
- [x] On campaign create or edit, unlinked answers should save
- [x] On edit, a single question with no next steps should be able to add answers. If you create a script and add a question and add answer options but don't link them to a next script step, they don't save. #158
- [ ] Write a unit test that would have caught this.

**Comment by sandramchung** [comment]
#158 is currently blocking the resolution of the rest of this issue.

**Comment by schuyler1d** [comment]
closing this since script work was fully rewritten by now.
