### ISSUE TITLE
Feature Request: Super volunteers should be able to use message review

### ISSUE THREAD

**Issue by ibrand** [ProgressiveCoders/Spoke#1488]
**Problem**
There are many scenarios where it would be nice for super volunteers to use message review to help out campaign admin.

**Solution**
Allow super volunteers to use message review to
1. Reassign individual threads
2. Reassign in-bulk
3. See a message thread conversation
4. Opt-out the contact on the conversation
5. Send a message on the conversation

This involves making some of the query calls visible in accessRequired() be "SUPERVOLUNTEER" instead of "ADMIN".  There are also some calls for `assignmentRequiredOrAdmin()` which maybe instead of renaming just change the permission check inside that function (src/server/api/errors.js)

This is strictly increasing permissions for supervolunteers.

**Comment by jasmosez** [comment]
I'll work on this.

**Comment by schuyler1d** [comment]
Updated this issue description after discussion with @ErikKirkstein

**Comment by ibrand** [comment]
This was completed in v7.0!
