### ISSUE TITLE
RFC: End-to-End testing using Cypress

### ISSUE THREAD

**Issue by matteosb** [ProgressiveCoders/Spoke#1494]
## Proposal

To replace the currently unmaintained Selenium-based e2e test suite with [Cypress](https://www.cypress.io/) tests and to eventually replace much of the manual QA process with automated tests.

## Motivation

For E2E tests: Spoke is a complex product with lots of different configuration options and limited bandwidth for QA. Having a robust end-to-end test suite should allow the project maintainers to deliver new releases faster and encourage volunteers to commit with confidence. 

For Cypress vs Selenium-based frameworks: In my experience Cypress is a lot faster, more user-friendly, and reliable than Selenium, which leads to broader adoption among developers and better test coverage. It trades some of the flexibility of Selenium for ease of use, which I think is appropriate for Spoke, where we want volunteers to be able to contribute effectively without spending too much time on setting up and learning new tools.

## Detailed Design

We can start with a test suite that runs against a local instance of Spoke with `fakeservice` and run it in CI. Once we have confidence in that, it should be relatively easy to have it run against a remote production-like environment.

We should prioritize covering the following core flows:

* Local authentication strategy
* Campaign creation
* Campaign stats
* Campaign editing
* Message Review
* Adding users and editing permissions
* Texter landing page
* Texter Initial send flow
* Texter response flow
* Tagging (when available)

What else am I missing @schuyler1d and @ibrand?

#### Sponsor Organization (will test alphas/betas)
MoveOn

#### Developer allocated
@matteosb 

#### Planned timeline

The basic set up and a few of the core user flows listed above should take a few days, while more comprehensive coverage could be worked on over the course of a couple months. Ideally, it should be easy enough to add tests that they could be added alongside most new features.

#### Files/File-sections touched

* `__test__/e2e` would be ported to Cypress tests
* CI would be changed to run Cypress tests on every PR and merge to stage-main
* Minimal changes to application code, ideally just adding `data-testid` attributes to components where they don't already exist

#### Existing github issues that this RFC will address
https://github.com/MoveOnOrg/Spoke/issues/382

## Resources:
* https://www.cypress.io/how-it-works
* https://medium.com/@applitools/cypress-vs-selenium-webdriver-better-or-just-different-2dc76906607d
* https://medium.com/front-end-field-guide/why-cypress-is-the-best-way-to-test-64ec0d394bae

**Comment by schuyler1d** [comment]
Yes!  Let's get back integration tests.  When we get this into place, we can delete the __test__/e2e directory.

I think my one request is that we architect and write these so that it can also be run on an external e.g. staging server.  I think that implies two main things:
* doing things through the interfaces wherever possible and at least 'abstracting' out the parts that can't be.
* having some of the 'initialization' parts (first account + org creation + admin login) contained in a way so that they wouldn't need to be run and admin login could have different settings (from the config file, presumably).

**Comment by tmc** [comment]
Can we include some rationale for using cypress over puppeteer?

**Comment by matteosb** [comment]
This is by no means comprehensive, but these are some of the reasons why I think Cypress is more appropriate for E2E testing for Spoke.

* Cypress is more of an "all-in-one solution" for E2E testing, which makes it easy to get started with and requires fewer additional technical decisions. It has a lot of nice built-in features specifically for e2e testing where you would roll your own with puppeteer.
* Very friendly to developers who are new to it because it has a large community, excellent documentation, and an interactive development experience. I would stress that this is very important for a volunteer-driven project like this where we want to minimize ramp-up for new developers with limited bandwidth to dedicate to the project.
* Tests run in the browser. I think this can be a pro or a con depending on context, but it definitely simplifies writing tests against staging/production.
* Support for more browsers. Unfortunately, neither framework support Safari, which might be an argument for a different framework like TestCafe.

I'll note that Puppeteer seems like a better choice for more lightweight unit/integration tests because, for example, we could integrate it into our main jest suite, but here I'm talking specifically about E2E tests that would run against remote production-like environments as well as locally. At the end of the day there are a lot of excellent frameworks and we just have to make a decision.
