### ISSUE TITLE
Feature Request: Make canned responses editable

### ISSUE THREAD

**Issue by ibrand** [ProgressiveCoders/Spoke#1502]
**Problem**
Currently we cannot edit canned responses.

**Solution**
Supervolunteers and admin should be able to edit canned responses

**Context**
This is especially important as we ramp up to add features to canned responses like tags and action handlers.

**Comment by Frydafly** [comment]
@ibrand closing this since this was merged in 7.1 thanks to https://github.com/MoveOnOrg/Spoke/pull/1576
