### ISSUE TITLE
Deprecation: Remove Texter's ability to add their own canned responses

### ISSUE THREAD

**Issue by ibrand** [ProgressiveCoders/Spoke#1523]
**Problem**
Texter's currently have a button to add their own canned responses, but that feature doesn't receive much love and currently doesn't work as expected. If a texter does create a personal canned response, it's actually propagated across the whole campaign which is pretty unfortunate for admin management. From what I can tell, very few texters are actually using this.

**Solution**
Let's remove this feature and deprecate it to remove the tech debt of a broken unmaintained feature.

**Context**
@deasterdaywfp @codygordon @jeffm2001 do any of you encourage the use of this feature? Would we be messing with existing strategies by removing it?

**Comment by jeffm2001** [comment]
Big 👍 to removing it from me

**Comment by ibrand** [comment]
@arena I'd also love to hear from you on this too from the texter side! Do you use this feature? It seems to not be very encouraged by admin, curious to hear about the texter side of this.

**Comment by arena** [comment]
I have no attachment to this feature as a texter and as a designer I don't feel that it automates much. If I want to insert my own pre-written responses and I'm savvy enough to want an automated way to do it, I'll use a utility like Alfred to get it done. It doesn't need to be supported within Spoke.

**Comment by deasterdaywfp** [comment]
I'm also okay with allowing that to drop

**Comment by ibrand** [comment]
Closed in v6.0
