### ISSUE TITLE
Bug: archive/unarchive individual campaign on campaign page don't work

### ISSUE THREAD

**Issue by lperson** [ProgressiveCoders/Spoke#1544]
**Describe the bug**
When I click the archive icon to archive an individual campaign, the campaign doesn't get archived and there's an error in the console.

Every mention of `archive campaign` also applies to `unarchive campaign` when filtered to archived campaigns.

**To Reproduce**
1. Go to admin campaign page.
2. Click on the archive campaign icon.
3. The campaign doesn't change state.
4. There is an error in the console.

**Expected behavior**
1. The campaign becomes archived and there are no errors in the log.
2. The campaign is removed from the active campaigns view.

**Screenshots**

<img width="923" alt="Screen Shot 2020-05-08 at 8 37 05 PM" src="https://user-images.githubusercontent.com/1637288/81459121-3e8aca00-916c-11ea-894f-7cf81a04b67c.png">

Error in the console:

<img width="665" alt="Screen Shot 2020-05-08 at 8 37 13 PM" src="https://user-images.githubusercontent.com/1637288/81459119-3c287000-916c-11ea-94ea-b5ad494a5b40.png">

**Comment by ibrand** [comment]
@lperson I think this is fixed? Closing, but reopen if I'm wrong
