### ISSUE TITLE
Feature Request: Carrier Violation Error Automatically Replaces Phone Number 

### ISSUE THREAD

**Issue by Frydafly** [ProgressiveCoders/Spoke#1552]
**Problem**
Most campaigns I run have either had one or more carrier violations, due to a link being sent out or too many unforeseen texts sent in one day. I could definitely be better about buying more phone numbers, or preventing our texters from sending out links, but eventually I will manage around 60 organizations on Spoke and this will slip through the tracks.

**Solution**
A `30007 - Carrier Violation` Error on Twilio releases the phone number that caused the carrier violation and automatically purchases another phone number with the same area code.

**Context**
Perhaps this can be worked into the WIP Phone Number Management?

**Comment by ibrand** [comment]
@matteosb interesting comments here ^

**Comment by ben-pr-p** [comment]
Based on our experience, this would lead to a lot of unnecessary phone number churn and conversation interruptions. If you send a link and get a 30007, you can often (and often do want to) send another message to the same number from that same number without the link and it'll go through no problem

**Comment by matteosb** [comment]
I agree with @ben-pr-p's comment. It's usually the script's fault, so it would be useful to add some deliverability metrics to campaign stats and maybe some functionality to pause campaigns with high carrier violations. The upcoming phone number management feature should make it easy to add numbers to your messaging service if you are under-provisioned.

**Comment by schuyler1d** [comment]
Based on this feedback, can we close this issue and create (or connect) issues for:
* error code metrics at the campaign level
* error code metric reports at the org (and cross-org level)

**Comment by ibrand** [comment]
Connected it to a pre-existing issue around error codes and graphs for twilio error codes (#451) so I'll close this one. Thanks all! This is great context for that issue
