### ISSUE TITLE
Bug: Knex Timeout

### ISSUE THREAD

**Issue by kneupper** [ProgressiveCoders/Spoke#1565]
We are deploying spoke on Lambda with Spoke v5.5 and following the deployment doc "DEPLOYING_AWS_LAMBDA.md". We have run into an error with knex that we can't get past. We have already deployed with Claudia and unsuccessfully attempted to seed the database locally. We are using postgres 10.4 with AWS RDS.

**To Reproduce**
1. Fill in the .env file with the database configuration as specified here:
DB_HOST=spokeprod.xxxxxxxxxxxx.us-east-1.rds.amazonaws.com
DB_PORT=5432
DB_NAME=spoke_prod
DB_USER=spoke
DB_PASSWORD=[something secret]
DB_TYPE=pg
DB_USE_SSL=true
PGSSLMODE=require
2. Run yarn dev in the console

**Expected behavior**
Running locally should seed the database for our production deployment.

**Screenshots**
<img width="1718" alt="Screen Shot 2020-05-21 at 11 26 58 AM" src="https://user-images.githubusercontent.com/32854782/82581434-2f395280-9b56-11ea-9e60-7b30457b187b.png">

**Platform:**
 - MacOS Mojave 10.14.6
 - Spoke Version 5.5

**Additional context**
The Knex error as seen above is replicated identically when deploying to AWS Lambda with Claudia.

**Comment by allibail** [comment]
I'm part of the team working on this deployment and we have an update:
We think that this may be an issue with the database, not with knex itself. We followed the RDS instructions [here](https://github.com/MoveOnOrg/Spoke/blob/main/docs/DEPLOYING_AWS_LAMBDA.md). We looked at the documentation for Postgres with AWS and attempted to connect to the database with psql using the method described in [this article](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_GettingStarted.CreatingConnecting.PostgreSQL.html#CHAP_GettingStarted.Connecting.PostgreSQL). This is the command we used:
`psql --host=[DB endpoint] --port=5432 --username=spoke --password --dbname=spoke-prod`

We get this output:
```
psql: error: could not connect to server: could not connect to server: Operation timed out
Is the server running on host "[DB endpoint]" ([DB IP]) and accepting TCP/IP connections on port 5432?
```

We think this might have something to do with the timeout described above.

**Comment by hiemanshu** [comment]
The knex timeout error is an issue with knex not being able to connect to the database, either because of database settings, or knex not being configured correctly. I've seen these errors before when a newly created instance wasn't setup to accept remote connections.

**Comment by allibail** [comment]
Our database was configured incorrectly. One of our public subnets in our VPC was mistakenly associated with a private route table. Once we corrected that, it was fixed.

**Comment by ibrand** [comment]
Oh great to hear that!
