### ISSUE TITLE
Bug: Creating Multiple Organizations

### ISSUE THREAD

**Issue by jheyer159** [ProgressiveCoders/Spoke#1566]
**Describe the bug**
On my dev system I'm attempting to create another organization using the /graphiql endpoint with this mutation from `docs/GRAPHQL_DEBUG.md`

```gql
mutation {
  createInvite(invite: {is_valid: true}) {
    id
  }
}
```
And it's resulting in this error...
```json
{
  "data": {
    "createInvite": {
      "id": null
    }
  },
  "errors": [
    {
      "message": "Resolve function for \"Invite.id\" returned undefined",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "createInvite",
        "id"
      ]
    }
  ]
}
```

**To Reproduce**
1. npm run dev
2. go to http://localhost:3000/graphiql
3. paste the createInvite mutation in
4. hit run - see the error

**Expected behavior**
Expected that this mutation would run and return something like
```json
{
  "data": {
    "createInvite": {
      "id": "d9691319-1106-4c4d-9efc-7765029fc140"
    }
  }
}
```

**Platform (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Desktop or Mobile: Desktop
 - Version: 5.3

**Additional context**
My goal is to create multiple organizations.  I'm assuming the first step is to get a correct inviteId so it can be used in the next step which would be createOrganization.

Is it possible to do this through the GUI?  I've already setup my initial organization.

**Comment by ibrand** [comment]
@jheyer159 There are workarounds to creating multiple organizations.

1. You can set `SUPPRESS_SELF_INVITE` to 0 temporarily and then login (which will prompt you to create an org) and then set it back.
2. You can use the SQL documented in our README under [Getting the app running](https://github.com/MoveOnOrg/Spoke#getting-the-app-running) to create a new org from the commandline.

We're hoping to eventually have a UI for this but don't have one yet. Are you interested in taking that on? It's a bit chunky of a feature but would be great for lots of groups using Spoke in a multi-tenant context

**Comment by jheyer159** [comment]
Thanks for the response.  I don't have the bandwidth to take that on right now.
