### ISSUE TITLE
Feature Request: Snowflake mode

### ISSUE THREAD

**Issue by KidPluto** [ProgressiveCoders/Spoke#1580]
**Problem**
The main issue I have with textbanking is having to deal with replies which are vulgar, rude, or obscene.  I shouldn't need to have to deal with this just to send out informational texts.  

**Solution**
Spoke needs to provide the user with the ability to control what replies they are exposed to.  
There could be different levels of control:
Level 1: Spoke takes no action and the complete text of the reply is shown.
Level 2: Spoke replaces vulgar, rude or obscene words with "xxxxxx"
Level 3:  Spoke doesn't present replies which contain vulgar, rude or obscene words and they would treated as if the user had selected "done, please handle remaining replies".  Any of these replies could only be handled by users who have selected Level 1 or 2.
(Someone could come up with cute names for the different levels.)
There should also be a selection for tagging a reply which contains  vulgar, rude, or obscene words which Spoke didn't catch.  This would allow refinements to the solution. 

**Disclaimer** 
I understand that no solution would be perfect.  A perfect solution is not needed.

**Comment by ibrand** [comment]
Hey @KidPluto thank you for submitting this! Does the solution outlined in #359 feel like a good fix here? It doesn't provide the full set of options you list, but would hide all the profanity with "grawlix" (comic book swearing like $%&#!)

**Comment by Frydafly** [comment]
assuming that this issue was resolved, using a different method on here https://github.com/MoveOnOrg/Spoke/pull/938 , I'll be closing this. Thank you @KidPluto!
