### ISSUE TITLE
Deprecation: Remove the Opt-Outs Menu

### ISSUE THREAD

**Issue by ibrand** [ProgressiveCoders/Spoke#1591]
**Problem**
From conversations with admin, it seems like no one is actually using the opt outs menu. The only function of that menu is to print all of the opted out phone numbers to the screen which can be accomplished through querying the opt-out table. On top of that, there are regularly enough opt outs that they cause the app to freeze if you accidentally click the menu.

**Solution**
Remove the menu. It's not worth invested energy into scaling a menu that doesn't need to exist, and it's clutter right now.

**Context**
Tagging some admin for their consensus on removing this menu: @Frydafly @jeffm2001 @deasterdaywfp @ErikKirkstein 

Please comment or just 👍 reaction if you're cool to see this go!

**Comment by bdatkins** [comment]
I'd love to take this one if it's approved.

**Comment by deasterdaywfp** [comment]
Take it away!

*Dylan Easterday*
*National Volunteer & Distributed Organizing Manager - Working Families
Party*
WFP4theMany.org
*Text *(347) 460-9451 or Schedule https://calendly.com/deasterday
Email deasterday@workingfamilies.org
Sign up to volunteer here <http://www.wfp4themany.org>

**Comment by ibrand** [comment]
@bdatkins Assigning this to you since it looks like we can go ahead and remove it!

**Comment by ibrand** [comment]
This was completed in #1591
