### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#16]
- [ ] As an admin, I want to be able to create universal tags in case I want to save information about certain contacts
- [ ] As a texter, I want to be able to tag contacts with admin created tags if a contact responds 
- Example: 
Admin creates a tag for 'potential leaders' with a description. 
Texter receives a reply from a highly experienced volunteer and is able to tag that number with the 'potential leaders' tag

**Comment by joemcl** [comment]
hey @lperson we can now tag *convos* in Message Review - how can we then apply that tag to the contact record for the *person* we sent to that's in that convo? Like for example - Spanish writer/speaker. cc: @shakalee14 @deasterdaywfp @ibrand @suegibson . @bchrobot will look at the PR in your repo that you linked to.

**Comment by ibrand** [comment]
This was implemented in #1473 !
