### ISSUE TITLE
Feature Request: Add link to Google Docs script import doc in Campaign creation UI

### ISSUE THREAD

**Issue by joemcl** [ProgressiveCoders/Spoke#1606]
**Problem**
We have a doc about how to use Google Docs to import a script but the Campaign creation UI does not point to that

**Solution**
Add text linking to [this](https://github.com/MoveOnOrg/Spoke/blob/main/docs/HOWTO_IMPORT_GOOGLE_DOCS_SCRIPTS_TO_IMPORT.md)  next to "You can import interactions and canned responses from a properly formatted Google Doc." in Script Import in the Campaign creation UI.

**Context**

**Comment by ibrand** [comment]
I really like this. It would be awesome to see more in-app links to docs.

Note: Would love to see the link go out to a more public facing doc site if we implement #1605

**Comment by joemcl** [comment]
@ibrand yeah I think setting up either GitHub Pages and/or readthedocs.org pages could be pretty quick, and once those are there, use links to those for stuff like this in the UI

**Comment by SoryRawyer** [comment]
hey folks (specifically @ibrand (hello!)), I'm new to the project and would hope to take you all up on this "good first issue" label.

**Comment by ibrand** [comment]
Awesome @SoryRawyer and hi 😄 ! Do you feel like you have enough context on this? Anything I can clear up?

**Comment by SoryRawyer** [comment]
I think I have enough context on this to get started and test locally!
I do have one question: do either you or @joemcl have thoughts on the copy for the link text? I was thinking something like `Please refer to this document for more details` with either "this document" or the whole phrase for the link. What do you all think?

**Comment by joemcl** [comment]
Thanks @SoryRawyer ! I think the link just from "this document" would be better, so it's clearly a hyperlink. @ibrand I'm going to try to implement #1605 on the docs in my own fork and see how quick it is to publish using readthedocs.org , if it's quick and easy, seems worth going with that for the docs in the upstream MoveOn repo branch main. @SoryRawyer if that's the case and @ibrand wants to go with that/try it out, IMHO we would rather have that more average-user friendly link than direct to the doc in the repo.

**Comment by joemcl** [comment]
OK never mind re readthedocs.org - that's for use by an Organization on GitHub, not an individual. So the MoveOn organization could test that out, @ibrand .

**Comment by SoryRawyer** [comment]
That makes sense! I'll probably open a PR later today.
You didn't ask, so my apologies in advance for unsolicited advice, but I've found the repository wiki to be a kind of nice medium between GH pages and readthedocs. That might be a bit friendlier to navigate than the entire repository, and could be easier to set up than GH pages (though how much easier, I can't say).

**Comment by ibrand** [comment]
Yeah @joemcl I've been waiting on some approvals for a readthedocs.io test, so we can always update this later, and I think @SoryRawyer's solution is really easy to adjust

**Comment by joemcl** [comment]
@ibrand sounds good
