### ISSUE TITLE
Make the volunteer texting screen auto-refresh after completing a round of texting

### ISSUE THREAD

**Issue by mathemagica** [ProgressiveCoders/Spoke#162]
When volunteers get responses, they should see those responses in the text screen automatically, without needing to reload the page.

pollingInterval: 5000

**Comment by sandramchung** [comment]
Setting the pollInterval in TexterToDoList graphql query to 5000 makes the screen refresh quickly; but I'm concerned that lots of texters leaving this screen open means they're all hitting the database every five seconds. I think we should implement an event-based refresh instead - triggered when new assignments come in or when this texter sends or receives messages.

**Comment by sandramchung** [comment]
Branch 162-textertodo-autorefresh and https://github.com/MoveOnOrg/Spoke/pull/197

**Comment by sreynen** [comment]
Let's do both, do the fix we can do now, and then plan the better fix for later.
