### ISSUE TITLE
Feature Request: Query-preserving url addressability for MessageReview

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#1632]
**Problem**
A message review query must be manually selected each time. Reloading clears a query -- and the default query is not even 'cheap' on the backend.

**Solution**
Message Review is quite powerful, and would be even more so, if queries were addressable.  This would enable:
* Linking from the CampaignStats page directly to a message review for that particular campaign
* Linking from a texter directly to all their conversations
* An Admin bookmarking some important queries that they review regularly.

## Tech context:

* Queries are generated from these code points:
(linking to stage-main-71 branch -- at time of writing that is our release target)
The top component for message review is at:
https://github.com/MoveOnOrg/Spoke/blob/stage-main-71/src/containers/AdminIncomingMessageList.jsx

This is the component where filters are chosen and updated:
https://github.com/MoveOnOrg/Spoke/blob/stage-main-71/src/components/IncomingMessageFilter.jsx

The query is run from here:
https://github.com/MoveOnOrg/Spoke/blob/stage-main-71/src/components/IncomingMessageList/index.jsx#L326

We have a few similar url places in the code to copy from:
https://github.com/MoveOnOrg/Spoke/blob/stage-main-71/src/containers/AssignmentTexterContact.jsx#L369
https://github.com/MoveOnOrg/Spoke/blob/stage-main-71/src/components/AssignmentTexter/ContactController.jsx#L41

**Comment by inorvig** [comment]
I will take a look at this one!

**Comment by inorvig** [comment]
Looks like the stage-main-71 branch was merged, so the links don't work but I think I've found most of the places referenced and gotten a pretty good understanding of things. Definitely seems very doable to me :) @ibrand feel free to officially assign haha
