### ISSUE TITLE
When creating a campaign, in the interactions form, deleting answer options adds an empty "Start" step and breaks display

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#164]

**Comment by sreynen** [comment]
<img width="651" alt="screen shot 2017-09-05 at 9 41 02 am" src="https://user-images.githubusercontent.com/108645/30069615-740e6e98-921e-11e7-8096-865052ff4df3.png">

Screen shot example. Should never have 2 "Start" steps in a script.

**Comment by ibrand** [comment]
This seems to be fixed! I couldn't reproduce it. Closing this one.
