### ISSUE TITLE
Feature Request: Add ability to exclude search terms for Campaigns 

### ISSUE THREAD

**Issue by joemcl** [ProgressiveCoders/Spoke#1640]
**Problem**
In Campaigns, we can *include* search terms to find Campaigns, but can't *exclude* search terms

**Solution**
Add the ability to exclude search terms when filtering for Campaigns

**Context**
It would be handy to be able to see all Campaigns that don't include the character 'X' in the title, for example

**Comment by ibrand** [comment]
This was merged in 8.1!
