### ISSUE TITLE
Bug: Ctrl-X to send overrides 'Cut'

### ISSUE THREAD

**Issue by gradyat** [ProgressiveCoders/Spoke#1643]
**Describe the bug**
The new keyboard shortcut 'Ctrl-X' sends a message. Typical behavior is the 'cut' command, and this overrides that.

**To Reproduce**
1. Go to send a reply.
2. Select a response.
3. Highlight the part you want to combine with another response.
4. Ctrl-X to cut that part.
5. The message inadvertently sends before desired.

**Expected behavior**
Ctrl-X should 'cut' the selected text. This deletes it and adds it to the clipboard.

**Screenshots**
N/A

**Platform (please complete the following information):**
 - OS: Windows 10, version 2004
 - Browser: Chrome
 - Desktop
 - Version: 83.0.4103.106

**Additional context**
Can a different shortcut be made for send? (Yes, I know that copying with Ctrl-C is an option, but I don't see how it's a good idea to override an default OS-level shortcut, to cause accidental sends.)

**Comment by schuyler1d** [comment]
Unfortunately, most other keyboard letters were taken by browser actions.

I suppose we could switch to Ctrl-<Enter> which might not have the same accessibility issues as the <Enter> key alone, but that would need some cross-OS testing.
