### ISSUE TITLE
Non-editable script fields in interaction steps pop up edit modal

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#165]
When attempting to edit a campaign after it's already started, the description in the Interactions section reads: "This campaign has already started, so you won't be able to modify the survey questions. You can still modify the scripts, though." Question fields and answer options aren't editable, but an editing modal still pops up when you click on the Script field - however, attempting to change the content and save by clicking "Done" in the modal has no apparent effect on the script content.

<img width="1071" alt="spoke" src="https://user-images.githubusercontent.com/5560919/29796708-edff2004-8c0f-11e7-971f-da979edd4dfb.png">

Do we actually need to be able to edit Script fields after a campaign has started? If so, keep the Script edit modal and make it work. If not, disable the Script edit modal.

**Comment by sandramchung** [comment]
Check to see if saved scripts are editable even before campaign has started.

**Comment by sandramchung** [comment]
Also, answer options disappeared after starting campaign.
