### ISSUE TITLE
Bug: CSV Upload Fails when Using Lambda Deployment 

### ISSUE THREAD

**Issue by Jdesk** [ProgressiveCoders/Spoke#1653]
**Describe the bug**
When I create a campaign and attempt to upload a csv, I get the following:

I have checked rollbar and the error I am receiving is: #1 Error: Invalid country calling code

```
File https://spoke.triumphtech.io/bundle.b043493b2c5dbf0a77a9.js
line 62 col 566492 in [1]</i18n.phonenumbers.PhoneNumberUtil.prototype.parseHelper_
File https://spoke.triumphtech.io/bundle.b043493b2c5dbf0a77a9.js
line 62 col 565452 in [1]</i18n.phonenumbers.PhoneNumberUtil.prototype.parse
File https://spoke.triumphtech.io/bundle.b043493b2c5dbf0a77a9.js
line 43 col 235826 in t.getFormattedPhoneNumber
File https://spoke.triumphtech.io/bundle.b043493b2c5dbf0a77a9.js
line 67 col 502140 in p/t<
File https://spoke.triumphtech.io/bundle.b043493b2c5dbf0a77a9.js
line 23 col 47129 in p
File https://spoke.triumphtech.io/bundle.b043493b2c5dbf0a77a9.js
line 23 col 88429 in cs
File https://spoke.triumphtech.io/bundle.b043493b2c5dbf0a77a9.js
line 67 col 502061 in p
File https://spoke.triumphtech.io/bundle.b043493b2c5dbf0a77a9.js
line 67 col 503575 in complete
File https://spoke.triumphtech.io/bundle.b043493b2c5dbf0a77a9.js
line 73 col 1675 in t/this.parseChunk
File https://spoke.triumphtech.io/bundle.b043493b2c5dbf0a77a9.js
line 73 col 4196 in r/this._chunkLoaded
File https://spoke.triumphtech.io/bundle.b043493b2c5dbf0a77a9.js
line 73 col 13393 in p/<
```

**To Reproduce**
1. Go to 'spoke admin console'
2. Click on 'create new campaign'
3. Try to upload csv contact file

**Expected behavior**
CSV Contact file is uploaded successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/9715064/86170694-86352e80-bae9-11ea-9e14-0574d410f36d.png)

**Platform (please complete the following information):**
 - OS: ALL
 - Browser firefox/chrome
 - Desktop or Mobile? Desktop

**Additional context**

**Comment by ibrand** [comment]
Hey @Jdesk are you able to share the headers of your csv file to diagnose?

**Comment by allibail** [comment]
We had a similar issue. Do you set the PHONE_NUMBER_COUNTRY environment variable? If you don't set this variable, you have to include the country code with every phone number you use.

**Comment by Jdesk** [comment]
@allibail @ibrand - we were able to sort this out by adding the PHONE_NUMBER_COUNTRY variable to the configuration.  

I did not see mention of this in the docs anywhere - might be a good idea to add something explaining this parameter.
