### ISSUE TITLE
Clicking "next" on interaction steps section sometimes never finishes

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#166]
When creating a new campaign, clicking the "Next" button at the bottom of the interactions form should save the current interactions data, collapse the interactions form and expand the Canned Responses form. Currently, sometimes nothing appears to happen when you click "Next" -
 the section does not collapse, and subsequently clicking on another section then coming back to interactions or refreshing the entire campaign admin page may show the updated interactions content, may erase the updates to the interactions content, or may show only some of the interactions content.

**Comment by sandramchung** [comment]
Why is saving interaction steps a job?
