### ISSUE TITLE
Feature Request: <your-title-here>

### ISSUE THREAD

**Issue by LinuxSysAdmin** [ProgressiveCoders/Spoke#1687]
**Problem**
Is your feature request related to a problem? Please describe the problem with a clear and concise description. E.g. I'm always confused when[...]
we are looking for signalwire API work for Spoke
**Solution**
Describe the solution with a clear and concise description of what you want to happen.
If Spoke accept API request signalwire API we can use Spoke with signalwire
**Context**

NODE_ENV=development
SUPPRESS_SELF_INVITE=
JOBS_SAME_PROCESS=1
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_S3_BUCKET_NAME=
APOLLO_OPTICS_KEY=
DEV_APP_PORT=8090
OUTPUT_DIR=./build
ASSETS_DIR=./build/client/assets
ASSETS_MAP_FILE=assets.json
CAMPAIGN_ID='campaign-id-hash'
DB_HOST=127.0.0.1
DB_PORT=5432
DB_NAME=spokedev
DB_TYPE=
DB_MIN_POOL=2
DB_MAX_POOL=10
DB_USE_SSL=false
WEBPACK_HOST=localhost
WEBPACK_PORT=3000
AUTH0_DOMAIN=XXXX.auth0.com
AUTH0_CLIENT_ID=
AUTH0_CLIENT_SECRET=
BASE_URL=http://localhost:3000
SESSION_SECRET=set_this_in_production
DEFAULT_SERVICE=twilio
NEXMO_API_KEY=
NEXMO_API_SECRET=

SPOKE_API_KEY=
SPOKE_AUTH_TOKEN=

TWILIO_API_KEY=
TWILIO_APPLICATION_SID=
TWILIO_AUTH_TOKEN=
TWILIO_MESSAGE_SERVICE_SID=
TWILIO_STATUS_CALLBACK_URL=
TWILIO_SQS_QUEUE_URL=

PHONE_NUMBER_COUNTRY=US
ROLLBAR_CLIENT_TOKEN=
ROLLBAR_ACCESS_TOKEN=
ROLLBAR_ENDPOINT=https://api.rollbar.com/api/1/item/
ALLOW_SEND_ALL=false
EMAIL_HOST=
EMAIL_HOST_PASSWORD=
EMAIL_HOST_USER=
EMAIL_HOST_PORT=
EMAIL_FROM=
TWILIO_MESSAGE_VALIDITY_PERIOD=
DST_REFERENCE_TIMEZONE='America/New_York'
PASSPORT_STRATEGY=local

**Comment by ibrand** [comment]
@LinuxDevBD you've put the API creds for your account into this issue and I would recommend removing those for security reasons!

**Comment by LinuxSysAdmin** [comment]
removed thanks

**Comment by arena** [comment]
Nothing is ever gone once it's in a github issue... they are in the version hx
You gotta change those credentials on your end now. (sorry)
And please edit this issue that have a descriptive title.

**Comment by arena** [comment]
This issue seems like it should be deleted. ...looks like it was a request for support or freelance work? there is no description, no title, no context.

**Comment by ibrand** [comment]
Closing cause I think this issue was an accident!
