### ISSUE TITLE
RFC: Microsite for our Docs folder

### ISSUE THREAD

**Issue by ibrand** [ProgressiveCoders/Spoke#1701]
## Proposal
I'd like a friendlier documentation presence for non-tech people. I'm specifically interested in these criteria:
1. There should be as few as possible changes made to a dev workflow. If a dev is writing a doc for their feature, it should still be added to the docs folder and be written in markdown.
2. The site should be deployable through the docs folder on github pages (and therefore require no extra deploy steps)
3. The site should not break any deployments that are live

## Motivation
Our docs are challenging for admin and texters who use Spoke to navigate because they are on github and unindexed. I also have found them challenging to navigate even as a software-trained person because they're not sorted (past their naming conventions) and are in all caps. I want our docs to feel really approachable, usable, and collaborative.

## Detailed Design
I'd like us to implement this with the conventions from [docsify](https://docsify.js.org/) which will not involve installing any libraries, just adding some files. I will then attach github pages to render from the docs folder and we'll have a micro site! Part of the PR for this feature will be the proposed sidebar outline for the docs which I will circulate in the community and gather extra feedback for.

[Here's a quick look at how few files are needed for this](https://github.com/MoveOnOrg/Spoke/compare/docsify?expand=1)

The only change that devs will see is that they will need to add their doc to a reasonable place in the `_sidebar.md` file which renders the sidebar if they want it available publicly (which we should encourage!) I will include a doc on how to add docs that includes that.

As of right now, I'm not sure if we'll be able to render files above the doc/ folder (like the README, CONTRIBUTING or CODE_OF_CONDUCT) without copying the into the docs folder. I'll keep investigating that.

### Other options considered
I looked at [sphinx](https://www.sphinx-doc.org/en/master/) since it's output is compatible with readthedocs.io but it would require us having everyone download sphinx as a python package and running a make command everytime they change docs which seemed like a real drag.

I also looked at [docusaurus](https://docusaurus.io/) which is a lot heavier weight than what we need

#### Sponsor Organization (will test alphas/betas)
MoveOn

#### Developer allocated
@ibrand 

#### Planned timeline
Within 2 weeks

#### Files/File-sections touched
There might be minor changes to some of our docs.

**Comment by sharonsolomon** [comment]
@schuyler1d and @ibrand I want to check in on this issue before starting work on #1728 from @nke5ka.  In making the microsite are you redoing any of the ReadMe already?  Is it ok for us to be working on these two issues concurrently?

**Comment by ibrand** [comment]
@sharonsolomon you can totally work on that in tandem with this. Docsify actually makes it super easy to change things around as needed. Thank you for asking!

**Comment by ibrand** [comment]
Closing cause this happened in 8.1!
