### ISSUE TITLE
Bug: New "Texting Alias" value interferes with search for texters to assign

### ISSUE THREAD

**Issue by ZevH** [ProgressiveCoders/Spoke#1714]
**Describe the bug**
Spoke assigners typically receive a request from a texter in Slack (e.g. "John Smith") and then search for that same name in the Spoke text assigning panel. But if a "texting alias" has been set by the texter in Spoke, the a First+Last search will not find the texter. This make it appear, incorrectly, that the texter does not have a Spoke account and cannot be assigned texts.

This is especially problematic when the texter has a common first name (like "John"), and the assigner is habituated to add the last name when searching in order to narrow down the search results.

The text assigners search string should be matched against the Spoke First + Last name without the parenthesized alias.

**To Reproduce**
1. Create an account in Spoke with the fields "First name", "Last name", and "Texting Alias (optional)" all filled in, e.g. "John", "Smohn", and "Pat", respectively.
2. Select any campaign, click "Edit", then select the "Texters" panel.
3. In the "Search for texters to assign" field, type "John Smohn"
4. The texter will not be located.
5. Now in the "Search for texters to assign" field, type "John (P"
6. The texter will be located.

**Expected behavior**
The text entered in the "Search for texters to assign" field should be matched only against the "First name" and "Last name" fields of Spoke accounts. The Texting Alias field value should be used only for display (in the search results and in the list of texters who have been assigned) and for inserting into text messages. It should not be searched on in the "Assign Text" panel.

(It should, however, be searchable in the "People" page of Spoke, along with First name, Last name, and Email. Currently it isn't.)

**Screenshots**
I created a Spoke account with the following profile values:
  First name: John
  Last name: Smith
  Texting alias: Pat
  I then tried searching on "John Smith" and "John (P". The screen shots below show the results of those two searches. Only the latter gives a result, although it is the former that should give the result.

<img width="351" alt="Screen Shot 2020-08-02 at 9 24 34 PM" src="https://user-images.githubusercontent.com/43025028/89146240-ffb8a600-d507-11ea-8075-00756d3d60eb.png">
<img width="344" alt="Screen Shot 2020-08-02 at 9 24 50 PM" src="https://user-images.githubusercontent.com/43025028/89146246-03e4c380-d508-11ea-9828-cae8c28b7506.png">

**Platform (please complete the following information):**
 - OS: MacOS 10.13.6
 - Browser: Firefox
 - Desktop or Mobile? Desktop
This bug appears to occur on all platforms and in all browsers.

**Additional context**
Is this really a bug or is this a feature change request? All of the text assigners on the MoveOn Text Team find the current functionality confusing and a hindrance, so I'm considering it a bug.

**Comment by ibrand** [comment]
Thanks for filing @ZevH ! To answer:
> Is this really a bug or is this a feature change request? All of the text assigners on the MoveOn Text Team find the current functionality confusing and a hindrance, so I'm considering it a bug.

I'd call this a bug. It should totally work to search by first and last name and it would be nice if it still rendered the full name (with the alias included)

**Comment by bdatkins** [comment]
@ibrand I'd like to take this one

**Comment by ZevH** [comment]
Working great! Thanks!
