### ISSUE TITLE
Bug: NGP VAN contact loader does not show selectable lists

### ISSUE THREAD

**Issue by pmbruce** [ProgressiveCoders/Spoke#1732]
**Describe the bug**
I attempt to enable the NGP VAN content loader, and am able to select NGP VAN as the load method. When I type in list names, none show up. I have the Hustle API key and app name as config vars, I'm not sure what the issue is.

**To Reproduce**
I deployed using heroku, added NGP_VAN_API_KEY, NGP_VAN_APP_NAME, and NGP_VAN_WEBHOOK_BASE_URL and variables. I have a Hustle API key and App Name

**Expected behavior**
The contacts should be loaded via the content loader.

**Screenshots**

![Screen Shot 2020-08-07 at 3 33 14 PM](https://user-images.githubusercontent.com/64431232/89681772-98ae3f00-d8c3-11ea-9f51-b9df8b7be3eb.png)

**Platform (please complete the following information):**
 - iOS: iOS Catalina 10.15.4
 - Browser: Chrome
 - Desktop
 - Version 5.5

**Comment by ibrand** [comment]
@lperson is there anything particular here that stands out as a user error?

**Comment by lperson** [comment]
The lists need to be saved to a folder to which the API user has permission as shown below. I got to this screen via

`home / folders / edit folder`

<img width="528" alt="Screen Shot 2020-08-13 at 2 28 04 PM" src="https://user-images.githubusercontent.com/1637288/90173152-03eb8b80-dd72-11ea-9512-77b5728db093.png">
