### ISSUE TITLE
Figure out what to do with rollbar

### ISSUE THREAD

**Issue by sandramchung** [ProgressiveCoders/Spoke#174]
There are a bunch of failed requests going to a rollbar account that's not set up. We should figure out what to do with it - take it out, implement it, or make it optional.

**Comment by shakalee14** [comment]
I think making it optional makes sense. I think Rollbar just provides a nice log interface and stack trace but I believe we already use cloudwatch on our lambda instance for this type of logging.

**Comment by sreynen** [comment]
I think the thing to change here is making the code at https://github.com/MoveOnOrg/Spoke/blob/master/src/server/middleware/render-index.js#L30 not get added if `process.env.ROLLBAR_CLIENT_TOKEN` is empty
