### ISSUE TITLE
Feature Request: adjust styling of forward aarow

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1740]
Style disabled forward (or back) arrow so that it is faded from its enabled (white) style instead of faded dark gray. 

This is a minor adjustment.. it would be a major project to set up my development environment. So, here is the minor change I would do if I could do it.

![styling](https://user-images.githubusercontent.com/411070/89933381-d19c2b80-dbc3-11ea-8316-8351b081d435.png)

**Comment by arena** [comment]
@ibrand this issues is the one we worked on the other day

**Comment by arena** [comment]
@ibrand ...sorry, this one is slightly different, but  I don't think I added one for alignment

**Comment by nkartha2** [comment]
I can work on this request!

**Comment by nkartha2** [comment]
I haven't forgot about this. I should be able to get to it this weekend - sep 19/20th! sorry for the delay

**Comment by schuyler1d** [comment]
Hm, so the problem with this is that the disabledColor is also the unfocused text-field placeholder text and that field bg is white, and so making this disabledColor faded white makes the placeholder (field name) invisible.

**Comment by nkartha2** [comment]
@schuyler1d I think this is ready for re-review. Fixed tests and made sure that the placeholder text is still visible.

**Comment by Arique1104** [comment]
Hey @nkartha2 or @schuyler1d 

What is the pull request that is attached to this issue?  If it's been merged we might be able to close this issue.

**Comment by schuyler1d** [comment]
https://github.com/MoveOnOrg/Spoke/pull/1849
