### ISSUE TITLE
Feature Request: Left justify text in outgoing message bubble

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1772]
**Problem**
Text is still right justified (a remnant from the old design that slipped into the redesign). It's difficult to read.

**Solution**
Left justify it so it will be easier to read.

**Comment by arena** [comment]
@ibrand can I assign this to you?

**Comment by ibrand** [comment]
This PR: #1743 should fix this right? It's included in the new 8.1 release going out soon!

**Comment by arena** [comment]
sorry for the redundancy, closing
