### ISSUE TITLE
Feature Request: Capturing and responding to multiple question answers at once

### ISSUE THREAD

**Issue by ryanjcrump** [ProgressiveCoders/Spoke#1781]
**Problem**
When a contact responds to a current question, and next question, the texter flow is cumbersome in the following ways:
1. The All Questions button, which opens All Questions, does not appear until a Survey Response to the first questions is selected.
2. After clicking on All Questions, it is not clear that the next question field is a selectable drop down box.

**Solution**
1. Let's make the "All Questions" button/label visible and clickable before a Survey Question is selected.
2. Let's make the dropdown field for each unanswered Question clearer (see attachments for quick mockup)

**Context**
the flow is cumbersome for texters in the following situation:

Initial Message: Will you vote for our candidate?
Voter Replies: Yes, I will vote for them and also I want to volunteer.

Since the voter answered the current question **and also the next question** (will you volunteer?), Texter needs to choose the **Yes** survey response, then click on All Responses again, then click on "All Questions", then click on second question "**_Volunteer?_**" , then select the Survey Response **Vol Yes**, then click out of the drop down, then click Send. 

(I updated this request after noticing that Past Questions has been changed to All Questions in 8.0! thanks to those who worked on that!)

Current UI:
![all questions 1](https://user-images.githubusercontent.com/70231636/91353002-7eb79c00-e79f-11ea-9b60-7e58f80e6139.png)

Proposed Mock up:
![all questions 2](https://user-images.githubusercontent.com/70231636/91353046-8e36e500-e79f-11ea-824c-163c8229a9cd.png)

**Comment by arena** [comment]
Good point that this part of the UI can present some friction in some circumstances. However what you've mocked up above, if I'm interpreting it right (hard to know without a prototype or a full screenshot even) would add a lot of complexity to an already confusing part of the ui... your solution might work ok for short surveys, but what about really long, multi question surveys? I think it would be worth exploring a more compact way to meet the user need of clearly marking survey responses all at once, but surfacing each question is a little problematic.

**Comment by ryanjcrump** [comment]
Thanks for this feedback! I don't think I understand your last sentence, or more specifically what you mean by "surfacing" but I think I was unclear; I don't want to reveal all questions at once in the way that I think you mean.

Currently, these "future" or "next" questions can be revealed by clicking Past Questions. As it stands, each "next" question is revealed after a selection is chosen for the one before. I think that's good! So I'm not suggesting that ALL questions should show at all times. 

The changes that I'm proposing would make it an **option** to reveal the current question dropdown view ("Past Questions") after the first voter reply is received. Currently, texters have the option to reveal the current question only after the first current question response is selected. 

The other change is simply to make the dropdown selection clearer for the user, as many folks have told us that they didn't realize they could click on the 2nd survey question in the view of photo 1 attached above.

I hope this provides some clarity or at least some background to clarify your concerns, Arena!

**Comment by ryanjcrump** [comment]
I updated this request after noticing that Past Questions has been changed to All Questions in 8.0! thanks to those who worked on that!

Thanks for the feedback here, Arena. 

I'm also realizing where I wasn't clear. For Solution #1, I'm not asking for the mock-up screen shot to be visible as is when the texter first clicks on the All Responses dropdown; I'm only asking that the All Questions button/label be visible at that point, so that a texter could click on it first to reveal the dropdown for the first question. Then dropdowns for subsequent questions will appear one at a time, just as this function works now. I hope that clarifies!

**Comment by Frydafly** [comment]
Woo! @ryanjcrump Checking whether this issue can be closed?

**Comment by ryanjcrump** [comment]
@Frydafly I don't think that the latest version has a solution to the problems that I've outlined here, which is that the UI of logging consecutive survey responses after the first contact reply takes a lot of clicks, is inconsistent (All Questions only shows up after the first responses is selected), and is unclear (many new texters often do not realize that the dropdowns within each question under All Questions are in fact dropdowns)

**Comment by arena** [comment]
Perhaps we should move the survey answers out of the all responses dialog all together and create a dedicated card on the sidebar that can expand to show the entire survey tree? 

We could also link to show the contents of that card as a dialog on mobile via the "Q: + current question" prompt above the responses.

**Comment by arena** [comment]
(I mean we should move the survey answers to their own card ... Can't edit my comment on the GitHub mobile app)

**Comment by Frydafly** [comment]
@arena that sounds promising! 
what do you think @ryanjcrump ?

**Comment by ryanjcrump** [comment]
closing this, as I think it's basically solved :)
