### ISSUE TITLE
Feature Request: Close All Responses dropdown on Survey Response selection

### ISSUE THREAD

**Issue by ryanjcrump** [ProgressiveCoders/Spoke#1782]
**Problem**
When selecting a survey response to the current question, texter needs to "Click out" of the dropdown in order to see the scripted response and send. 

**Solution**
Let's close the All Responses dropdown as soon as a Survey Response to the current question is selected.

**Comment by arena** [comment]
oh interesting -- it behaves that way (the way you suggest it should, that it closes automatically) with the "other responses" just not the survey responses. good catch!

**Comment by ryanjcrump** [comment]
I'm seeing that this is fixed in 8.0!
