### ISSUE TITLE
Redesign texter view so replies are visible

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#179]
![pasted image at 2017_09_05 11_57 am](https://user-images.githubusercontent.com/108645/30070695-888fecea-9221-11e7-94da-29888295e4af.png)

**Comment by sreynen** [comment]
Note: this task is only coming up with new look, not implementation.

**Comment by sandramchung** [comment]
Note: I have to go down to 320 x 480 screen size to replicate this view in chrome devtools emulator

**Comment by sandramchung** [comment]
Also reproduces on my phone, a Moto g4 play with 720 x 1280 screen resolution. 
![screenshot_20170906-134710](https://user-images.githubusercontent.com/5560919/30131711-02e760d8-930b-11e7-8949-0cb31aa950ce.png)

**Comment by sandramchung** [comment]
Quick mock:
[texter_replies_mobile2.pdf](https://github.com/MoveOnOrg/Spoke/files/1286125/texter_replies_mobile2.pdf)
