### ISSUE TITLE
TLV value using HTTP api and SMPP api 

### ISSUE THREAD

**Issue by AnythingLinux** [ProgressiveCoders/Spoke#1792]
it is possible to add two TLV value in HTTP api and SMPP api into Spoke

**Comment by ibrand** [comment]
Hey @UbuntuEvangelist do you mind providing a little more context and clarity with this request?

**Comment by AnythingLinux** [comment]
can you help me to add two TLV value in HTTP api & SMPP in Spoke because in INDIA all vendors now want custom TLV for each SMS so Spoke is suitable for that or should i move to kannel or Jasmin sms gateway?

**Comment by AnythingLinux** [comment]
I wants to setup two TLV values in API & SMPP spoke

**Comment by maxkc** [comment]
@UbuntuEvangelist I understand what you're trying to do but what's the specific need/use case to add TLV values for Spoke SMS?

**Comment by AnythingLinux** [comment]
I wants to do TLV fields are as follows:

Principal entityId TLV: 0x1400 (Hex), string, len = 30 : this is client's identifier on DLT
platform, a unique identifier belonging to each client.

ContentId TLV: 0x1401 (Hex), string, len = 30 : this data corresponds to the content
Template ID received when template is registered on DLT platform.

**Comment by maxkc** [comment]
Ah, got it.  Is this for TRAI regulation compliance?

**Comment by AnythingLinux** [comment]
@maxkc yes new DLT rules from 1st September. They need these two parameters as well in all API calls & SMPP Calls.

**Comment by maxkc** [comment]
@UbuntuEvangelist hmmm well, I guess you could add it... but it would be very challenging.  The majority of Spoke users are on Twilio, which doesn't support most of the [new guidelines](https://www.twilio.com/guidelines/in/sms).  [Nexmo supports DLT](https://help.nexmo.com/hc/en-us/articles/204017423-India-SMS-Features-Restrictions) but none of required fields required for this exist are in Spoke right now. 

I'm unfortunately not familiar with any open source solution that supports TRAI's DLT requirement.  If you were looking to make one I _think_ there are probably easier places to start than Spoke but not sure.

**Comment by AnythingLinux** [comment]
For this issue I have used feature request to suggest an idea for Spoke how ever I am closing this. Spoke does not brings good luck 2 tomes for me!
