### ISSUE TITLE
Feature Request: Add a Conversation View UI to Message Review

### ISSUE THREAD

**Issue by ryanjcrump** [ProgressiveCoders/Spoke#1794]
**Problem**
The current UI in Message Review is a list view with check boxes, which is useful to see batches of messages filtered by different variables. It is not as useful in viewing individual messages one at a time, since it requires clicking a link to preview and then clicking a link to open the conversation, then tabbing back out, closing the preview, and finding the next message in the list.

**Solution**
Let's add a UI on the admin side of Message Review that allows admins to arrow-through conversations in a similar way that texters do with their assigned conversations. Perhaps this view could have a toggle on/off so that we do not lose the list view altogether and so that the filtering options at the top of the page are still in tact whether in list view or conversation view. 

**Context**

**Comment by codygordon** [comment]
Some additional specifications (authored by @deasterdaywfp / @ryanjcrump).

Currently, the WFP Guide / Sweeping process relies on a couple tools to be used by volunteer leaders simultaneously including Spoke and Airtable forms or grid views to track sweeping results. 

**We would like to merge this process to all take place in Spoke, where sweeping would take place in a user mode (like Texter Mode)**. See:

![Spoke and Volunteer Data Development _ Automation](https://user-images.githubusercontent.com/13374656/93363195-c0b28b80-f7fb-11ea-9ff2-268a2d61204d.png)

Currently, our Guides are working to review both for issues or errors but **also signs of mastery within a sample of 20-30 conversations and identify trends and ways to guide any texter than needs extra support**. 

### Current "Sweep Flow"

1. Claim texter ready to be swept by adding your name to the “Guide [#channel]” view in the Texter Tracking Table in Airtable
2. Open Sweeping Form, fill in your name, texter’s email, and campaign
3. Find the campaign and texter in Message Review. Select 20-30 responses (or ~1/3, whichever is higher) to review, including some of each:
    1. Active Conversations
    1. Close Conversations
    1. Needs Texter Response w/ previous messages sent by texter
    1. Opted-Out (“All”)
8. Messages with Errors: Note # of errors on sweep form and all errors and describe issues with quotations from the message in note to texters
9. Copy/paste these notes into a DM with the texter in Slack
10. Track # reviewed and # errored in form
11. Note Level Up Skills in Sweep Form
12. Correct all errors for data accuracy
13. Reassign all reviewed messages to the Operator
14. Submit form with the following status:
    1. Continue Reviewing = Default
    1. Needs to Confirm Feedback = there are issues to be addressed!
    1. DO NOT ASSIGN = bad actor, sending misleading information, cursing, or escalating with non supporters, (escalate to staff when marking this)
18. After submitting the form, Update the “Currently Texting” view in the Operator Table in Airtable to mark the Texter as swept in the current campaign
19. Use your judgement from the first sweep to determine if that texter should also be marked as swept in one or more other campaigns; 
    1. if they had none or only one error, find their messages in other campaigns and reassign all to the Operator. mark them as swept in those other campaigns as well. 
    1. If they had multiple errors, sweep another campaign of theirs to correct those errors.  

## What we hope for is a seamless UI that would simplify this process

1. Select a texter to review from a dropdown or text search
2. Have that select pre-filter responses to the criteria of message types that we review (see the Basic Guide at the top of this page),
3. Then allow the Guide to then “step through” each conversation much like they would see as a texter moving from conversation to conversation, but the difference here being that the Guide would also have the ability to mark that conversation for the texter to review and add notes that “attach” to that conversation. 
4. That is then sent back to the texter to show up on their assignment screen under a new button type like “Review”. 
5. This would also then require that the texter step through each of those conversations marked for review, and make corrections or read the Guide feedback and mark a checkbox or similar button to confirm resolution. 
6. After all have been “resolved” then the texter should be allowed to click again to resume either new texts or their typical response queue.

**Comment by inorvig** [comment]
I believe this request sort of branched off of #1761 so just noting that as a reference/feature with some WIP

**Comment by ryanjcrump** [comment]
The new guide view feature satisfies this issue for me! Thanks @inorvig and @codygordon for leadership and development on this!
