### ISSUE TITLE
Feature Request: Allow for marking text messages as done

### ISSUE THREAD

**Issue by yuanstanley** [ProgressiveCoders/Spoke#1809]
**Problem**
Oftentimes, texters will conclude a conversation and someone will respond back with a thumbs up or another message that doesn't require a response. However, these will still be listed as `Respond`. It's a little inconvenient for texters, but is particularly problematic when using dynamic assignment, as texters will no longer be able to assign themselves new texts.

![image](https://user-images.githubusercontent.com/6366221/92292812-ed010a80-eed3-11ea-8c10-c5480ba1b04f.png)

**Solution**
Create an ability to mark text messages as completed / done / finished / archive.

**Context**
We're currently on Spoke 8.0 under LeftApps - I checked the release notes for 9.0 and don't think I saw anything addressing this specific issue, but of course let me know if the behavior is different already or there are other suggested workarounds!

**Comment by ibrand** [comment]
Hey @yuanstanley thanks for this! As a short term workaround, many texters use the "skip" button to get those conversations into "past messages"

**Comment by yuanstanley** [comment]
@ibrand awesome! Didn't realize that the `skip` button was there, thanks!!

**Comment by Frydafly** [comment]
Hey @yuanstanley! Checking in whether the skip button helped with this issue?

**Comment by yuanstanley** [comment]
Hi @Frydafly ! The skip button was usable for our end goal, although I think it was a little bit confusing for our users!

**Comment by Frydafly** [comment]
I think that @arena 's feature request https://github.com/MoveOnOrg/Spoke/issues/1778 might work towards resolving this issue, by implementing more of an inbox style display where conversations might be archived rather than just skipped.

**Comment by arena** [comment]
It would be great to get rid of "Skip" and replace it with a way to bookmark conversation and a way to toggle if a reply is read or not. ...but marking as "done" feels a little confusing because conversations are never really done. 

Here is the bookmarks issue: https://github.com/MoveOnOrg/Spoke/issues/1264

**Comment by mau11** [comment]
We are reviewing outstanding issues. Closing as this issue is being addressed in the commented links (#1778 and #1264)
