### ISSUE TITLE
Texts should send on hitting enter/return on keyboard

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#181]
Apparently this didn't work:
https://github.com/MoveOnOrg/Spoke/pull/156

**Comment by sandramchung** [comment]
Part 1: make text send on enter
part 2: prevent text from sending a zillion times if you hit enter a zillion tmies

**Comment by sandramchung** [comment]
Resolved by https://github.com/MoveOnOrg/Spoke/pull/209
