### ISSUE TITLE
Feature Request: character limit on response field

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1819]
**Problem**
Texters are able to paste or type in a response of any length (including several pages articles). Not usually an issue but it's possible to think you are pasting a single sentence and you've actually selected an entire essay (especially on mobile). 

**Solution**
Incremental features with increasing complexity.
a. 500 character limit, no messaging just truncate or don't let the texter type any more
b. display the character count and warn the texter when they get close and then extra warn them when they hit the limit (see twitter compose for inspiration)
c. let admins adjust the character limit for their org or instance of Spoke

**Comment by schuyler1d** [comment]
This is already possible with MAX_MESSAGE_LENGTH (see https://github.com/MoveOnOrg/Spoke/blob/main/docs/REFERENCE-environment_variables.md)
