### ISSUE TITLE
Ability for texters to revisit completed text conversations

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#182]
Currently after hitting send, no way to go back when:
* the user 'opt-ed' out.  Use-case: 1. opt-out was a mistake, Use-case: want to refer back to it.
* If they hit 'skip' by mistake or changed their minds.
* If they want to 'complete' a reply with another message (in exceptional cases)?

**Comment by sreynen** [comment]
Currently on any campaign a texter is assigned to, they can go through contacts in two lists: text (for people who have not yet been contacted at all) and reply (for people who have replied, and need a response to their latest reply). I think the simplest thing to do here is add a third list for all assigned contacts who do not show up in one of the other two lists: review, for conversations that are apparently complete, but the texter may want to review. Here's what this might look like:

<img width="617" alt="screen shot 2017-09-15 at 11 58 44 am" src="https://user-images.githubusercontent.com/108645/30496859-f65b9b68-9a0d-11e7-8f17-d50e42d3c88f.png">

Clicking on that would then show the same interface used in the other two lists, with one contact at a time displayed, and the ability to page through them. That interface is designed for completing a list of contacts, not finding a specific contact, so it's not great for this use case. But I think it's usable, so rather than try to predict what changes might work best for review, I suggest we implement the existing text interface first and make changes based on feedback from actual use.

**Comment by schuyler1d** [comment]
That sounds reasonable, though in the "Review texts" list I think we'd want two UX differences:
1. if the target is marked opt-out, then it should NOT skip that texter (right now it does), and probably (instead or even in the default view) -- mark the opt-out visually, to make sure to especially discourage additional follow-ups with them. -- and maybe a way to 'unmark' the opt-out (one use-case was that it was a mistake)
2. Consider adding an additional step before being able to text people on this list.

**Comment by sandramchung** [comment]
++ on both 1 & 2. Additionally, on the texter dashboard/todo list pictured above, consider swapping out the red or green numbered notification bubble for a less active-looking color, like dark grey text on light grey bubble. The bright color implies that the texter needs to take action, which may not be the case for many or all of the "Review Texts" conversations.

**Comment by sreynen** [comment]
https://github.com/MoveOnOrg/Spoke/tree/182-review-interface has some initial work here, but pausing this for now to focus on other things.

**Comment by ErikKirkstein** [comment]
Hi team,

Great work on this.

As far as what messages show up in the 'revisit conversations' list, the ideal would be the following:

A normal conversation flow goes like this:

initial sms message>recipient reply>texter reply

In the 'revisit conversations' list, we would want to include any sms message thread that is not an opt out.

Example of what to include:

Texter: Hi (member), it's (texter) with MoveOn. Can you attend the DC event?

Member: Yes, I will be there!

Texter: Great, here's the info.


Example of what not to include:

Texter: Hi (member), it's (texter) with MoveOn. Can you attend the DC event?

Member: Unsubscribe me, please

Texter: "Sends opt out message:
