### ISSUE TITLE
Bug: Relying on PHONE_NUMBER_COUNTRY default breaks CSV uploads

### ISSUE THREAD

**Issue by mayefsky** [ProgressiveCoders/Spoke#1824]
**Describe the bug**
If you haven't set PHONE_NUMBER_COUNTRY your CSV uploads will not assume US numbers. https://moveonorg.github.io/Spoke/#/REFERENCE-environment_variables currently suggests US should work as a default.

**To Reproduce**
1. Don't set PHONE_NUMBER_COUNTRY
2. Upload a valid CSV with US numbers
3. Get a "upload at least one number" error

**Expected behavior**
Either the csv processing should honor the US default if not set in the environment, or the environment variable reference should say that it's a required variable, and various deploy .env templates should include it.

This was also the culprit in https://github.com/MoveOnOrg/Spoke/issues/1653

**Comment by mayefsky** [comment]
Edit: .env.example does, it's just the lambda-env that doesn't

**Comment by maxkc** [comment]
Linking to [#1754](https://github.com/MoveOnOrg/Spoke/issues/1754) too because (I think?) the proposed workflow from @bobbyoderek may break that PR workaround.

Seems like there's some work that could be done around country assignment if anyone wants some help tackling it!

**Comment by Frydafly** [comment]
Checking in -- does PR https://github.com/MoveOnOrg/Spoke/pull/1883 resolve this issue?

**Comment by maxkc** [comment]
Yes, #1883 should fix this 🎉

**Comment by Frydafly** [comment]
Woohoo! Closing this.
