### ISSUE TITLE
Bug: Source file empty 

### ISSUE THREAD

**Issue by Michael-Labriola** [ProgressiveCoders/Spoke#1846]
Spoke/src/workers/job-handler.js is empty.  Is this file no longer needed to run Spoke?

**Comment by BryceStevenWilley** [comment]
For context, it was removed in https://github.com/MoveOnOrg/Spoke/commit/f0da498d0f271c776a4cf10f0ef6a0ca2d2f242e#diff-16bc0f440d8618de1963ad5dd8d46906.

**Comment by BryceStevenWilley** [comment]
For context, it was removed in https://github.com/MoveOnOrg/Spoke/commit/f0da498d0f271c776a4cf10f0ef6a0ca2d2f242e#diff-16bc0f440d8618de1963ad5dd8d46906.

**Comment by Michael-Labriola** [comment]
If was deleted on purpose, should it be invoked here: Spoke/deploy/spoke-pm2.config.js.template ?
