### ISSUE TITLE
Bug: Heroku Quick Start doesn't work due to missing repo tag

### ISSUE THREAD

**Issue by BryceStevenWilley** [ProgressiveCoders/Spoke#1847]
**Describe the bug**
A `v9.2` tag is needed for the Heroku one-button deployment to work. 

**To Reproduce**
1. Click on the "Deploy to Heroku" button on the README, which provides the `v9.2` tag as the repo for Heroku to use.
2. The Heroku page it brings you to will give an error: 
"""
No app.json located in the repo URL provided.

Make sure that an app.json file exists in the project root directory.
"""

**Expected behavior**
Heroku can correctly deploy an instance of Spoke. 
For a workaround, you can click on the button, and on the Heroku page, go to the end of the URL and change the `v9.2` to `master` for now. 

**Screenshots**

![Screenshot from 2020-09-20 15-50-37](https://user-images.githubusercontent.com/6252212/93720798-4a928980-fb59-11ea-91c3-9a4fb03ecdc0.png)

**Platform (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Desktop
 - Version: 9.2

**Comment by ibrand** [comment]
Thanks for noticing this @BryceStevenWilley , this is now fixed. I appreciate you pointing it out!
