### ISSUE TITLE
Heroku One Click Empty Page

### ISSUE THREAD

**Issue by moirahuang** [ProgressiveCoders/Spoke#1868]
**Describe the bug**
Sorry if I'm missing something really obvious here, this is my first time using Heroku. After I've deployed the app, I only get a completely white screen. 

**To Reproduce**
1) I clicked on the purple Deploy To Heroku button on the README and also opened up the [follow up instructions](https://github.com/MoveOnOrg/Spoke/blob/main/docs/HOWTO_HEROKU_DEPLOY.md) linked under the purple button. 
2) I followed the [environment variables documentation](https://github.com/MoveOnOrg/Spoke/blob/main/docs/REFERENCE-environment_variables.md) and set up a Twilio and Auth0 account, entered the keys, and all the other fields
3) I then clicked deploy at the bottom of the Heroku site. 
4) But when I click to open the app after it's been built, it just results in a completely white screen. 
5) I've also followed the instructions [here](https://moveonorg.github.io/Spoke/#/HOWTO_HEROKU_DEPLOY?id=setting-up-for-production-scale-database-etc) and removed and then added Heroku Postgres, but the same thing still happens. 

**Expected behavior**
I'd expect to see the console upon deploying the app

**Screenshots**
![image](https://user-images.githubusercontent.com/7342246/95417256-6f248a80-08e9-11eb-8b83-eff63f33f5d7.png)
Attached are the console error messages. 

**Platform (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Desktop or Mobile? Desktop
 - Version v9.2

**Additional context**
I'm able to build the console successfully locally and have tried to migrate through the Heroku CLI.

**Comment by mau11** [comment]
Hi @moirahuang, we are reviewing outstanding issues. We have since released Spoke v14. Please open a new issue if this issue still persists.
