### ISSUE TITLE
Password reset/change with Auth0

### ISSUE THREAD

**Issue by jeffm2001** [ProgressiveCoders/Spoke#1870]
**Describe the bug**
The password reset button on the Users list, and change password button on the user edit screen are intended to work for local auth. If you are using the Auth0 passport strategy, they do bad things:

- The change password dialog gives "GraphQL error: undefined" which is confusing for users.
- The Reset Password button is worse. If an admin clicks the button, the user's Auth0 token is replaced in the database with a reset hash, and they will NEVER be able to log in with that account again. If the user does manage to log in with Auth0 (presumably by using A0's password reset) it will create a duplicate account in the Spoke db (same email, name, etc, new user id).

I see that @lperson worked on #1155, but it appears it was closed without merging. Probably a good place to start for working on this issue!

**Comment by Frydafly** [comment]
@Nladhani -- tagging you in since I know this has been an issue at NYCET!

**Comment by Frydafly** [comment]
Thanks @jeffm2001 ! This has happened to me too and it's really annoying. Would love to see some progress on this!

**Comment by dj** [comment]
@lperson @schuyler1d is there a reason this PR wasn't merged? Just spend the last week trying to figure out why this was happening to our users.

**Comment by dj** [comment]
Actually, now that I think about it, we can just ask users to use the Auth0 password reset page.

**Comment by schuyler1d** [comment]
My guess is that Auth0 has changed their API 3 times so maybe it used to work, but now it doesn't. We either need to update the API or disable the button.

**Comment by percworld** [comment]
Is this password reset issue something that can be temporarily avoided by disabling the button only if AUTH0_CLIENT_ID != null?

**Comment by crayolakat** [comment]
This fix for this was merged into the `main` branch for the 12.2 release, but some rebasing caused the issue to not close automatically. Manually closing this issue.

**Comment by crayolakat** [comment]
Confirmed that a regression has happened. When an admin clicks "Reset Password," it says "The user has been sent an Auth0 password reset link!" but that actually doesn't happen. Instead the issue that Jeff originally described happens:

> the user's Auth0 token is replaced in the database with a reset hash, and they will NEVER be able to log in with that account again. If the user does manage to log in with Auth0 (presumably by using A0's password reset) it will create a duplicate account in the Spoke db (same email, name, etc, new user id).
