### ISSUE TITLE
Feature Request: View all todos across orgs

### ISSUE THREAD

**Issue by ibrand** [ProgressiveCoders/Spoke#1871]
**Problem**
There are many scenarios where texters are working on 1 Spoke instance but in multiple orgs and then it gets easy for a texter to miss one of their responses.

**Solution**
Create a Texter Todo screen view where a texter sees all assignments across orgs. Start with showing this view when the visiting the todo screen with the query param `?org=all` and as a follow up create a button for exposing it.

**Comment by Frydafly** [comment]
This is great! Any progress on this @ibrand ?

**Comment by arena** [comment]
I've never experienced this as a texter. How would a mere-mortal texter end up with multiple orgs on the same spoke account? I have multiple spoke accounts for multiple orgs that exist on different domains, but I usually only text for one group at a time.

**Comment by ibrand** [comment]
The case for this would probably be that you've learned about different issue areas or campaigns from a org that hosts a spoke for smaller orgs (for example the New York Civic Engagement Table which hosts an instance for all the smaller local NYC orgs that are members of the table that don't have the infrastructure to host their own) and end up on a few local campaigns with their orgs on different issues. Because the parent org would be running the instance for several smaller orgs, you'd then be able to see what your assignments were across the sub orgs.

**Comment by arena** [comment]
Thanks for clarifying. 

Do you think it would be annoying if we simply showed a section header for each org on the dashboard? 
Any thoughts on how they should be ordered?

Do you think there are cases where someone would have so many orgs that this would be overwhelming? 
If it wouldn't be overwhelming, I think the design could be pretty simple. 
If it would be overwhelming, we should explore ways to hide, order, or collapse inactive or ignored orgs.

**Comment by mau11** [comment]
We are reviewing outstanding issues. Closing, see comments here: https://github.com/StateVoicesNational/Spoke/pull/1872
