### ISSUE TITLE
Bug: Yellow badges on buckets of handled conversations prompt unexpected opt-outs by new volunteers

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1874]
**Problem**
Volunteer texters see the yellow badges on buckets of handled conversations and want to get rid of the badges so they opt people out to “clear” those conversations leading to lots of admin clean-up.

**To Reproduce**
This is a design issue --- the software is working as expected but the humans are confused. 

**Solution**
1. remove the yellow badges
2. reword the labels to complete the sentence “I want to ____” with: “view past” and “view skipped” 
3. either ignore the count or insert it into the label of the button (e.g. “view 2 skipped” or “view 22 handled”)

**Screenshots**
https://www.figma.com/file/mfDrcffzFnb0Iwsjq6Srdz/We-don-t-need-yellow-badges?node-id=0%3A1

**Additional context**
"We’re seeing a pattern of people going back into Past Messages and Skipped Messages and trying to get rid of them somehow (in some cases by opting people out :sob: which creates a ton of clean-up work).
Is there any reason to have an alert badge on these buttons? I can’t think of one and would like to see those yellow circles with a number in them go away." -Dinah, Admin

**Comment by schuyler1d** [comment]
++ to doing all three -- i think having the count is useful, but I don't think it needs to be on a badge -- either "View Skipped (5)" or as you have it "View 5 Skipped)

**Comment by arena** [comment]
My favorite is the number in the middle because it feels less like like a badge. It feels more FYI and less todo.

**Comment by stefanhayden** [comment]
This update look good? 

![image](https://user-images.githubusercontent.com/87616/108149914-bd207a80-70a1-11eb-83d0-7f1c52f1d2e5.png)

**Comment by arena** [comment]
Looks good to me! 👍

**Comment by arena** [comment]
cc'ing @dinahsanders since she will appreciate the improvement

**Comment by DinahSanders** [comment]
Thanks, @arena and @stefanhayden and @schuyler1d! I surely do! 💯
