### ISSUE TITLE
Feature Request: Indication of Which Organization You Are In

### ISSUE THREAD

**Issue by ntashladhani** [ProgressiveCoders/Spoke#1884]
**Problem**
With a Multi-Org set up, once you select an org from the drop down, there is no indication of which org you are in besides the organization id in the url. Looking at the UI itself, however, I can't tell which organization I'm in.

**Solution**
Have a header that says the name of the org at the top or highlight the org you are in within the drop down menu.

**Context**
Header could be above the "Campaigns" title or some marker in the drop down menu
<img width="1435" alt="Screen Shot 2020-11-09 at 12 06 31 PM" src="https://user-images.githubusercontent.com/67773100/98572877-2400ed00-2284-11eb-97f1-e26aea25d097.png">
<img width="562" alt="Screen Shot 2020-11-09 at 12 06 41 PM" src="https://user-images.githubusercontent.com/67773100/98572878-2400ed00-2284-11eb-8414-e2d013a8a81d.png">

**Comment by arena** [comment]
I think org level theme/branding would address this... But I think that got delayed because of the way material design is used in the code.

**Comment by Frydafly** [comment]
Adding for reference that the feature request for org branding is https://github.com/MoveOnOrg/Spoke/issues/1504
