### ISSUE TITLE
Bug: Documentation to run local setup with postgres says to populate database before running it

### ISSUE THREAD

**Issue by navinsivakumar** [ProgressiveCoders/Spoke#1892]
**Describe the bug**
In the local setup instructions to [use Docker to run Postgres](https://github.com/MoveOnOrg/Spoke/blob/main/docs/HOWTO_DEVELOPMENT_LOCAL_SETUP.md#using-docker-to-run-postgres-optional), the instructions say to run `./dev-tools/create-test-database` before running `docker-compose up -d`. You need to run the database first before running the tool to populate it.

**To Reproduce**
1. Go to the Spoke root director.
2. Run `./dev-tools/create-test-database` without Postgres running in Docker.
3. Get `ERROR: No container found for postgres_1`.

**Expected behavior**
The documentation should tell us to run Postgres before trying to populate it.

**Comment by navinsivakumar** [comment]
I can send a PR to swap the steps.

**Comment by Frydafly** [comment]
@ibrand this is what we ran into recently during set up no?
