### ISSUE TITLE
csv uplaod issue

### ISSUE THREAD

**Issue by python4GH** [ProgressiveCoders/Spoke#1908]
hi Spoke team,

 I recently set up a spoke on Heroku which worked out fine till I had to upload the CSV. I fount out that CSV upload function only  accepts are only US numbers and I an in ghana, is there a way to configure the files to accept Ghanian numbers

**Comment by joemcl** [comment]
Check out PHONE_NUMBER_COUNTRY env setting - see
https://github.com/MoveOnOrg/Spoke/blob/main/docs/REFERENCE-environment_variables.md

**Comment by arena** [comment]
this seems like a handled issue, anyone object to me closing it?

**Comment by Frydafly** [comment]
Closing this!
