### ISSUE TITLE
">Claudia create --role SpokeOnLambda" significance

### ISSUE THREAD

**Issue by harrybaker-md** [ProgressiveCoders/Spoke#1909]
Hello,

Maybe this is a dumb question, but what is the significance to the --role SpokeOnLambda flag in the Deploy Step of the AWS Lambda Instructions? I'm currently struggling to get that working, and I'm wondering if this is why. The rest of the documentation never mentions creating a SpokeOnLambda role. Is this something that has to be done before deployment, or will executing the script in the "Deploy" section create it?

I'm currently getting Access Denies when running Claudia even though when I run AWS s3 or s3cmd directly it works fine.

**Comment by arena** [comment]
Hi
I don't know the answer to your question but I have two suggestions
1. If you aren't on the progcode.org slack, you should join. It's a good place to ask questions. 
2. I suggest we convert this issue to a feature request for documentation so that someone can add the answer to the readme or to the /docs folder

**Comment by harrybaker-md** [comment]
Hi,

I applied to join the slack last week and am still waiting to hear back.

**Comment by ffaristocrat** [comment]
yeah, it's not in the documentation. You have to create the Role yourself. Use the wizard to give the baseline Lambda permissions and add AmazonS3FullAccess.

**Comment by Frydafly** [comment]
@ffaristocrat thanks for this! 

@harrybaker-md did that help you in your set up? would be great if either of you replied with a few more details on what you had to do to get this working, since this will be so helpful for the documentation!

**Comment by ffaristocrat** [comment]
Here's the exact policy we use in our cloudformation template.

```
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - lambda.amazonaws.com
                - apigateway.amazonaws.com
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - s3:*
                Resource: "*"

```
