### ISSUE TITLE
The login fields and log in button should all be visible on the auth screen without scrolling on mobile devices

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1910]
**Problem**
This is a pretty minor problem that may cause a minor amount of confusion for users on mobile devices. However, it would set a nice first impression (and eliminate any minor confusion) to make the "LOG IN" button appear closer to the login fields so that users on mobile devices do not need to scroll down to get to the button. 

**Solution**
a. keep the same design but make the need to scroll go away
b. change the layout so the "LOG IN" button is free standing and right below the email and password fields (instead of glued to the very bottom of the view like it is now).

**Screenshot**
This screenshot was taken on a mobile device. Note: the issue is not apparent if you select a mobile device emulator in a desktop browser, but when the mobile browser chrome is added to the screen (or something) the LOG IN button ends up below the fold. 
![image](https://user-images.githubusercontent.com/411070/104376395-ceda9500-54d9-11eb-95a9-379e5d5ab607.png)

**Comment by marzvrover** [comment]
I'm going to work on this issue. Commenting to easily find issue to reference once dev environment is set up.
