### ISSUE TITLE
-1 Error Message

### ISSUE THREAD

**Issue by wu2202** [ProgressiveCoders/Spoke#1934]
Hi everyone, I'm a bit new to Spoke. Recently, I tried launching a campaign, but I kept getting the -1 error message not sent. Does anyone know how to troubleshoot?

**Comment by Frydafly** [comment]
Hi @wu2202! Sometimes resetting the twilio message service information has worked for me. 

Also, I'd love to invite you to join the progcode community (https://www.progcode.org/) we have a channel called `#spoke` where you might be able to get faster support for these issues!

**Comment by arena** [comment]
@nireia this issue already exists. See the suggestion above in case it helps and I also recommend joining progcode

**Comment by mau11** [comment]
Hi @wu2202, we are reviewing outstanding issues. The error may occur if your Twilio environment variables are not properly configured. Please open a new issue if this issue still persists.
