### ISSUE TITLE
Feature Request: Change default message texters see on todos screen when they have "nothing to do" 

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1939]
**Problem**
When texters are done sending a batch of texts (and there are no replies or other active campaigns on their todos dashboard) they will often see a screen with the message "You have nothing to do." This is the wrong message, especially for inexperienced texters. The texters have something to do, at the very least they should be encouraged to check back for replies.

**Solution**
Change the default from "You have nothing to do" to "Sending complete. Please check for replies by refreshing in a few minutes."

**Context**
There may be a request to make this message customizable at some point. There may also be work that makes this screen go away all together, ideally always landing texters back at their dashboard where they can see that they are waiting for replies, can start sending more texts... or in some cases, actually have nothing to do (maybe because there are no active campaigns).

**Comment by schuyler1d** [comment]
Changing the default text is here:
https://github.com/MoveOnOrg/Spoke/blob/main/src/containers/TexterTodoList.jsx#L118

It can already be overridden in the dynamic assignment Texter UI with the "Summary text when there is nothing to do" option.

I'm not sure the suggested text is ideal -- it's a bit long so I'm interested to know what it looks like on mobile.  Also, there are scenarios where someone will see the message and they haven't sent anything -- e.g. when they join a campaign that has no more contacts left.  But overall, I'm ++ on this.

**Comment by arena** [comment]
Closed since there is a way to do this
