### ISSUE TITLE
Feature Request: character limit on message field

### ISSUE THREAD

**Issue by arena** [ProgressiveCoders/Spoke#1940]
**Problem**
Texters can send any length message they type or paste. 

**Solution**
Set a character limit.

**Context**
This doesn't need to be restrictively low (140, 160, etc) but should be set to prevent texters from sending an entire pasted article or whatever. 

Here is 1000 bytes of Lorem Ipsum (maybe double that in case there is some need for lots of emoji) but seems like more than enough to me

`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi pretium orci ut orci accumsan scelerisque. Vestibulum magna velit, commodo nec felis at, aliquet placerat mi. Donec vitae aliquam sem, sed auctor justo. Etiam non tellus eu lacus scelerisque mattis sed ac arcu. Phasellus elementum elit posuere, euismod nunc sed, luctus velit. Cras bibendum, massa id imperdiet lobortis, libero nisi scelerisque nisi, eu scelerisque ex augue vel neque. Integer vehicula nulla et mollis eleifend. Sed et enim lacus. Maecenas id imperdiet lectus. Aenean vulputate ultricies leo sed dapibus. Vivamus eget congue elit, et pulvinar augue. Sed in fringilla tortor. Duis accumsan cursus facilisis.`

`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec viverra neque, tristique interdum leo. Sed mattis leo semper sagittis dictum. Vestibulum vitae nibh viverra, ultricies lacus at, sollicitudin quam. Mauris consectetur nec urna ut pulvinar. Suspendisse pulvinar rutrum quam, sed efficitur est aliquam.`

![image](https://user-images.githubusercontent.com/411070/110162542-bb45ff00-7da3-11eb-9be0-64c3a57f2e73.png)

**Comment by DinahSanders** [comment]
Someone (who isn't me) with internationalization experience should look at this. Not sure what is a reasonable "more than enough" for other languages/character sets.

**Comment by Frydafly** [comment]
Hi @arena! Looks like currently we can use `MAX_MESSAGE_LENGTH` in the [env variables](https://github.com/MoveOnOrg/Spoke/blob/main/docs/REFERENCE-environment_variables.md) to set a character limit. 

Does this setting resolve your feature request? Or would you like to see more options available?

**Comment by arena** [comment]
Ok. I'll close this. It's just not set up on the staging instance I was using for testing.
