### ISSUE TITLE
Feature Request: Support ngrok in Dev Env

### ISSUE THREAD

**Issue by Frydafly** [ProgressiveCoders/Spoke#1951]
**Problem**
There isn't currently a way to automate tunneling on dev env using ngrok

**Solution**

- Supporting ngrok in Dev Env would allow folks to do local dev AND setup twilio to use

- As an alternative, we could create documentation on how to run your local server and then run ngrok command separately (to proxy the port through to ngrok), which would not require any changes to the code. 

**Context**
Issue is a follow up made in order to not abandon this now-closed PR from 2017 https://github.com/MoveOnOrg/Spoke/pull/367

**Comment by mau11** [comment]
Hi @Frydafly, we are reviewing outstanding issues. Spoke has since been updated to support this (see docs: https://statevoicesnational.github.io/Spoke/#/HOWTO_DEVELOPMENT_LOCAL_SETUP?id=ngrok). Please open a new issue if this issue still persists.
