### ISSUE TITLE
Bug: Include Unsent Initials (Needs First Message) in Contacts Export

### ISSUE THREAD

**Issue by ryanjcrump** [ProgressiveCoders/Spoke#1954]
**Problem**
When exporting data from campaigns, contacts that were not sent an initial message are not currently exporting. 

**Solution**
Let's include uncontacted contacts (status = Needs First Message) in contacts export with appropriate status data

**Comment by codygordon** [comment]
I think this is actually a bug – contacts with `needsMessage` status do seem to export, but contacts without an assignment weren't.
