### ISSUE TITLE
Bug: Per-Campaign Messaging Service not functioning

### ISSUE THREAD

**Issue by ntashladhani** [ProgressiveCoders/Spoke#1965]
**Describe the bug**
We have a few organizations that would like to use a per-campaign messaging service, but it isn't allowing for phone numbers to be pulled in to specific campaigns. It was functioning previously, but now doesn't allow for this. I have tried removing and re-putting in the feature in the organization. Now, when I go to the Phone Numbers section in the admin panel, I get a graphql error

**To Reproduce**
1. Go to the database and add the following to the features section in an organization: `"EXPERIMENTAL_TWILIO_PER_CAMPAIGN_MESSAGING_SERVICE":1,"EXPERIMENTAL_CAMPAIGN_PHONE_NUMBERS":1`
2. Refresh the cache
3. Go to the spoke organization in the UI and click on Phone numebrs
<img width="1139" alt="Screen Shot 2021-03-25 at 3 46 56 PM" src="https://user-images.githubusercontent.com/67773100/112534391-65042480-8d81-11eb-8ffb-c735e4209380.png">

**Expected behavior**
I should be able to purchase phone numbers that are then available for the organization and in the campaign creation, bring them in to that campaign

**Platform (please complete the following information):**
 - OS: MacOs 11.1
 - Browser Chrom
 - Desktop
 - Version 10

**Comment by Frydafly** [comment]
Hi @ntashladhani, when you say it was functioning previously, do you mean in a previous version of Spoke?

**Comment by Frydafly** [comment]
Also what variable, if any do you have set for `EXPERIMENTAL_PHONE_INVENTORY` or `PHONE_INVENTORY`?

**Comment by ntashladhani** [comment]
Yes, it was working in a previous version of Spoke. PHONE_INVENTORY is set to 1

**Comment by Frydafly** [comment]
pinging @jeffm2001. jeff, not sure if you happen to have any ideas here! I recall you knowing a lot about these functions. figured i'd try!

**Comment by Frydafly** [comment]
@ntashladhani wonky thing, but try changing writing the json format exactly like this `EXPERIMENTAL_CAMPAIGN_PHONE_NUMBERS: "1"` and remove the "EXPERIMENTAL_TWILIO_PER_CAMPAIGN_MESSAGING_SERVICE":1 variable and refresh.

**Comment by Frydafly** [comment]
How's this going after our meeting @ntashladhani ?

**Comment by Frydafly** [comment]
Closing now that it's working!
