### ISSUE TITLE
Bug: <cannot log into Spoke from Heroku>

### ISSUE THREAD

**Issue by ec4sf** [ProgressiveCoders/Spoke#1979]
Hi, 

I built a heroku app for the Spoke based on instructions provided byhttps://docs.google.com/presentation/d/1AtLE2vm5C9g8FpI438aRom75WpQh7KJAxwJ53ZOPVHA/edit#slide=id.g9f7f57cf84_0_213.

It says it has been successfully deployed; however, when I click on "open app," it takes me to the Spoke signon page, but when I type in my username and password, there is an error, and it does not let me in. 

The instruction says, log on to the app and create an org, but without creating an org beforehand, it does not seem like they will let you use the platform to begin with. 
 
Screenshots attached. Any help would be appreciated. 

![Slide2](https://user-images.githubusercontent.com/82676044/115098696-44456f80-9ee6-11eb-89c4-bdd3267ab91e.JPG)

**Comment by Frydafly** [comment]
Hi @ec4sf ! 

Did you set up an auth0 login? 

If so, when you click on "log in and get started", can you click on the "sign up" tab and create an account for yourself?

**Comment by mau11** [comment]
Hi @ec4sf, we are reviewing outstanding issues. Make sure you have SUPPRESS_SELF_INVITE blank in your .env file (see docs: https://statevoicesnational.github.io/Spoke/#/HOWTO_HEROKU_DEPLOY?id=important-note-for-first-time-deployers) Please open a new issue if this issue still persists.
