### ISSUE TITLE
Bug: backend error Error: select count(*) from `zip_code` limit 1 - SQLITE_ERROR: no such table: zip_code

### ISSUE THREAD

**Issue by eudaimonstro** [ProgressiveCoders/Spoke#1981]
**Describe the bug**
Running npm run dev results in the error `backend error Error: select count(*) from `zip_code` limit 1 - SQLITE_ERROR: no such table: zip_code` ... `[nodemon] app crashed - waiting for file changes before starting...` Spoke is unreachable on `localhost:3000`

**To Reproduce**
1. clone repo
2. run `npm install --force`
3. run `docker-compose up -d`
4. run `dev-tools/create-test-database`
5. run `npm run dev`

**Expected behavior**
No error and Spoke should be running on `localhost:3000

**Screenshots**
![image](https://user-images.githubusercontent.com/5083012/115127598-89bc7800-9f8c-11eb-9f4c-47369365df14.png)
![image](https://user-images.githubusercontent.com/5083012/115127609-9c36b180-9f8c-11eb-92e6-e3b5a8d5e128.png)

**Platform (please complete the following information):**
 - OS: Fedora 33
 - Browser N/A
 - Desktop or Mobile? N/A
 - Version: master branch

**Comment by Frydafly** [comment]
Hi @eudaimonstro ! Just pointing to this documentation https://github.com/MoveOnOrg/Spoke/blob/a5f52ec10f620efcad7df35af819df5e2072657d/docs/HOWTO_DEVELOPMENT_LOCAL_SETUP.md 

If you follow the steps in the documentation above, do you still get the same bug after cloning the repo?
