### ISSUE TITLE
Feature Request: Zapier Response Handling

### ISSUE THREAD

**Issue by aspensmonster** [ProgressiveCoders/Spoke#1983]
**Problem**
We (Homes Not Handcuffs, Austin DSA) wanted to be able to fire off payloads to Zapier whenever a response was registered.

**Solution**
The Zapier action handler worked for tags, but not responses. So we added the feature:

https://github.com/aggroskater/Spoke/blob/zapier-test/src/extensions/action-handlers/zapier-action.js

**Context**
This code was used for a GOTV textbank of a universe of 46k numbers. The spoke instance was deployed from the prod heroku button/link of the repo, and had a premium dyno backing it.

We introduced `ZAPIER_TIMEOUT_MS` to make timeout configurable (if Zapier was being slow; it wasn't) and `ZAPIER_CONFIG_OBJECT` for letting us set the webhook URL per-answer. Zapier's existing functionality ("Paths") for this is limited to start with (3 paths), and support will only raise it to 10 paths, meaning it makes far more sense (or did for us) to make independent webhooks per-response.

This code is likely not ready for merging, but I *did* want to at least get the ball rolling. If for no other reason than letting other socialist techies know that this can be done and has been done, so don't worry about staying up all night coding it the night before a big GOTV campaign. Just use this (or something similar) :)

Edit: Also... this isn't really limited to Zapier. You could fire off this payload to *any* URL that takes JSON payloads via HTTP POST.

**Comment by Frydafly** [comment]
hey @aggroskater , that sounds great! would you want to submit a PR for this, even a work in progress / draft one? would love to see that!

**Comment by aspensmonster** [comment]
@Frydafly  I'll be sure to get one going after May 1st (election day). We're nose to the grindstone presently :)
