### ISSUE TITLE
Feature Request: Show time since message was claimed in message review

### ISSUE THREAD

**Issue by stefanhayden** [ProgressiveCoders/Spoke#2004]
**Problem**
When looking at message review and seeing all contacts that "Needs First Message" there is no way to know how long that message has been assigned to that texter. It is then hard to know if I need to assign that text to a texter who is currently online or not.

**Solution**
The message review should show how long a person has owned an initial for "Needs First Message" so I can make decisions on what to do with that message.

**Context**
Often we don't want to take texts away from people who have just been assigned those messages but it's just not clear who has just been assigned.

**Comment by schuyler1d** [comment]
hm.  I think we'd need to have that timestamp first.  I think the easiest way to do this is:
1. add updated_at: new Date() here: https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/mutations/findNewCampaignContact.js#L147-L149
2. get the campaign_contact.updated_at in the MessageReview fields and display it (at least when needsMessage status is true) -- not sure where/when else campaign_contact.updated_at gets changed -- looking at the code, I don't see anywhere actually.
