### ISSUE TITLE
Bug: Export campaign button sometimes not appearing for owner

### ISSUE THREAD

**Issue by bxjw** [ProgressiveCoders/Spoke#2007]
**Describe the bug**
Despite being the org owner, sometimes when I navigate to a campaign, my side bar menu disappears except for "Close Menu" and "switch to texter". This happens sporadically when I click into a campaign and all the buttons  disappear (except for Convos). When that happens, if I click on "Convos" and then go back, the export button (and other buttons) appear..

**To Reproduce**
1. Go to the page of a specific campaign. Admin settings may not be showing completely.
2. Click to "convos" and return to see export button.

**Expected behavior**
I would expect to continue seeing the normal admin layout and buttons.

**Screenshots*
![image](https://user-images.githubusercontent.com/15195793/121594838-99e05900-ca0b-11eb-98b8-c4bc401493c6.png)

**Platform (please complete the following information):**
 - OS: MacOS Big Sur v11.3
 - Browser: Chrome v90.0.4430.212
 - Desktop
 - Version: Spoke v10.2

**Comment by mau11** [comment]
Thank you @bxjw, we're reviewing outstanding issues. It appears this user does not have the proper permissions to view the other options/buttons. If you're still having issues, please feel free to reopen.
