### ISSUE TITLE
Feature Request: Auto-Opt Out responses

### ISSUE THREAD

**Issue by agreenspan24** [ProgressiveCoders/Spoke#2009]
**Problem**
The auto opt-out message handler saves an opt out to our database. However, it doesn't let the contact know that we've removed them from our list. Plus, texters don't see the auto opted-out contact, so they can't send an opt-out message manually.

**Solution**
As part of the auto opt-out message handler, send the organization's default opt out message back to the contact being opted out.

**Context**
Twilio has their own effective auto opt-out, which blocks any additional messages after specific keywords are sent. We may need to exempt these specific keywords from this new feature.
https://support.twilio.com/hc/en-us/articles/223134027-Twilio-support-for-opt-out-keywords-SMS-STOP-filtering-

**Comment by agreenspan24** [comment]
@schuyler1d @Frydafly I'm working on this, should be fairly easy. Let me know if you have any additional requirements or comments on it.

**Comment by crayolakat** [comment]
This fix for this was merged into the `main` branch for the 12.2 release, but some rebasing caused the issue to not close automatically. Manually closing this issue.
