### ISSUE TITLE
Feature Request: Both opt-out buttons should be in the same place so I don't have to move my mouse.

### ISSUE THREAD

**Issue by stefanhayden** [ProgressiveCoders/Spoke#2013]
**Problem**
When I opt out I need to click 2 buttons but the button moves when the modal opens and it slows me down.

**Solution**
Both buttons should be in the same spot.

![optout gif](https://user-images.githubusercontent.com/87616/124190495-5e77fe00-da90-11eb-8d8c-900f6956e96e.gif)

**Comment by arena** [comment]
What's might that look like? 
Possibly a pop-over from the button?
Possibly no confirmation step but a way to undo?
A change in button state from "Opt out" to "Confirm" plus a color change? 
+
A keyboard shortcut that would let you one-click opt out?
Maybe an option in the confirmation dialog that says "don't show again" (then to clear the standard reply you'd need to select and delete what's in the response message field occasionally)

**Comment by arena** [comment]
Also, I agree. The intuitive thing when designing a messaging ui is to make it hard to accidentally opt someone out. However, since texters need to opt out around 50% (give or take) of their response queue it makes sense to streamline rather than prevent mistakes. 

I imagine there are different opinions on what to optimize for but I support reducing response times and reducing repetitive motions (improve efficiency and ergonomics).

Undo opt-out would be great as a follow up feature

**Comment by stefanhayden** [comment]
I was really just thinking of shifting the 2nd button to be in the same spot as the first.

- I like the idea of no confirm but an undo. Might be hard since an opt out causes you to go to the next person in the queue.
- A keybaord short cut would also be great. I would love every action in spoke to have some shortcut for better speed an accessibility.

good ideas!

**Comment by arena** [comment]
So, would the modal be attached to the button but overlap it when it opens?

**Comment by arena** [comment]
Are you imagining something like this: https://www.figma.com/proto/EzvSYKxURLu4HHU50E73QI/Opt-Out-Modal-Placement?page-id=0%3A1&node-id=1%3A24&viewport=414%2C987%2C0.5&scaling=min-zoom

**Comment by stefanhayden** [comment]
yes! Exactly like that.

**Comment by schuyler1d** [comment]
This movement of the buttons is intentional to avoid accidental 'full optout' before someone realizes they accidentally clicked the optout button.  It's similar to a delete confirmation popup.
