### ISSUE TITLE
Remove pm2

### ISSUE THREAD

**Issue by sandramchung** [ProgressiveCoders/Spoke#205]
Since we can now run everything in a single process in node, pm2 is unnecessary. Also it's not great to have yet another place to update environmental variable config.

**Comment by hiemanshu** [comment]
I don't think removing pm2 would be a good idea. We could remove the env variables in the pm2 config, and point to the `.env.example` to see what variables need to be set. Having a PM2 config would make it easier to deploy on other VPS like servers (EC2, DO, etc). Also running everything off a single process is bad for scalability.
