### ISSUE TITLE
Reusable Scripts

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#21]
As an admin, I want to be able to reuse scripts from previous campaigns so that I can text a new group without re-creating the conversation flow each time. 

Copying a campaign involves creating a new campaign with title info (from campaign table), script data and canned response data (texters and campaign contacts should not carry over).

**Comment by schuyler1d** [comment]
This probably involves listing/copying https://github.com/MoveOnOrg/Spoke/blob/master/src/server/models/interaction-step.js instances from another campaign
