### ISSUE TITLE
Ability to 'redelegate' a contact to another texter (with a skill, e.g. language)

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#210]
Use-case: As a texter, I only know English, but other texters know Spanish. When a contact responds in Spanish, I want to be able to re-delegate the contact to a texter that knows Spanish.

Implications:
* texters (users) need 'skills' (and maybe campaigns need them, too)
* needs ui for how to 'reassign' a contact to another texter with an available skill
* needs ui or some method to mark users with skills

(use case from NY Civic Engagement Table)

**Comment by shakalee14** [comment]
Handled with #678
