### ISSUE TITLE
Cancelling a new script should close form rather than validate

### ISSUE THREAD

**Issue by lady3bean** [ProgressiveCoders/Spoke#226]
Currently when you hit cancel to exit out of adding a new script, it seems to validate the form and keep the dialogue box open, rather than closing it. 

<img width="1364" alt="screen shot 2017-09-14 at 3 41 10 pm" src="https://user-images.githubusercontent.com/10011287/30452305-324b2a36-9963-11e7-9a2e-af8389ebc24f.png">

**Comment by SAnschutz** [comment]
I'd be happy to take care of this one.
