### ISSUE TITLE
Local area codes

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#23]
- [ ] As a texter, I should be able to send messages to contacts with a phone number with a local area code.

**Comment by mathemagica** [comment]
Some more notes after talking to Shaka: the sender of the text message gets assigned a "from" number from twilio, and we think textees are more likely to respond if the "from" area code is the same as their area code. So when calling twilio to make the text happen, if possible choose a "from" area code that matches the area code the message is getting sent to.

**Comment by shakalee14** [comment]
- [ ] Create a messaging service via twilio that uses local phone number matching 
- [ ] Replace the 'from' in message.create with the messaging service sid
- [ ] Check if there is a number in the pool that you can use (with regards to how many people you need to text within an area code) --> if not
- [ ] Purchase phone numbers from around the country either manually (boooooo)
--> [ ] via doing another call to the twilio api requesting a list of [available phone numbers and then purchasing it ](https://www.twilio.com/docs/api/rest/available-phone-numbers) 
--> .org discount for long numbers via twilio 0.75/month

**Comment by mathemagica** [comment]
Note from Shaka: there's of risk of numbers getting marked as spam. If you send a certain amount of texts from certain numbers we'll get these marked as spam and then these texts could get blocked. So research best practices for avoiding this- maybe we need to regularly rotate numbers in and out. Prev authors considered cycling numbers out after 250K texts sent. Understand the tradeoff between cost and spam risk.

**Comment by sreynen** [comment]
Related: https://github.com/MoveOnOrg/Spoke/pull/60

**Comment by sreynen** [comment]
There are 800 area codes in the US, and numbers cost $0.75/month for non-profits, so our max cost for one local number in every area code would be $600.

https://support.twilio.com/hc/en-us/articles/223181848-How-Does-Carrier-Filtering-Work- describes what would cause a number to get marked as spam, and as long as we're distributing our messages across different numbers, we don't seem especially likely to hit any of the quantity or rate caps, but if our messages get flagged as being too similar, that's a less predictable reason to get marked as spam.

Twilio will notify us if they're notified that a number has been blacklisted, so we should drop those numbers from our pool if that happens, but Twilio doesn't necessarily get notified, so we can't rely on getting notified.

To control costs, we should remove any numbers from our pool that we haven't used recently. To minimize the risk of a number getting blacklisted, we should replace existing numbers in our pool with fresh numbers in the same area code when available. We could do all of that in an update-pool task that runs periodically, maybe weekly. And we could also use an optional MaximumNumbersInPool config option to cap the cost when needed.

**Comment by sreynen** [comment]
When I went to create a new worker to refresh numbers in the Twilio pool, I noticed there's already a worker named number-assigner.js, which sounded like it might be related to this. After some research, documented in https://github.com/MoveOnOrg/Spoke/wiki/Worker-Processes, I believe this existing script is doing much of what Twilio's Messaging Services option will do if we start using that.

Which raises two questions for me:

1. Do we want to maintain the option to choose sender numbers directly and not use Messaging Services to choose for us?
2. Do we want to maintain Nexmo as a sender option?

Depending on the answer 1, I think we either need to strip out or update everything related to `user_number` in the `message` table. And depending on the answer to 2, either need to research what the options are for doing this with Nexmo, or create an issue to remove Nexmo code and all the service switching, if not do that under this issue.

**Comment by sreynen** [comment]
Also, regardless of the answer to those questions, all the message-sender workers will need to be updated to segment the load on something other than `user_number` (probably `contact_number` is best) when that's no longer a required field on messages.

**Comment by shakalee14** [comment]
1) We want to use phone numbers with area codes local to the contact when we choose a phone number. To my understanding, this number assigner process does not choose based on local area codes. Another option I guess it to purchase a pool of phone numbers, hit that twilio endpoint  and do some filtering process based on the first 3 digits to assign the number? 

2) I think as an open source project, maybe it's good to have two options for sender options but open to other opinions.

**Comment by sreynen** [comment]
Okay, I'll do some research on Nexmo's options for auto-choosing the sender number like Twilio does. Maintaining decent Nexmo support might be difficult without active testing on Nexmo, since the Twilio code for choosing the sender number is going to be very different.

**Comment by sreynen** [comment]
It's not clear to me from Nexmo's documentation whether or not it can do something similar to what Twilio does with auto-selected send numbers. I think we'd need to get an actual Nexmo account to try that. And even if we're aiming to leave Nexmo functionality as-is, I think we're going to be making enough changes that we won't really know if it still works without a Nexmo account to test on. So I guess my vote is we either get a Nexmo account to test Nexmo functionality, or we drop Nexmo functionality if we can't test it.

**Comment by sreynen** [comment]
With https://github.com/MoveOnOrg/Spoke/pull/79 merged and https://github.com/MoveOnOrg/Spoke/pull/68 on hold, I think this issue is as complete as it can be for now.
