### ISSUE TITLE
Make Webpack and Babel use OUTPUT_DIR

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#230]
Currently `npm prod-build` deletes the directory defined by the `OUTPUT_DIR` environment variable, then Webpack and Babel package client and server files to `./build`, regardless of what `OUTPUT_DIR` is set to. Ideally these would all use the same directory, defined by `OUTPUT_DIR`.

**Comment by ibrand** [comment]
@sreynen @schuyler1d is this still true? If so, might make a good first issue for an infra-interested person

**Comment by schuyler1d** [comment]
I don't see output_dir in our webpack config. I don't think any current deployment approaches would be improved with this, so closong
