### ISSUE TITLE
Opt-out button with mobile view overlays other buttons and is unavailable on iPad

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#233]
![bugoptoutmobile](https://user-images.githubusercontent.com/52117/30600057-67f45884-9d2c-11e7-84df-b75a5260eb00.png)

**Comment by shakalee14** [comment]
<img width="358" alt="screen shot 2017-09-19 at 11 26 40 am" src="https://user-images.githubusercontent.com/16676323/30602369-6212247c-9d32-11e7-9783-5a5c922fd01c.png">

PR: https://github.com/MoveOnOrg/Spoke/pull/236
