### ISSUE TITLE
Bug: GHCR Failure

### ISSUE THREAD

**Issue by crayolakat** [ProgressiveCoders/Spoke#2344]
**Describe the bug**
GHCR doesn't appear to be set up in the StateVoicesNational GitHub organization, so the GitHub Action workflow to build and push the Docker image to GHCR always fails.

**To Reproduce**
1. Push a commit to the `main` branch. Observe failing GitHub Action workflow. Example: https://github.com/StateVoicesNational/Spoke/actions/runs/7105580530/job/19343089416

**Expected behavior**
The GitHub Action workflow should succeed.

**Screenshots**
Example failure: https://github.com/StateVoicesNational/Spoke/actions/runs/7105580530/job/19343089416

**Platform (please complete the following information):**
 - Version: 13.1.0

**Additional context**
Images were previously published in MoveOn's GHCR here: https://github.com/orgs/moveonorg/packages/container/package/spoke

**Comment by engelhartrueben** [comment]
Apologies for the delayed response.

The links provided expired by the time I had looked at this, so I am only guessing based off of the URL.

We have adjusted the Docker image ([f94d03b](https://github.com/StateVoicesNational/Spoke/commit/f94d03b62ba6632f6ff1a1f9c6e477711da4e2c6)) for our `new-node-20-branch` which has now allowed for tests to not only run, but pass like so:
![image](https://github.com/StateVoicesNational/Spoke/assets/140833605/ccf9f5ad-6a61-4267-acbd-ca795e09a381)
source: #2353 

Is this what you were referring to? I remember seeing some discrepancies between the Node version on the Spoke Application versus the Docker Image.

Thanks for pointing this out

**Comment by crayolakat** [comment]
Hi @engelhartrueben, I'm actually referring to the failing workflow on the `main` branch! If you go to https://github.com/StateVoicesNational/Spoke and click the red X next to the latest commit the failing GHCR workflow will display
![image](https://github.com/StateVoicesNational/Spoke/assets/9382984/d7fdb6a8-9d66-4a1b-9714-be09fba0f3ba)

**Comment by engelhartrueben** [comment]
#2381 fixes this and will be added to 14.1 release
