### ISSUE TITLE
Display Campaign Name in header field

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#237]
This is slightly more difficult than one would imagine, because the 'current campaign' is not available at the top-level (but it should be).

This is still marked easy, because it will be a good 'stub' for adding a new graphQL query to an existing component.  We should also perhaps have top-level state for 'current' campaign data, which can also be used in default navigation.

Main code point is here: https://github.com/MoveOnOrg/Spoke/blob/master/src/components/TopNav.jsx
But you'll want to see where TopNav is included in src/containers/ and src/components/
and then also see where the current campaign is learned/set within the routes that have it.

**Comment by JeremyParker** [comment]
Third time lucky :)
@shakalee14 @schuyler1d I'd like to take a stab at THIS issue.

**Comment by schuyler1d** [comment]
Great!

**Comment by JeremyParker** [comment]
I'm interpreting this issue to mean display the campaign name in header field *when we're in the texter view*. Is that correct? As I understand the UI, the screens in Admin mode don't necessarily correspond to a particular Campaign. The data there is global. Is that right?

**Comment by 1kindjune** [comment]
@schuyler1d  Hi! Can you assign this to me unless it has been completed?

**Comment by schuyler1d** [comment]
@1kindjune please accept the invite at https://github.com/MoveOnOrg/Spoke/invitations

**Comment by ibrand** [comment]
Hey @schuyler1d and @1kindjune (@JeremyParker ?)  I'm cleaning up our `good first issues`s and want to know if this one was completed (since it's pretty old) or if it's open for new contributors to claim!

**Comment by schuyler1d** [comment]
I don't see it there.  I believe this is still desired and not done.

**Comment by Anasauce** [comment]
Hey I can take a stab at this if no one is currently working on it! Recommended to me on the prog-code slack channel :)

**Comment by ibrand** [comment]
Closing because the new texter UI includes this! #1493
