### ISSUE TITLE
On people screen, superadmin cannot change a person's role

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#239]
To reproduce:

1) Go to /admin/{orgId}/people
2) For any texter, click "Texter" and change the drop-down to "Admin"
3) The drop-down should now say "Admin" or give some indication that the change is being saved. Instead, it still says "Texter"

**Comment by Anasauce** [comment]
I think this is only happening on the client-side. I was testing it out today.

**Comment by sandramchung** [comment]
Roles and perms need work overall. Currently: 

- Superadmin status alone doesn't let you do or see anything in any of the orgs. You need to also have an admin or owner role in the org.
- The original owner/creator of an org by default ends up with owner, admin and texter roles for that org.
- A superadmin with admin role in an org can convert that org's texters to admins and vice versa, but can't edit the roles of owners at all.

Suggest that:

- Someone with the owner role in an org should be able to assign roles in the admin UI for that org (in the People admin).
- Org owners should also be able to assign multiple roles to a given individual in the admin UI for that org.
- Superadmins should have all roles in all orgs.

**Comment by sreynen** [comment]
@Anasauce can you elaborate on what you mean by only happening client-side? Were the new roles saving on the server and showing up after refresh for you? They weren't for me.
