### ISSUE TITLE
Easter Egg Invite Link

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#24]
- [ ] As a user, I can invite myself to the repo without directly going to port 8080 via a link on the splash page

**Comment by sandramchung** [comment]
So this is to workaround the current steps 12 and 13 in the Getting Started part of the README, which are:

> 12. Because Spoke is invite-only you need to generate an invite: Go to the RethinkDB data explorer at http://localhost:8080/#dataexplorer and run: r.db('spokedev').table('invite').insert({is_valid: true}). Copy the generated key.
> 13. Use the generated key to visit an invite link, e.g.: http://localhost:3000/invite/e7bcc458-c8e9-4601-8999-a489e04bd45f. This should redirect you to the login screen. Use the "Sign Up" option to create your account.
