### ISSUE TITLE
SuperUser UI for invite system.

### ISSUE THREAD

**Issue by Anasauce** [ProgressiveCoders/Spoke#240]
- As a superuser I want to be able to invite other campaigners without having to go into the backend of the app and manually change the .env variable $SELF_SUPPRESS_INVITE or manually enter an invite hash into the DB

- I still want to keep just any user from being able to access setting up an admin account

- I suggest adding a UI for the invite system to admin. Where a superuser can send a link to other campaigners they want to add

**Comment by schuyler1d** [comment]
An initial superuser that has created a organization can add others by first sending them a campaign invite link, and then upgrade their account to an admin for the particular organization. But ++ that a superadmin should have UI powers across organization visibility and access without having to dig into the DB.

**Comment by ibrand** [comment]
@Anasauce is still still a problem you encounter? II've only ever used this flow:
> An initial superuser that has created a organization can add others by first sending them a campaign invite link, and then upgrade their account to an admin for the particular organization

**Comment by Frydafly** [comment]
@ibrand Do you know if I can close this? From what I'm reading, the Supervolunteer can generally do these things now.

**Comment by ibrand** [comment]
I believe this is done!
