### ISSUE TITLE
Texter assignments change after being saved

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#244]
Texter Assignments are changing after being saved. 

Example 1: I setup Texter A with 500 texts. I save. i then open the campaign to add another Texter, Texter B. When I open the tab to assign tTexter, Texter A's assignment has changed to a larger or smaller number. I add Texter B and assign 500, then adjust Texter A's assignment back to 500. I open the campaign again to add Texter C, and Texter A or B's assignment has changed. I adjust and save. Rinse. Repeat.

Example 2: Texter D was assigned 500. 20 minutes later they message me on Slack asking if I added more texts to their assignment, or say that they're see 1048 texts, not the 500. Or they say their text disappeared.

It appears that something is happening where the assignment are not "locked in" in any way, but instead seem to change on their own, and for what appears to be arbitrary reasons. This does not appear to happen to all campaigns in a given day, just some, and for unknown reasons.

**Comment by mathemagica** [comment]
https://github.com/MoveOnOrg/Spoke/pull/262 *might* fix that/those issues

**Comment by mathemagica** [comment]
Next steps: download sky's testing csv and try to reproduce the issue locally. we are tentatively sure we fixed this on prod.
