### ISSUE TITLE
Keep texter todo list updated without significant load on database at high texter volume

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#254]
We were previously using Apollo polling on the texter todo list data query to keep it refreshed, but this caused too much database load with a high number of texters all repeatedly running the queries, so https://github.com/MoveOnOrg/Spoke/pull/253 removed that. So currently texters need to manually refresh their browser to get the latest data. Ideally we can find a better way to refresh the data without too much database load.

**Comment by sandramchung** [comment]
More context in https://github.com/MoveOnOrg/Spoke/issues/255. Some ideas: 

- implement auto-refresh for the ToDo list that doesn't hit the db every time
- restore polling, but boot texters out of the ToDo list if they leave it open for too long
- make manual refresh the obvious only choice with e.g. a manual refresh button on the ToDo list screen

**Comment by schuyler1d** [comment]
Some thoughts:
* If we have a redis/memcache layer, the generic version might be to insert between knex and the db, the same way django-cachalot works.  If knex doesn't allow that, then maybe we can "conveniently" use the rethink-knex-adapter.  My concern here is that it might be 'too' global for a bunch of queries that really need to be super-up-to-date, while focusing on the sms message queue really might be the only place in our application that exerts this much db pressure and need of freshness.
* So then maybe use redis, e.g. as an (optional) queue for 'updates'.  e.g. for each (?logged in) user, we send messages related to their assignments into the redis queue, and then the query that is polled only looks at the redis queue for updates/new messages.

**Comment by ben-pr-p** [comment]
We can do, via Redis pubsub, a new message on a new reply -> push a message to the client over websockets telling them to check for new updates?

This avoids
a) Ever checking for an update when there won't be one (polling the DB)
b) Having to store reply state in Redis / anywhere outside of the DB

Downside is maintaining a bunch of open socket connections, but this shouldn't each up too much CPU resources if these connections are mostly idle, and should still solve the problem if the bottleneck is the DB.

If this approach makes sense to people, I'll probably tackle this Monday!

**Comment by schuyler1d** [comment]
Hi @ben-pr-p I've been thinking through the same problem for a bit.  I'd like to coordinate on planning and come to consensus on a full plan that will work over-all before diving into an implementation

For that purpose, I wrote up a planning document as a PR here: https://github.com/MoveOnOrg/Spoke/pull/524

Could you read it over and comment -- feel free to just say "That's all wrong" and write up a similar counter-proposal document.  Anyway, I'd like to discuss and maybe white-board through it and once we agree we have a plan that will work, then we can get to implementing.

**Comment by ibrand** [comment]
I'm noticing that #524 is marked as merged, does that mean this should be closed @schuyler1d ?

**Comment by schuyler1d** [comment]
This is still an issue. #524 was just the plan! (It's no longer up-to-date)

**Comment by ibrand** [comment]
Closing because #207 will address this
