### ISSUE TITLE
Address database load when there are many texters in the app at once

### ISSUE THREAD

**Issue by sandramchung** [ProgressiveCoders/Spoke#255]
When we had about ~80 texters in an active campaign today, DB load was high enough to perceptibly kill Spoke performance and prevent replies from being processed. CPU was near 100% capacity and DB connections > 700.

<img width="857" alt="rds_ _aws_console 1" src="https://user-images.githubusercontent.com/5560919/30748961-29a1a5ec-9f6f-11e7-87df-112e21d9f713.png">

<img width="883" alt="rds_ _aws_console 2" src="https://user-images.githubusercontent.com/5560919/30748966-2ec8f2aa-9f6f-11e7-93cd-a26c926ad244.png">

We were attempting to process all incoming messages at once every 5 minutes, and that was failing completely under high load. We are now telling the system to loop through batches of 100 message parts at a time: https://github.com/MoveOnOrg/Spoke/pull/252 though it may not be doing that fast enough (see branch troubleshoot-prod for logging to explore this issue).
With that fix deployed, there were still far too many DB connections for the amount of messaging activity we knew was happening on the app. Checking pg_stat_activity, we found many dozens of idle copies of queries from the ToDo List. This is because were polling every 5 seconds on the ToDo list (possibly more often) to make it feel like it was updating in real-time. We're not doing that anymore:
https://github.com/MoveOnOrg/Spoke/pull/253 https://github.com/MoveOnOrg/Spoke/pull/256

<img width="894" alt="rds_ _aws_console" src="https://user-images.githubusercontent.com/5560919/30749041-5c4c98ee-9f6f-11e7-97ed-cebeec72fb71.png">

The ToDo list will still refresh on harder browser refresh or when exiting from the messaging interface. Killing polling is a temporary fix only. Long-term fix should be discussed and implemented per https://github.com/MoveOnOrg/Spoke/issues/254

**Comment by schuyler1d** [comment]
This particular issue was solved with adding some db indexes and, at least for twilio, message parts are no-longer a separate processing stage, and incoming messages are created as they come in
