### ISSUE TITLE
Use-case: texter/campaigner knowing if a cell has been contacted by another campaign 'today'

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#265]
Imagining multiple (allied) organizations using the same spoke instance but also and all using their own contact lists.

What if some campaigns, at least, are not interested in re-contacting someone if they've already been texted by another campaign (in the same org) OR

Some options:
1. an option when uploading to exclude people that have been contacted already today (even by other organizations)
2. at least a marker in the UI for a texter so they know if the contact has already been texted before

**Comment by DinahSanders** [comment]
This could violate some election laws—e.g. campaigns can't share info with political action groups as I understand it—so solution should have legal review before it advances too far in development and certainly before rollout.

**Comment by Frydafly** [comment]
For multi-tenant orgs, it could be a good feature to turn on!

Possibly if same cell phone has been contacted today by a fellow org in the multi-tenant space, maybe you see it when you set up the campaign and load the contacts, and then get the option of removing them from the list. I think it would be good to be able to decide on a per-campaign basis. Since some campaigns you don't mind if you are over-contacting someone.

**Comment by schuyler1d** [comment]
Agreed -- there are a lot of features and potential here, but this has a lot of complicating considerations -- e.g. when you want to retext affirmative responses from a previous campaign of the same day, etc.
Many multi-tenant orgs do not have over-lapping contacts (i.e. they're often, though not always, regional).
I'm also interested in cross-spoke/cross-instance APIs here -- e.g. TMC's communal contactibility program -- and thinking through how we could support this within a larger ecosystem -- though that also has equity and other un-gamification issues.

**Comment by Arique1104** [comment]
Hello,

My name is Arique (they/them) and I am the Community Manager for Spoke. First of all, thank you so much for creating this issue and for everyone’s contributions to this ticket.

I am going through all of our issues and beginning to close all issues created in 2018 or older. Your issue qualifies.

I am giving everyone one week to answer the following question: 

- **Has this issue been resolved during the subsequent Spoke Updates?**

On November 16th I will be closing this issue if:
1. There is no response
2. You respond yes

If you are reading this message after November 16th, please note that if you tag me and answer the above question, I will be happy to reinstate the issue.

**Comment by Arique1104** [comment]
This issue is considered resolved.
