### ISSUE TITLE
Allow multimedia images in texts and scripts

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#266]
Create the ability to send MMS messages with media in them.

The easiest way might be to allow a markdown-ish format in script text like `[<img url>]` which gets converted to being sent with the MMS.

More complicated options:
* A more sophisticated interface would allow image upload, etc.  
* UI could also include embedding the message, at least as a thumb or href for the Texter post-sending

**Comment by shakalee14** [comment]
trying easy implementation first.

**Comment by shakalee14** [comment]
Didn't work on this yet but will assign myself if we decided to focus on this issue in upcoming milestone.

**Comment by lperson** [comment]
I'm going to work on this.

**Comment by shakalee14** [comment]
@lperson 💯

**Comment by ben-pr-p** [comment]
Me too!

**Comment by shakalee14** [comment]
added with https://github.com/MoveOnOrg/Spoke/pull/425
