### ISSUE TITLE
Texter assignment form behavior is confusing/unpredictable

### ISSUE THREAD

**Issue by sandramchung** [ProgressiveCoders/Spoke#269]
Texter assignment form behavior can get very confusing as the campaign progress and you return to add more contacts and/or texters and/or distribute or redistribute contacts between the texters. This is at least in part because the permutations of possibilities in this form are too many to test and think through comfortably, and we're not testing or thinking through all of them yet.
Propose:
1) Writing tests for the form permutations and using those to update the texter assignment algorithm
2) Converting autosplit into a simple button that does exactly one thing: divides the assignable contacts between the listed texters as evenly as possible, regardless of how many contacts the texters have already contacted.

**Comment by sandramchung** [comment]
First stab at breaking down the permutations: https://docs.google.com/spreadsheets/d/1un4RedrEGEcm3IZKPo7Iv6Jm9rehRz9aJierJ-InEIo/edit#gid=0

**Comment by mathemagica** [comment]
- finish writing out testing permutations (0.5 day)
 - writing more tests (1 day)

**Comment by sandramchung** [comment]
Suggested breakdown of tasks:
-Finish writing out permutations.
-Clarify the assignment algorithm and UI behavior using insight based on permutations. 
-Write tests that verify that the algorithm steps and UI behavior are as designed and/or
-Write tests that verify that the results for each permutation of conditions is as expected.
