### ISSUE TITLE
Create ability to track active user count

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#276]
Using Auth0, we can use this API:
https://auth0.com/docs/api/management/v2#!/Stats/get_active_users

Otherwise we could use # of unique texters for sends in a given time window.

Tracking should support amazon cloudwatch, but also heroku metrics if such a thing exists

**Comment by sandramchung** [comment]
What temporal resolution do we need here? It looks the best we can get from the Auth0 API stats endpoint is daily login count. We could alternatively parse the response from Auth0 log endpoint to get login successes within an arbitrary time period.

**Comment by sandramchung** [comment]
Of these ideas, counting unique texters among sends and receipts in a given time window will probably give us the best figure to hold up against load on the db/service at any given time.

**Comment by schuyler1d** [comment]
so total sends per [5 minutes], total receipts per [5 minutes], total unique texters-that-sent-a-message per [5 minutes], is what i think we came to at standup

**Comment by sandramchung** [comment]
Per standup today: aim for 1 hr temporal resolution via querying unique texters in the message table, and since I've already written code to send it to cloudwatch, send it to cloudwatch.

**Comment by sandramchung** [comment]
Hmm, I heard 1 hour resolution and one query.

**Comment by sandramchung** [comment]
Manual queries documented here: https://github.com/MoveOnOrg/Spoke/blob/active-user-count/docs/TEXTER_ACTIVITY_QUERIES.md

**Comment by sandramchung** [comment]
https://github.com/MoveOnOrg/Spoke/pull/289 We can run these queries against our data warehouse to generate reports without burdening the production DB at all. Will implement cloudwatch metrics later.
