### ISSUE TITLE
Spoke perf testing framework: simultaneous users

### ISSUE THREAD

**Issue by mathemagica** [ProgressiveCoders/Spoke#278]
Context: we need a way to simulate having many texters on spoke at the same time so we can measure how well the system performs at scale without undue risk of prod breakage. Goal of these perf testing tasks is not to load test the entire system end-to-end, but be able to load test just the parts of the code we change, so that we can have some sense ahead of time whether code changes we're about to roll out will causing scaling issues. 

Using __test__/backend.test.js as an example of how to mock out the current logged in user, and https://github.com/MoveOnOrg/Spoke/blob/master/src/server/api/schema.js#L323 as an example of how to mock twilio interaction, write a test that mock logs in as a configurable number of users simultaneously, executes the test case defined in https://github.com/MoveOnOrg/Spoke/issues/277 records the observed load time to complete this test case, and prints out a report summary.

Document how to run this test on a locally run server using your local postgres database, and also pointing at the staging postgres database.

How do we know this is actually helpful? When this is working, choose an N, run the tester script with N users and monitor staging db cpu and observed page latency, and then ask mobile team to run a test on prod with N users and compare both db cpu and observed page latency to make sure our simulated test is in the same ballpark as prod.

What are we going to use this for? 1. Be able to tell the mobile team how many simul texters they can plan around onboarding. 2. be able to run this test after adding polling back in and feel confident we haven't created any new scaling problems

**Comment by shakalee14** [comment]
Closing this because this is was discussed via this project and was decided to not be a priority.

https://github.com/moveonorg/spoke/projects/4
