### ISSUE TITLE
Bug preventing campaign from starting

### ISSUE THREAD

**Issue by mathemagica** [ProgressiveCoders/Spoke#282]
Erik created campaigns 203 and 204 today and experienced the error that even after he had set up the campaign to run properly, the "run campaign' button remained grayed out, and is_started never got set to true in the DB. Sandra and I think this was introduced with https://github.com/MoveOnOrg/Spoke/pull/263/commits/bc9c9f7593bc5421850c72941d2beb12e81743ca but have not yet tested reverting it. To temporarily workaround this to get Erik started on campaign 203 we just set is_started=t. Campaign 204 still exhibits the error behavior can be used for testing.

additionally, even when is_started=t is hacked into place, message receiving is also broken. Perhaps due to clearing out jobs older than 2min which may still be valid jobs?

**Comment by shakalee14** [comment]
did we capture in errors in the logs? or was it silently failing?

**Comment by schuyler1d** [comment]
looking at campaign 204, the section that is 'incomplete' is Texters. The texter data is saved and represented in the form.  However, the texter assigned count doesn't cover all contacts.  I suspect there's an assumption somewhere in AdminCampaignEdit.jsx that all contacts must be assigned for the texter step to be 'complete' and thus startable.

**Comment by schuyler1d** [comment]
I think this commit might be responsible/related e2654fe61560627a29227ba58d18981103afcb81, but going to sort through what we *want* to happen
