### ISSUE TITLE
Bug: Cannot reply to received reply

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#283]
Bug introduced where, as a texter, I can send a first text, receive a reply, and then when trying to send a reply, receive an error screen

Notes:
- The message actually does send despite error screen

<img width="991" alt="screen shot 2017-10-04 at 9 15 34 am" src="https://user-images.githubusercontent.com/16676323/31178346-c39f21e4-a8e6-11e7-937e-ceab1d050164.png">

**Comment by schuyler1d** [comment]
https://github.com/MoveOnOrg/Spoke/commit/8bb8cbd124e42e122ee916e7ed4206bda399db64
may fix this.

**Comment by mathemagica** [comment]
Confirmed Sky's change fixes this!
