### ISSUE TITLE
Texting using keyboard "enter" button sent contacts multiple texts

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#286]
Volunteer texters who used the "enter" or "return" button on their keyboards to send text messages in Spoke reported receiving replies from individual members indicating they had received multiple texts, sometimes up to 20. This seems to be connected to a volunteer "holding down" the enter button as opposed to clicking it repeatedly, but I am not certain I can say the later with confidence.

**Comment by shakalee14** [comment]
i can reproduce this issue when i hold down enter.

**Comment by shakalee14** [comment]
holding down enter for 2 seconds sent 9 texts
