### ISSUE TITLE
Create test data

### ISSUE THREAD

**Issue by sandramchung** [ProgressiveCoders/Spoke#31]
Create shareable test database that can be used to reproduce and test issues currently in the issue queue. Maybe using faker, which is already part of the project: [How to Mock Data for Node.js Applications Using faker.js](https://hackernoon.com/how-to-mock-data-for-node-js-applications-using-faker-js-b1f4c0e78102)

Especially useful for https://github.com/MoveOnOrg/Spoke/issues/15 and https://github.com/MoveOnOrg/Spoke/issues/14

**Comment by ibrand** [comment]
@schuyler1d my understanding is that the request here is to make it easier to test things locally. Is this solved by a combination of the fake contacts for testing contact loader and fakeservice?

I'm inclined to close this
