### ISSUE TITLE
Check for wrong numbers

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#316]
Check for wrong numbers before sending messages - When it's a wrong number, it causes the following error in Twilio:

`(Error: 30005) Unknown destination handset. The destination number you are trying to reach is unknown and may no longer exist.`

**Comment by shakalee14** [comment]
I believe we can use this twilio look up api - wonder if it would make sense to implement a check after uploading contacts and then we could see how many numbers were removed from the list (currently it reports how many contacts were removed based on the `opt_out` table)

https://www.twilio.com/blog/2016/06/how-to-validate-phone-numbers-in-nodejavascript-with-the-twilio-lookup-api.html

**Comment by shakalee14** [comment]
Also FYI - if message is marked as 'undelivered' - you are still charged:
https://support.twilio.com/hc/en-us/articles/223181728-Will-I-be-charged-if-Twilio-encounters-an-error-when-sending-an-SMS-

**Comment by schuyler1d** [comment]
Also after a SMS is attempted, if the service (e.g. twilio) comes back with an `unreachable` or landline error code, then we should mark it in the system, so we don't try again.

**Comment by ibrand** [comment]
We've discussed this recently in the form of something like these incoming message handlers: #1317 except for filtering down lists within the contact importing step

**Comment by Frydafly** [comment]
Is it possible to add a message handler that checks whether a phone number connected to an outgoing text has previously been flagged as a landline or wrong number by twilio/messaging service? @lperson

**Comment by schuyler1d** [comment]
This error code is already logged in the campaign_contact record -- I think the tricky thing with logging specifically 'wrong number' to a phone number e.g. globally (rather than to a person/contact) is that it's NOT a wrong number for someone else -- so this in-particular may need to depend on an outside CRM to make business decisions about how to handle this scenario.

**Comment by Frydafly** [comment]
I think perhaps this issue might be more relevant if we shift the conversation over from wrong numbers, and towards phone numbers that show up as landlines or phone numbers that are not currently deliverable?

**Comment by schuyler1d** [comment]
maybe then worth thinking about whether to connect this to the upcoming table in https://github.com/MoveOnOrg/Spoke/pull/1917 for phone numbers independent of a particular campaign -- maybe there would be a status column e.g.

**Comment by Arique1104** [comment]
Hello,

My name is Arique (they/them) and I am the Community Manager for Spoke. First of all, thank you so much for creating this issue and for everyone’s contributions to this ticket.

I am going through all of our issues and beginning to close all issues created in 2018 or older. Your issue qualifies.

I am giving everyone one week to answer the following question: 

- **Has this issue been resolved during the subsequent Spoke Updates?**

On November 16th I will be closing this issue if:
1. There is no response
2. You respond yes

If you are reading this message after November 16th, please note that if you tag me and answer the above question, I will be happy to reinstate the issue.

**Comment by Arique1104** [comment]
This issue is considered resolved.
