### ISSUE TITLE
document security model for graphql

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#319]
explain how security is managed with graphql/apollo server functions.

**Comment by Frydafly** [comment]
hey @schuyler1d! does [this documentation](https://moveonorg.github.io/Spoke/#/EXPLANATION-development-guidelines?id=apollographql-structure-and-gotchas) suffice for this request? Or do you think there's opportunity to add more in here?

**Comment by schuyler1d** [comment]
agreed
