### ISSUE TITLE
Showing reply interface behind "sending" is confusing

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#321]
Currently when a texter sends a message, the interface briefly changes to the reply interface while the "sending..." overlay is active, before moving to the next contact. The reply interface can't be used because of the overlay, so it's not useful to update it, and a little confusing.

**Comment by sreynen** [comment]
<img width="1392" alt="screen shot 2017-10-10 at 11 22 44 am" src="https://user-images.githubusercontent.com/108645/31400594-680e58a6-adad-11e7-8692-6c3491b93bdb.png">

**Comment by arena** [comment]
This is not the case any longer 
Closing. 
(Let me know if I'm mistaken and I'll reopen)
