### ISSUE TITLE
Create button to take you to the Home Screen for Texter View

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#341]
- Currently, in order to visit the texter dashboard (home screen) while you're in the contact texting view, you have to click 'X' to return to the home screen. This should be a button.
- [ ] Create UX screen mock up for both desktop and mobile
- [ ] Implement mock up for desktop 
- [ ] Implement mock up for mobile

**Comment by arnazmursidp** [comment]
Hi! I'm a first timer, and I want to contribute to your project, so if there are any suggestions or feedbacks let me know, thanks!

**Comment by shakalee14** [comment]
Hey @arnazmursidp - glad you're interested in contributing. This is a good first client side focused issue to work on. Please remember to review the [README](https://github.com/MoveOnOrg/Spoke/blob/master/README.md) and [Contributing Guidelines](https://github.com/MoveOnOrg/Spoke/blob/master/CONTRIBUTING.md). We also have a [docs](https://github.com/MoveOnOrg/Spoke/tree/master/docs) directory that should provide more guidance.

**Comment by arnazmursidp** [comment]
@shakalee14 okay i will try to do this

**Comment by schuyler1d** [comment]
closing since #494 and #500 fixed
