### ISSUE TITLE
Spoke inconsistently fails on uploading .csv files greater than 20-25K rows

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#356]
Spoke does not allow me to upload a .csv file with greater than approx 25K rows. After clicking to upload contacts, Spoke reads the file, but does not begin the upload process. A good way to test this will be to grab a list of 30k and attempt an upload into a campaign.

**Comment by shakalee14** [comment]
I get a 502 error for this post request to the `editCampaign` endpoint - which I believe means the server doesn't respond in time to the post request which aws doesn't like (30 second rule for api gateway). 

I attempted to load a campaign locally with 77K rows while connected to the prod db and was able to successfully load it in less than 5mins.

**Comment by ibrand** [comment]
This seems to be solved at this point partially due to the addition of CSV contact loaders!

**Comment by matteosb** [comment]
For CSVs uploaded from the browser, I think the Lambda payload limit ends up being the limiting factor. I added a feature request to solve this using presigned urls: https://github.com/MoveOnOrg/Spoke/issues/1537
