### ISSUE TITLE
Admin: When Changing Teams, Pop Up Menu Doesn't Close

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#357]
- As an admin, when if I'm over two teams, I visit the corner button and see a drop down menu of teams I'm apart of. When I choose a different team (org), the view will switch to the new team (org) but the pop up modal will not close.

**Comment by shakalee14** [comment]
The user menu is rendered via this container: 
https://github.com/MoveOnOrg/Spoke/blob/master/src/containers/UserMenu.jsx

Not sure if this method is working properly:
https://github.com/MoveOnOrg/Spoke/blob/master/src/containers/UserMenu.jsx#L32

**Comment by schuyler1d** [comment]
I think this will be fixed with moving handleClose before the redirect/rerouting:
https://github.com/MoveOnOrg/Spoke/pull/472/files#diff-a3f06cdfff7f8ab0f4b25badfc621acaR40

**Comment by schuyler1d** [comment]
closing.. it was fixed.
