### ISSUE TITLE
When campaign_contact.timezone_offset is "undefined_undefined", contacts don't show

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#363]
The contacts still show up in the admin assignment interface, but not in the texter interface, so they can't be contacted. Anecdotally, this seems likely related to using zip codes.

Two problems to solve here: 1) ideally invalid values would never get added for timezone_offset, and 2) if invalid values do somehow get set, that should be made more explicit.

On part 2, currently if an invalid value gets set, it looks to an admin as if the texter isn't completing their assigned contacts, while it looks to the texter as if they have fewer contacts.

**Comment by schuyler1d** [comment]
This was resolved with this: https://github.com/MoveOnOrg/Spoke/pull/364
