### ISSUE TITLE
Automate integration tests

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#382]
We currently have unit tests with Jest and we've been doing manual integration tests by visiting a deployed copy of Spoke and clicking around to make sure specific functionality works. Something like https://www.cypress.io/ could do this integration testing automatically.

**Comment by sreynen** [comment]
https://github.com/MoveOnOrg/Spoke/tree/382-cypress-tests is a start at this, but not far enough to be useful, and currently blocked on #381

**Comment by shakalee14** [comment]
since #381 was merged, this isn't blocked anymore.

**Comment by ibrand** [comment]
Closing because Cypress was merged in, and is described in this RFC: #1494
