### ISSUE TITLE
Automatically track and update dependencies

### ISSUE THREAD

**Issue by jmcarp** [ProgressiveCoders/Spoke#392]
Some project dependencies are out of date and potentially present security vulnerabilities--see #389, #390, #391. We should use a tool like `gemnasium` or `synk` to automatically alert on outdated and/or insecure dependencies. I'd be happy to set this up if you all are interested.

**Comment by schuyler1d** [comment]
Yes, please.

**Comment by ibrand** [comment]
I know we discussed dependabot at one point but it seemed like the project wasn't ready for it. Is this something we've thought more about @schuyler1d and @jmcarp ?

**Comment by schuyler1d** [comment]
I think we need to get a lot closer to "up-to-date" versions of things (and a better test suite) before we can do this.

**Comment by schuyler1d** [comment]
I'm going to close this, as we still need several dependencies to be up-to-date before we could tackle this -- also dependabot in github semi-helps with this
