### ISSUE TITLE
receiving unicode messages fails on aws Lambda

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#393]
the twilio api fails, when there's unicode in the resonse body, because aws-serverless-sdk fails with `The header content contains invalid characters`
This is because the twilio api ALSO includes a header X-Twilio-Body which might include unicode.

Maybe we can 'turn this off' either on the twilio side or the aws-serverless-sdk side.

**Comment by ibrand** [comment]
Is this still true @schuyler1d ? If so, let's decide on whether we want to turn it off on the twilio side or the aws-serverless-sdk side to give a clearer objective with this ticket

**Comment by schuyler1d** [comment]
No!  I see successful unicode messages these days.  Closing!
