### ISSUE TITLE
Use an ORM and/or choose a single database

### ISSUE THREAD

**Issue by jmcarp** [ProgressiveCoders/Spoke#409]
We're using knex (plus rethink-knex-adapter) to talk to the database. We're also supporting both sqlite and postgres. Knex isn't a full orm and doesn't attempt to smooth over differences between sql flavors, which means we have to handle differences in our code. This sometimes leads to bugs, like in #406. We can save ourselves the effort of supporting multiple databases, and the risk of bugs, by either using a full-fledged orm like sequelize or bookshelf, and/or committing to a single database (postgres). I'm not sure what value we get from supporting sqlite, so sticking with postgres might be the simplest way to solve this.

**Comment by schuyler1d** [comment]
I think sqlite is important for an easy development environment. I wish knex was better at abstracting over different dbs than they are, but knex does support different drivers and does some minimal date transformations.

If the right ORM comes along I think we could evaluate it for the project but that would be a lot of work.  I think for now the goal should be documenting best practices on using knex in the project and maybe doing tests on both with sqlite and postgres.
