### ISSUE TITLE
Deploy to Production 

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#41]
- [x] Update README.md with production deployment steps 
- [x] Deploy to production
- [x] Confirm everything in https://github.com/MoveOnOrg/Spoke/wiki works

**Comment by sreynen** [comment]
Can't test this step yet, as we don't have a Mailgun account, so skipping for now:

> As a texter, I want an email when my texting assignment is ready (requires MAILGUN API integration)
