### ISSUE TITLE
Retry web requests on dns error

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#421]
A few places, Spoke reaches out to an outside REST api.  In those situations, platforms like aws lambda or other server environments, may timeout on DNS occasionally before the request can be made.

In that case, we should simply retry the request.

Places where we should do this:
* twilio sending: https://github.com/MoveOnOrg/Spoke/blob/master/src/server/api/lib/twilio.js#L121
* nexmo sending: https://github.com/MoveOnOrg/Spoke/blob/master/src/server/api/lib/nexmo.js#L95
* actionkit rsvp actionhandler https://github.com/MoveOnOrg/Spoke/blob/master/src/server/action_handlers/actionkit-rsvp.js

When we should do this:
Example error (redacted):
```
error: actionkit event sign up failed { Error: getaddrinfo ENOTFOUND act.moveon.org act.moveon.org:443 at errnoException (dns.js:28:10) at GetAddrInfoReqWrap.onlookup [as oncomplete] 
(dns.js:76:26) code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: 'example.com', host: 'example.com', port: 443 } { event_id: '666', page: 'aaaaaaaa', role: 'attendee', status: 'active', akid: 'XXXXXXXXXXXXX', event_signup_ground_rules: '1', source: 'spoke' } 
```

Note: we should not do this on ANY failure -- e.g. a 500 error from the server means the service is down, or the same request will probably fail.  Opinions may differ on this, and if you think that's the right thing to do (try every time), then we'll hear your argument.

**Comment by benderTheCrime** [comment]
I'm going to look into this!

starting in Node 6, moreso in Node 8 and 10, errors started to get more standard messages. I can retry on error code (`e.code`) whitelist or http status code (>299 <500) or a combination of both.

**Comment by ibrand** [comment]
Hey @benderTheCrime and @schuyler1d  I'm cleaning up our `good first issues`s and want to know if this one was completed (since it's pretty old) or if it's open for new contributors to claim!

**Comment by rpachos** [comment]
Hi @benderTheCrime, pinging again on @ibrand 's question -- are you actively working this ticket? If not, I'm thinking I'll pick up this one as my first issue.

**Comment by ibrand** [comment]
He @rpachos given the quiet on this issue, I've reassigned it to you!

**Comment by rpachos** [comment]
Hi @schuyler1d , I'm reviewing the code and want to clarify some scope/approach details:

* Do you only care about sending? For instance, the twilio class performs other calls that appear to be external and thus exposed to DNS errors:
 -- twilio.messages.create()
 -- twilio.availablePhoneNumbers("US").local.list()
 -- twilio.incomingPhoneNumbers.create()

* How do you feel about a refactor? Don't want to overcomplicate, especially given the lack of unit tests at the moment, but I'm hesitant to add retry logic within the existing `twilio.js` `sendMessage` routine being that it's already 125 lines -- it might be easier to work with if portions were broken into smaller private functions.

Also, you may want to fix the links in the description as they've been broken by the change of the `master` branch to `main` for the project.

**Comment by schuyler1d** [comment]
Hmm. I've recently been near this code and understand a bit more how it currently works.  Basically, when there's a DNS error, the message.send_status is still QUEUED or SENDING, and then there are src/workers/job-processes.js methods that are called that try again.

This may, in fact, be better than trying again within the function, because a DNS error in Lambda may indicate a bad instance -- so better to wait for a different instance to try again anyway.

In that light, I'm going to close this issue.  @rpachos I'm sorry to remove this issue after you took it up and did the research.  Please ping or `@` me on ProgressiveCodersNetwork (`@sky_moveon`) and we can find something else.  One good candidate if you're interested in twilio interactions will be followups to this PR: https://github.com/MoveOnOrg/Spoke/pull/1273 (currently in our stage-main / testing branch)
listed in aggregate here: https://github.com/MoveOnOrg/Spoke/issues/451

**Comment by rpachos** [comment]
No problem @schuyler1d, thanks for the prompt response. I'm not married to twilio interactions (actually was new ground for me) but I'll take a peek at #1273 and browse other "first issue" tickets.
