### ISSUE TITLE
Mobile Regressions on #411

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#428]
Regression found on hackathon-pre branch
Button placement regressions found on all mobile devices for this branch for both sending messages and replies. Screen shots included below

**master - send first message**
iphone5
<img width="325" alt="screen shot 2017-12-07 at 12 59 01 pm" src="https://user-images.githubusercontent.com/16676323/33730936-8e227c14-db4f-11e7-8f16-d4b40d777358.png">

iphone 6
<img width="385" alt="screen shot 2017-12-07 at 12 58 41 pm" src="https://user-images.githubusercontent.com/16676323/33730982-b135a53c-db4f-11e7-8372-4922cec21bb4.png">

nexus 4
<img width="390" alt="screen shot 2017-12-07 at 12 59 18 pm" src="https://user-images.githubusercontent.com/16676323/33731015-c570bfaa-db4f-11e7-9d0d-c76ac4dbdf9f.png">

galaxy s III
<img width="388" alt="screen shot 2017-12-07 at 12 59 27 pm" src="https://user-images.githubusercontent.com/16676323/33731037-e0cb34ce-db4f-11e7-9a6c-34c310fc4b7e.png">

**master - send replies**

galaxy s III
<img width="388" alt="screen shot 2017-12-07 at 12 59 27 pm" src="https://user-images.githubusercontent.com/16676323/33731100-0a5c37c0-db50-11e7-8175-452107078f44.png">

nexus 4
<img width="390" alt="screen shot 2017-12-07 at 12 59 18 pm" src="https://user-images.githubusercontent.com/16676323/33731103-0d95f142-db50-11e7-83b3-e6a6eaba8357.png">

iphone 5
<img width="325" alt="screen shot 2017-12-07 at 12 59 01 pm" src="https://user-images.githubusercontent.com/16676323/33731106-10732128-db50-11e7-961e-450539689b3f.png">

iphone 6
<img width="385" alt="screen shot 2017-12-07 at 12 58 41 pm" src="https://user-images.githubusercontent.com/16676323/33731118-13fd37b6-db50-11e7-91ac-236f12ae7dff.png">

**hackathon-pre - send first message**
iphone 5
<img width="409" alt="screen shot 2017-12-07 at 1 04 24 pm" src="https://user-images.githubusercontent.com/16676323/33731162-3c1480ba-db50-11e7-8a03-74e3cfb42138.png">

iphone 6
<img width="384" alt="screen shot 2017-12-07 at 1 04 39 pm" src="https://user-images.githubusercontent.com/16676323/33731185-4d0cc56c-db50-11e7-85d5-fb8925ce63a2.png">

nexus 4
<img width="381" alt="screen shot 2017-12-07 at 1 04 08 pm" src="https://user-images.githubusercontent.com/16676323/33731166-3e6ad0a8-db50-11e7-8799-3e0e70e4986f.png">

galaxy s III
<img width="396" alt="screen shot 2017-12-07 at 1 03 53 pm" src="https://user-images.githubusercontent.com/16676323/33731410-02035242-db51-11e7-85ca-58d07def7aa9.png">

**hackathon-pre send replies**

iphone 6
<img width="430" alt="screen shot 2017-12-06 at 11 40 28 am" src="https://user-images.githubusercontent.com/16676323/33731234-75608936-db50-11e7-83d1-2de694ee565d.png">

iphone 5
<img width="415" alt="screen shot 2017-12-07 at 1 15 03 pm" src="https://user-images.githubusercontent.com/16676323/33731325-be42795c-db50-11e7-8286-a76f95662348.png">

nexus 4
<img width="364" alt="screen shot 2017-12-07 at 1 14 44 pm" src="https://user-images.githubusercontent.com/16676323/33731328-c0da94f6-db50-11e7-8ace-97e76acb34aa.png">

galaxy s III
<img width="388" alt="screen shot 2017-12-07 at 1 16 30 pm" src="https://user-images.githubusercontent.com/16676323/33731424-0f9d7bb2-db51-11e7-9f7f-49e62bb8e268.png">

**Comment by schuyler1d** [comment]
https://github.com/MoveOnOrg/Spoke/pull/411/commits/7d8cd62859b4662f085912b0812a8ad240b0df6d might fix this

**Comment by schuyler1d** [comment]
based on Chrome Inspector, it looks like most mobile profiles work.  I do still see a regression on the vertical view for iPad:
![ipad_stage_spoke](https://user-images.githubusercontent.com/52117/33751016-d7497f22-dba5-11e7-98e3-712f8489e34c.png)

**Comment by hiemanshu** [comment]
I'm unable to see any of the issues you see in Chrome. Am I missing something in my setup? 

![2017-12-12-142031_407x677_scrot](https://user-images.githubusercontent.com/367605/33875435-440f542e-df48-11e7-9760-b9650588f2eb.png)


I did make a small CSS change so that the Send button lines up with the other buttons, but haven't changed anything else.

**Comment by shakalee14** [comment]
it looks like the original issues i was seeing for this issue were handled with https://github.com/MoveOnOrg/Spoke/commit/7d8cd62859b4662f085912b0812a8ad240b0df6d @hiemanshu . but nice fix!

**Comment by hiemanshu** [comment]
Cool. I'm going to make a couple more CSS changes, and push them through!

**Comment by hiemanshu** [comment]
I've fixed them with https://github.com/MoveOnOrg/Spoke/commit/74c22ef017350a2bee7d7bb752aef71121152eb2
