### ISSUE TITLE
text summary doesn't display the total send but instead the send count remaining

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#433]
Instead of going from 1/12, 1/11, 1/10 ....
It should go from 1/12, 2/12, 3,12, ...

**Comment by shakalee14** [comment]
<img width="977" alt="sendmessage_screen_shot_1" src="https://user-images.githubusercontent.com/16676323/34118810-f1faf436-e3ed-11e7-8750-a372d7200369.png">

<img width="977" alt="sendmessage_screen_shot_2" src="https://user-images.githubusercontent.com/16676323/34118817-f7a14462-e3ed-11e7-9050-b2fa18a6fc5f.png">
