### ISSUE TITLE
Spoke buttons not appearing on iPhone 6/6s and Galaxy devices

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#434]
Post deploy to prod on 12/14, buttons on bottom of the screen are no longer appearing

**Comment by ErikKirkstein** [comment]
It appears some are able to see the buttons by minimizing their screen

**Comment by schuyler1d** [comment]
![image uploaded from ios 6](https://user-images.githubusercontent.com/52117/34013953-69173f0c-e0e7-11e7-9070-a4da7c105815.jpg)

**Comment by shakalee14** [comment]
fixed and confirmed on production with commit: https://github.com/MoveOnOrg/Spoke/commit/62ed4a3c68604a0ad11a4f844445c9e1417ada7f
