### ISSUE TITLE
Campaign primary color doesn't require enough (any) contrast with text color

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#448]
As an extreme example, it's possible to set the primary color to exactly the same as the text color, making the text totally unreadable:

<img width="398" alt="screen shot 2017-12-20 at 8 53 37 am" src="https://user-images.githubusercontent.com/108645/34215671-6882079a-e563-11e7-994c-237afdfe3d50.png">

But more likely, less extreme low-contrast color options are bad for accessibility. See: https://www.w3.org/TR/WCAG20/#visual-audio-contrast-contrast

**Comment by ibrand** [comment]
@rifkegribenes and @sreynen  I'm cleaning up our `good first issues`s and want to know if this one was completed (since it's pretty old.) @rifkegribenes did you ever find an answer to your question?

**Comment by SAnschutz** [comment]
I'd love to work on this issue if no one else has claimed it yet!

**Comment by ibrand** [comment]
Awesome @SAnschutz ! I added you as the assigned person for this issue!

**Comment by ibrand** [comment]
This was completed and merged!
