### ISSUE TITLE
Cannot remove a texter who has all contacts assigned

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#449]
Steps to reproduce:

1) Create a campaign
2) Assign all contacts to a single texter, save
3) Edit the campaign texters by removing the single texter, save

Expected result: texter is no longer assigned. Actual result: texter is still assigned all contacts.

This also happens when the contacts are reassigned to a new texter.

**Comment by ibrand** [comment]
@sreynen I'm cleaning up our `good first issues`s and want to know if this one was completed (since it's pretty old) or if it's open for new contributors to claim!

**Comment by schuyler1d** [comment]
This appears to be fixed!
