### ISSUE TITLE
Migrate/Upgrade for Auth0 api deprecation

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#450]
Might just be updating a library or following:
https://auth0.com/docs/libraries/auth0js/v9/migration-guide

Email below:

Hello from the Auth0 product team,

In order to provide customers with more frequent and transparent product roadmap communications, Auth0 will now be publishing a quarterly Auth0 Roadmap Update to give you better visibility to upcoming new product features, security updates and associated feature deprecations.

⏳ Features we are improving and deprecating

We know that authentication is a critical part of your applications infrastructure, so our commitment to you is that when we replace an existing feature with a more secure and better one, we will give you at least 90 days notice to upgrade to the new one.

📔 We will offer migration guides and additional assistance, depending on the complexity of your implementation and subscription level. Details of this assistance will vary, but in general we will provide the following:

    A Migration Guide (documentation)
    A Migration How-to Webinar (recorded for all customers)
    Pre-scheduled “Migration FAQ” webinars - staffed by an Auth0 Solution Architect to answer your questions

Additionally, for our Enterprise customers, your CSM will work with you to develop a custom migration plan away from deprecated features on an as-needed basis.

    Introducing Lock 11. Deprecating Lock 8, 9 and 10
    We’re continually improving the security of our service. As part of this, we are deprecating a set of APIs (usernamepassword/login, /ssodata, /tokeninfo, /delegation) used by Lock.js 8, 9 and 10 and and auth0.js, 6, 7, 8. You should update your applications by April 1, 2018.
    We are offering two options for this update:
        Option 1 (recommended). We are moving towards a centralized login experience and are recommending this option moving forward. There are many benefits of using a centralized login experience, read more about Centralized Login here. Moving to the centralized login experience is straightforward and will simplify your code base. Read this guide to learn more about these changes.
        Option 2. If you decide you need to continue using embedded login, here are the migration guides for Auth0.js and Lock.

    Introducing Resource Owner Support for oauth/token endpoint
    We’ve introduced support for Resource Owner Password to the oauth/token endpoint earlier this year (doc). We will deprecate the current oauth/ro and oauth/access_token endpoints. Applications must be updated before July 1, 2018, when oauth/ro will become unavailable. A migration guide will be available in Q1.
     
    API Authorization with 3rd Party Vendor APIs. Deprecating Delegation endpoint
    We’re re-architecting the mechanism by which you get tokens for 3rd Party/Vendor APIs (like AWS, Firebase, etc). It now works the same as any custom API, providing better consistency. This new architecture will be available in the next few weeks and will deprecate the Delegation Endpoint. All clients must be updated prior to June 1, 2018. Formal migration guide will be available in Q1.

    Deprecating the usage of id_token on Auth0 Management API
    We’re deprecating usage of id_tokens when calling PATCH/GET /user and /device-credentials. We’ve moved to regular access_tokens and this is available today. Applications must be updated by June 1, 2018, when this functionality will become unavailable. Migration guide will be available by February 2018.

    Improved OpenID Connect interoperability in Auth0
    We’re updating the userinfo endpoint to return OpenID Connect-conformant user profile attributes. The most notable change is user_id becomes sub. This will deprecate the legacy Auth0 user profile (in userinfo and in ID Tokens). Applications must be updated to use the new user profile before July 1, 2018. Migration guide will be available in late Q1.

New Features coming in Q1 2018!

The following is the list of all new features shipping between now and the end of March 2018.

    Custom Domain Support
        What’s new: Support for custom domain names for cloud customers (e.g. foo.auth0.com => accounts.foo.com).
        Why I should care: For customers who prefer not to use “your-domain.auth0.com” as their domain name for centralized login, you will now be able to configure your own custom domain name.
        Note: This capability will be available to all Enterprise, Developer Pro and Developer customers in the cloud. The beta release is available for dev tenants today, with the final release available for production tenants early in Q1.

    New Marketing Integrations
        What’s new: Export real time identity transaction metadata to any marketing platform, e.g. Adobe Campaign, Marketo, and MailChimp.
        Why I should care: This will help Product and Marketing teams improve their own users’ experience by analyzing data to get a better understanding of user behavior, remembering user preferences, and building specific user personas.

    Auth0 Analytics
        What’s new: A powerful new way to visualize your user population and leverage first-party identity data, this is particularly useful for analyzing populations of consumer users. This feature includes pre-built reports, with the ability to filter for more fine-tuned information, such as:
            Returning users by identity provider
            Logins by device
            Logins by location
            Users by application
            Anomaly detection trends and incidents
        Why I should care: Aid decision-making, optimize registration and login forms, create unique user experiences and keep a close eye on potentially malicious activity.

    Improved Auth0 MFA offering: Guardian
        What’s new: An improved version of Guardian, which exposes our MFA API, so that you can better adapt MFA to the look and feel of your application. These new features also allow you to have multiple MFA Authenticators.
        Why I should care: Create a more seamless user experience and help users who lose or break their phone (or face a similar problem).

    Anomaly Detection: New Device Detection
        What’s new: The ability to create Rules conditional on whether this is the user’s first login from a particular device.
        Why I should care: When paired with multi-factor authentication, New Device Detection allows you to add an extra layer of security by triggering MFA when a new device is detected. It also provides a method to keep friction low for users by allowing them to shortcut superfluous authentication steps if the device is trusted.

    Password Expiration
        What’s new: A feature that will enable you to attach a password expiration time to your password policy.
        Why I should care: Enhanced security. If a user’s password is expired, all endpoints will prevent that user from logging in until the password is reset.

For our Private SaaS Appliance customers, we are sending you additional information on how your customer success team will update your PSaaS infrastructure to the new versions that include these new features.

Special reminder that Lock 11 is now available and you will need to migrate by April 1st (not an April fool’s joke 😬), as earlier versions of Lock will be deprecated on that date. The migration guides are available in the Lock 11 section above.

Thanks for your partnership with Auth0. Reach out to us at notifications@auth0.com if you have any questions or feedback. We look forward to continuing to provide you with a steady stream of improved and more secure features in the coming months!

Chris Spiek
Head of Product

**Comment by wildest** [comment]
FYI for anyone trying to get started with Spoke and Auth0 until this is fixed;
You're going to see a CORS issue in your browser console "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://xxx.auth0.com/user/ssodata. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)."

If you reach out to Auth0 support, you can request they enable the old version of the lock;
"We recently started deprecating our Legacy non standard APIs which made Lock < 11 work, the /user/ssodata is one such custom endpoint.

In order to promote adoption of our standard complaint APIs, we default to these settings being disabled on all new tenants. At the moment, we can enable these settings on you tenant which will allow you to quickly deploy these applications. However, in a long run **these APIs will be deprecated by end of Q1.**

You can read more about migration steps at https://auth0.com/docs/libraries/lock/v11/migration-guide

Please let me know if you'd like me to request enabling the legacy flags on your tenant and if you need further assistance."

**Comment by shakalee14** [comment]
Some of this was fixed with https://github.com/MoveOnOrg/Spoke/pull/483
