### ISSUE TITLE
Spoke skipping texts; sending every other initial text instead of each

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#452]
After assigning a texter X amount of texts, when clicking send to send the initial texts, Spoke is skipping over odd numbered texts.

Ex: You have 50 texts, you enter the user screen. You click "Send" and according to the counter, instead of sending 1/50. 2/50. 3/50, 4/50, 5/50 etc, Spoke is sending 2/50, 4/50, 6/50 etc.

The skipped over texts then appear as new texts to send in the to-do page.

**Comment by shakalee14** [comment]
This bug isn't necessarily even or odd - i believe it is just skipping. I can reproduce this issue locally.
