### ISSUE TITLE
Request: display last name and user ID info in Spoke texter screen

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#454]
In a live campaign, Spoke currently only displays the first name of the texter to the admin. In cases where the an org has two or ore users with the same first name, should a user request more texts, this limited amount of information prevents the admin of knowing which user is which. See the two "Naomi" users in the screen shot as an example.

![screen shot 2018-01-08 at 12 38 28 pm](https://user-images.githubusercontent.com/32142717/34683723-e6ed1a0e-f470-11e7-8c89-f2c3a57c072e.png)

By adding the last name and user ID to the texter screen, a campaign admin will be able to assign the correct user texts each time they are requested.

**Comment by JeremyParker** [comment]
@schuyler1d @shakalee14 I'd like to take a stab at this issue.

**Comment by harpojaeger** [comment]
I have a commit that solves this. Does Spoke require a last name for a texter to sign up? IOW, do I need to handle cases where `texter.lastName` is null or blank, or can I assume it will always exist?

**Comment by shakalee14** [comment]
I believe form validation with auth0 disallows someone from registering without a last name - so i don't believe you need to handle that case.

**Comment by shakalee14** [comment]
@harpojaeger Can you create a PR for this fix so we can review it/leave comments ? Thanks!

**Comment by harpojaeger** [comment]
Yup, been away from the computer. Stand by.
