### ISSUE TITLE
SuperVolunteer access level

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#455]
NOTE, this issue has some progress, but could use help (and is marked good-first-issue for that)!  If you are interested in helping with this, checkout the branch from this WIP PR: https://github.com/MoveOnOrg/Spoke/pull/476 (`super-volunteer`) and volunteer to fix *one* of the unchecked checkboxes with a comment.  When you make your PR, instead of a PR against `main`, make it against the `super-volunteer` branch.  Thanks!

Beyond texting, it should be possible to grant someone an access level at the organization level that gives them access to:
* Assign texters to existing campaigns
* Adding and editing “canned responses”
* “Incoming messages” menu
* Enforce texting hours

They should NOT have access to:
* Data exporting
* Adding and editing “Interactions”
* Campaign archiving
* Optouts menu
* Creating new campaigns

**Comment by anule** [comment]
I would like to work on this!

**Comment by shakalee14** [comment]
Great @anule !! @schuyler1d did you make any progress on this? Let's make sure @anule can plug in!

**Comment by schuyler1d** [comment]
@anule great, welcome!
The current status is at the wip pull request here:
https://github.com/MoveOnOrg/Spoke/issues/476
So if you checkout the branch there it itemizes what still needs to be done.
Happy to help get you setup if you run into any issue.

**Comment by anule** [comment]
thanks @shakalee14 ! @schuyler1d I'll take a look at the pull request and let you know if I run into any issues

**Comment by shakalee14** [comment]
Fixed with #476
