### ISSUE TITLE
Edit email notification sender name from "help" to "MoveOn texting"

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#465]
When a Text Team volunteer receives an email notification indicating their campaign is ready for texting or they have replies waiting in Spoke, the sender name is currently "help."

To ensure greater clarity for volunteers and avoid possible spam filters, I recommend we change the sender name to "MoveOn texting."

**Comment by shakalee14** [comment]
I think this is set in our 'EMAIL_FROM' config option so we can change it there and test this on wednesday @ErikKirkstein :)

**Comment by ibrand** [comment]
Closing cause this was addressed!
