### ISSUE TITLE
Push replies to texter

### ISSUE THREAD

**Issue by ben-pr-p** [ProgressiveCoders/Spoke#466]
If someone has just finished texting a list, and they are sitting on the post completion page, they have to refresh in order for "Send Replies" to pop up.

This could include:
- [ ] Push updates live to user (Send Replies pops up without requiring a refresh)
- [ ] Send the texter a push notification

**Comment by shakalee14** [comment]
https://github.com/MoveOnOrg/Spoke/issues/254
Original discussion around this issue.

**Comment by ibrand** [comment]
Closing because this is a duplicate of #207
