### ISSUE TITLE
Non-urgent - fix moment.js issue

### ISSUE THREAD

**Issue by sandramchung** [ProgressiveCoders/Spoke#47]
This keeps popping up in the backend error log: Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.

try `grep -r Date src/server/api/*` to look for places in the code that might need to be updated.

**Comment by shakalee14** [comment]
This is possibly urgent, as after switching to knex, it has trouble reading the due_by field as a date.
