### ISSUE TITLE
Remove dependences that use React.PropTypes

### ISSUE THREAD

**Issue by jparkrr** [ProgressiveCoders/Spoke#479]
I was trying to see what I could do to fix the warning:
```
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
```

Spoke's code was all updated, so the issue was dependences that are behind:

- Material-ui (I've sent a PR to update spoke https://github.com/MoveOnOrg/Spoke/pull/480)
- [material-ui-color-picker](https://github.com/LoicMahieu/material-ui-color-picker)
  - hasn't been updated, but it would be easy enough to send a PR or fork
- React-router (I've sent a PR to update spoke https://github.com/MoveOnOrg/Spoke/pull/480)
- React-formal needs to be updated to at least to 25.4
  - This package is for defining a schema and validating forms
  - They don't have a good changelog, so could be tricky to verify https://github.com/jquense/react-formal/releases
- React-apollo needs to be updated to at least 1.1.1
  - Looks like there was some work in https://github.com/MoveOnOrg/Spoke/pull/418
  - But the work is also long to complete and tricky to verify

So I won't be able to fix the warning 😢. I just wanted to document what I found.

**Comment by jparkrr** [comment]
Found a few more that might need to be updated:

- redux
- [react-async-script](https://github.com/dozoisch/react-async-script)

I ran these commands to find all (hopefully) React.PropTypes deps. You'll also see dependencies of dependencies, so you have to check what depends on it if it's not a direct dependency.
```
grep -Rl "PropTypes.*react" node_modules/
grep -Rl "React.PropTypes" node_modules/
```

**Comment by Frydafly** [comment]
@schuyler1d checking in case this is relevant given a potential React upgrade coming soon?

**Comment by schuyler1d** [comment]
i think this is mostly gone already, but will definitely be gone if/when we merge the React upgrade (AFAIK)

**Comment by Arique1104** [comment]
Hello,

My name is Arique (they/them) and I am the Community Manager for Spoke. First of all, thank you so much for creating this issue and for everyone’s contributions to this ticket.

I am going through all of our issues and beginning to close all issues created in 2018 or older. Your issue qualifies.

I am giving everyone one week to answer the following question: 

- **Has this issue been resolved during the subsequent Spoke Updates?**

On November 16th I will be closing this issue if:
1. There is no response
2. You respond yes

If you are reading this message after November 16th, please note that if you tag me and answer the above question, I will be happy to reinstate the issue.

**Comment by Arique1104** [comment]
This issue is considered resolved.
