### ISSUE TITLE
make missing timezone hours configurable

### ISSUE THREAD

**Issue by lperson** [ProgressiveCoders/Spoke#491]
This is hardcoded.  Let's make it configurable so it can be adjusted without a code change.

```
const TIMEZONE_CONFIG = {
  missingTimeZone: {
    offset: -5, // EST
    hasDST: true,
    allowedStart: 12, // 12pm EST/9am PST
    allowedEnd: 21 // 9pm EST/6pm PST
  }
}
```

**Comment by schuyler1d** [comment]
should relate a bit to `TZ` config parameter.

**Comment by ibrand** [comment]
@lperson I'm cleaning up our `good first issues`s and want to know if this one was completed (since it's pretty old) or if it's open for new contributors to claim!

**Comment by Frydafly** [comment]
@lperson @ibrand 

Seeing this change in the tests:  https://github.com/MoveOnOrg/Spoke/blob/ddd32f474461da98d6377b59e8a2f76099370543/__test__/lib/timezones.test.js#L1027 

But the documentation still says that if timezone is missing, the default TZ will be EST: https://github.com/MoveOnOrg/Spoke/blob/main/docs/HOWTO_TEXTING_HOURS_ENFORCEMENT.md#contact-zip-code

**Comment by schuyler1d** [comment]
We should document this (probably where you specify) -- but without a default TZ there's a 'default' that actually makes texting hours default to a 'narrow' range for the continental US https://github.com/MoveOnOrg/Spoke/blob/main/src/lib/timezones.js#L10-L16 (12pm EST-6pm EST).  So it's actually advantageous for national campaigns NOT to have TZ set.

That's different than 'defaults to EST' -- so docs do need update

**Comment by Frydafly** [comment]
Worked on updating the documentation to reflect this https://github.com/MoveOnOrg/Spoke/pull/1943

**Comment by Arique1104** [comment]
Hello,

My name is Arique (they/them) and I am the Community Manager for Spoke. First of all, thank you so much for creating this issue and for everyone’s contributions to this ticket.

I am going through all of our issues and beginning to close all issues created in 2018 or older. Your issue qualifies.

I am giving everyone one week to answer the following question: 

- **Has this issue been resolved during the subsequent Spoke Updates?**

On November 16th I will be closing this issue if:
1. There is no response
2. You respond yes

If you are reading this message after November 16th, please note that if you tag me and answer the above question, I will be happy to reinstate the issue.

**Comment by Arique1104** [comment]
This issue is considered resolved.
