### ISSUE TITLE
ALL_OFFSETS (used to filter timezones for texting hours enforcement) should be configurable or eliminated

### ISSUE THREAD

**Issue by lperson** [ProgressiveCoders/Spoke#492]
```
//Currently only USA
const ALL_OFFSETS = [-4, -5, -6, -7, -8, -9, -10, -11, 10]
```

The comment is not accurate, by the way, because +10 is Australia eastern time.

This is used to establish which timezones are within texting hours at the current point in time relative to configured or default texting hours.

I see no reason not to just compute this for all offsets.  It's probably a small optimization.

That having been said, if we're going to keep this, make it configurable so Spoke is portable to other regions without requiring a code change.

There are other ways to make this work without a list and without configuration, such as determining, for the current point in time, the easternmost and westernmost timezones that are within texting hours.  That way we wouldn't have 2 lists with a total of 24 timezones, which I think is probably what they were trying to optimize for.

**Comment by ibrand** [comment]
@lperson this was never done, was it?

**Comment by lperson** [comment]
@ibrand short answer: yup, it was never done.  There hasn't been a real use case for doing it in the 2 years that have elapsed since I create the issue.

**Comment by Frydafly** [comment]
Related issue: https://github.com/MoveOnOrg/Spoke/issues/491

**Comment by Arique1104** [comment]
Hello,

My name is Arique (they/them) and I am the Community Manager for Spoke. First of all, thank you so much for creating this issue and for everyone’s contributions to this ticket.

I am going through all of our issues and beginning to close all issues created in 2018 or older. Your issue qualifies.

I am giving everyone one week to answer the following question: 

- **Has this issue been resolved during the subsequent Spoke Updates?**

On November 16th I will be closing this issue if:
1. There is no response
2. You respond yes

If you are reading this message after November 16th, please note that if you tag me and answer the above question, I will be happy to reinstate the issue.

**Comment by Arique1104** [comment]
This issue is considered resolved.
