### ISSUE TITLE
Heroku Hobby Level Row Limit exceeded by zip_code table

### ISSUE THREAD

**Issue by wildest** [ProgressiveCoders/Spoke#496]
Following this guide;
 https://github.com/MoveOnOrg/Spoke/blob/master/docs/HOWTO_HEROKU_DEPLOY.md

The standard deploy now seems to have the zip_code table pre-populated with 43k rows which means a free deploy for Heroku on the Hobby level is already exceeding the 10k limit.

It might be nice to be able to seed a subset of zips perhaps through the config or just update the instructions to note the fact a hobby-basic level tier is required from outset.

**Comment by schuyler1d** [comment]
Probably the best thing to do is exclude all the zips that we get programmatically here:
https://github.com/MoveOnOrg/Spoke/blob/main/src/lib/zip-format.js#L12
So you'd filter the data here:
https://github.com/MoveOnOrg/Spoke/blob/main/src/server/seeds/seed-zip-codes.js#L21
if  `zipToTimeZone` returns a value:
https://github.com/MoveOnOrg/Spoke/blob/main/src/lib/zip-format.js#L60

(not needed for this issue, but this is where we actually use this info:
https://github.com/MoveOnOrg/Spoke/blob/main/src/workers/jobs.js#L15)

**Comment by zluo16** [comment]
I'd like to give this one a shot!

**Comment by schuyler1d** [comment]
Hi @zluo16 this will already be fixed by https://github.com/MoveOnOrg/Spoke/issues/511
(We try to mark something assigned when its being worked on)

If you are looking for a backend good first issue then maybe this one: https://github.com/MoveOnOrg/Spoke/issues/185 (or feel free to chat on progcode)

**Comment by zluo16** [comment]
@schuyler1d Sorry about that! I'll keep that in mind!
