### ISSUE TITLE
Resolve eslint errors

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#50]
https://github.com/MoveOnOrg/Spoke/blob/master/CONTRIBUTING.md says new PRs should have no lint errors, but there are a lot of existing lint errors, so currently every PR shows lint errors. Let's resolve all the current errors so we can start using lint as a basic check on new PRs.

**Comment by shakalee14** [comment]
Resolved --> https://github.com/MoveOnOrg/Spoke/pull/53
