### ISSUE TITLE
Add tests for React components

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#503]
There are some tests for some components, but there is more work to do:
src/components/AssignmentTexter.jsx
src/components/CampaignBasicsForm.jsx
src/components/CampaignContactsForm.jsx
....and more!

See PR  #478 for some progress.

**Comment by solpark** [comment]
I would like to take this issue!

**Comment by shakalee14** [comment]
Great @solpark !!

**Comment by shakalee14** [comment]
no we haven't - we should discuss it! is this a testing suite?

**Comment by nathanhinish** [comment]
In particular, the Lonely Planet demo uses the "knobs" plugin. This is the plugin that allows you to change prop values on the fly.

https://lonelyplanet.github.io/backpack-ui/

**Comment by solpark** [comment]
Hi everyone! I'm sorry I haven't been very active on this issue so far. I just got bogged down recently with my other responsibilities. I would love to work on this issue eventually, but I completely understand if someone else wants to take this to get this finished earlier on!

**Comment by ibrand** [comment]
Closing this issue in favor of #1212 which gives the full checklist of components that need tests. @solpark and @nathanhinish if either of you are interested in jumping back into Spoke work, head to that issue and pick a component to test 🎉
