### ISSUE TITLE
Add New Logo and Message to Login/Sign Up Page

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#505]
**Issue:** Integrate logo and remove `We are currently in private beta.`

**More information:** 
New Logo: 
![spoke_logo](https://user-images.githubusercontent.com/16676323/36105008-8b4fef00-0fe1-11e8-893c-a58786d1970c.png)

**New Message** (remove We are currently in private beta):
Spoke is a new way to run campaigns using text messaging.
Login and get started

Currently logged out home page looks like this:
<img width="1187" alt="screen shot 2018-02-12 at 10 44 07 am" src="https://user-images.githubusercontent.com/16676323/36105185-00ad11c4-0fe2-11e8-97f2-fe55e88372e7.png">

**Comment by zluo16** [comment]
Hey Shaka! I'd like to take a crack at this issue.

**Comment by zluo16** [comment]
Should I keep the green box green or should I try and match it with the new color?

**Comment by shakalee14** [comment]
Let's keep the green for now since it's throughout the app! Thanks @zluo16

**Comment by shakalee14** [comment]
Fixed by @zluo16 with https://github.com/MoveOnOrg/Spoke/pull/514
