### ISSUE TITLE
OSDI List Import

### ISSUE THREAD

**Issue by ben-pr-p** [ProgressiveCoders/Spoke#507]
Like the database warehouse option, we should implement the [OSDI list exchange](https://opensupporter.github.io/osdi-docs/list_exchange_profile.html) inside of Spoke. 

Then, in addition to being able to upload contacts as a csv, you should be able to browse a modal that has lists from an external CRM, and select one to import for a campaign.

This would enable integrations with ActionNetwork, and other CRMs I end up implementing as part of [this project](https://github.com/justicedemocrats/osdi-proxy).

**Comment by joemcl** [comment]
@ben-pr-p this would be so handy, cc: @codygordon @j-ro @deasterdaywfp

**Comment by ibrand** [comment]
Closing because we implemented [contact loaders](https://github.com/MoveOnOrg/Spoke/blob/main/docs/HOWTO-use-contact-loaders.md) that allow for bringing in contacts from all sorts of different sources with some configurations
