### ISSUE TITLE
Make it so that when you text 555-555-5555, it responds with a message

### ISSUE THREAD

**Issue by ben-pr-p** [ProgressiveCoders/Spoke#508]
This would be useful for development, since you can develop response functionality without setting up Twilio!

**Comment by shakalee14** [comment]
we do have some functionality where you can fake reply -->
/admin/org_id/campaigns/campaign_number/send-replies

then there's an interface for sending replies :)

**Comment by ben-pr-p** [comment]
Oh great! Thanks!

**Comment by schuyler1d** [comment]
You can also set up fakeservice as the default_service and then you don't have to setup twilio at all.  

There's still maybe something compelling to the autoreply for fakenumber testing, but we should probably document whats there better
