### ISSUE TITLE
Remove gearshift.co references

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#51]
Spoke was originally a project of gearshift.co and the codebase still has a lot of references to that. Now that it's open source, let's replace those references with more relevant links and email addresses.

**Comment by sandramchung** [comment]
Includes https://github.com/MoveOnOrg/Spoke/issues/46

**Comment by sreynen** [comment]
Related, also need to remove references to "Axle Factory", the company name.
