### ISSUE TITLE
Adjust "revisit convos" Spoke tool to capture only convos instead of all texts threads/ name & color change request

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#533]
1. Currently, the new "revisit convos" feature in Spoke houses every open message thread that is not an opt out.

Example: I send 500 initial texts, all 500 initial texts message threads are then housed in "revisit convos"

Since not every initial text is responded to... 

Suggested change: Have "revisit convos" house only messages that were both replied to by a contact and a texter. This will make the tool more user-friendly for texters, where instead of having to search through all threads, only the threads which were back and forth conversations between contacts and texters would be housed in  "revisit convos"

2. if possible, can we adjust the name to "convo history?" 

3. Notifications appear in green circles just like "SEND FIRST TEXTS." Could we change it to yellow or grey?

**Comment by ErikKirkstein** [comment]
We're going to hide the "revisit convos" button until adjustments are completed.

**Comment by shakalee14** [comment]
Fixed with #542
