### ISSUE TITLE
Custom canned responses added by texters not saving

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#535]
When a texter enters the canned response menu, it provides the option to draft and save your own custom canned response(s). 

Currently, when you add a custom canned response, Spoke does not save the message in your canned responses.

It would be great to have Spoke save these custom canned responses.

**Comment by shakalee14** [comment]
@ErikKirkstein - it seems like you can save the canned response. It just doesn't save until you refresh the page. I just did the following steps:

Click on 'canned responses' while on a contact as a texter, click on 'add new', fill out the form and click save. Then it doesn't seem to show up in the menu until I do a hard refresh.

**Comment by shakalee14** [comment]
Think this is resolved.
