### ISSUE TITLE
make tests work with latest jest dependencies

### ISSUE THREAD

**Issue by lperson** [ProgressiveCoders/Spoke#544]
#478 changed the versions of jest, jest-cli and babel-jest in package.json.  

Running jest did not work with the newer versions.

The changes in #543 roll back the versions so tests run.

The purpose of this issue is to make the changes necessary to ensure that the tests run with the latest possible jest, jest-cli and babel-jest.

**Comment by ibrand** [comment]
@lperson is this still true?

**Comment by lperson** [comment]
@ibrand you can close this.
