### ISSUE TITLE
Create background process that syncs redis writes to db

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#556]

**Comment by ibrand** [comment]
@schuyler1d does this need to be done still? It has a really vague description, so if it does, we should either flesh it out or close it and make it a bulleted sub task of something else

**Comment by schuyler1d** [comment]
I don't think this process is necessary of we eliminate sufficient read pressure on the database -- ie we should start with writing to the db.

Reads/syncing in redis are complex enough, so this would blow way past our complexity budget
