### ISSUE TITLE
Allow for direct download of campaign export (when size isn't too big)

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#563]
When messages for a campaign are less than ?10000 by default ,with some process.env.SYNC_EXPORT_MAXROWS option to change that, then clicking the the 'export' button should synchronously generate the export and return the file from the request.

relevant files:
`src/containers/AdminCampaignStats.jsx` is where the export button is triggered
`src/server/api/schema.js` is where the rootMutation exportCampaign is called (through graphql)
`src/workers/jobs.js` is where the exportCampaign method is that generates the file.

Probably the best strategy would be to change the jobs.js::exportCampaign to be able to return the filedata directly (given some argument), when it would not save to s3 or email.
Then you would need to make a non-graphql view (probably in api/server/index.js that takes the campaign_id and (after checking privileges), runs the worker method directly and returns the file directly.
Then, provided the right row-count (which AdminCampaignStats already has, if it makes the threshold, then something 'redirects' document.location directly to the download link.

There may be some better graphql way to receive filedata within the protocol directly -- that should probably be researched (briefly) to see if it's easy.  If so, then the download data should be in schema.js itself.  Otherwise, see the above strategy.

**Comment by joemcl** [comment]
Thanks so much @schuyler1d . @ben-pr-p @shakalee14 @schuyler1d - is there a standard URL which gets sent by e-mail for a requested Export that you can share, anonymized of course, which I could tweak with our instance and campaign number settings, and that would allow me to pull up the data in a requested campaign Export?

**Comment by schuyler1d** [comment]
I don't think it would be the URL that's in the email since that one will be in the s3 bucket (by that method).

you need to create a separate `app.get('/....')` in src/server/index.js

**Comment by joemcl** [comment]
So here's a question - Export should work on Heroku Spoke instance with mailgun enabled and set up correctly right. So we don't have an S3 bucket. Does an Export email not just point to a URL to retrieve the export data from our Heroku  instance?  Sorry if I'm being dense.

**Comment by schuyler1d** [comment]
Looks like it log.debug's the csv to the console:
https://github.com/MoveOnOrg/Spoke/blob/main/src/workers/jobs.js#L546
dur.

**Comment by ibrand** [comment]
I'm cleaning up our `good first issues`s and want to know the status of this one since it's pretty old. @joemcl or @schuyler1d has anything changed with this issue since it was written?

**Comment by joemcl** [comment]
@ibrand @schuyler1d @deasterdaywfp yeah this is old. I still think direct download would be handy, and that this Issue should be kept open, but it's definitely not the first or second or third feature request or problem I'd ask someone with the skills to tackle. I also have no idea what it would take to implement. My enthusiasm then, which is less so now, was because Relay, which we had been using primarily in 2017, has direct download of an export in the Admin UI.

**Comment by joemcl** [comment]
> Looks like it log.debug's the csv to the console:
> https://github.com/MoveOnOrg/Spoke/blob/main/src/workers/jobs.js#L546
> dur.

And @schuyler1d if this is the case - then a user with access to the console could get to that directly of course.

**Comment by schuyler1d** [comment]
a direct link is available now when redis caching is enabled
