### ISSUE TITLE
Cache user.id_token and use it for auth

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#566]
Using branch redis-auth, let's take another step in the [caching plan](https://github.com/MoveOnOrg/Spoke/blob/redis-plan/docs/HOWTO-scale-spoke-plan.md)
by storing user data for the session in cache and load it from there when possible

 - [x] load and save user.is_superadmin, user.id, user.first_name by auth0_id
 - [x] clear it when logging out
 - [x] move `User.filter({ auth0_id: id})`  call in auth-passport.js to cacheable-queries.js

**Comment by shakalee14** [comment]
fixed by #572
