### ISSUE TITLE
Ability to assign texters to specific contacts based on an uploaded column

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#570]
If texters should be assigned based on contact features like 'turf', language, or other options.
There should be a specific column name called `texter_id` or `texter_email` that will default assignments for that texter if they are assigned.  Other texters should not be assigned any contacts that have those column values set.

To implement this:
1. You should probably document the `texter_id` and `texter_email` columns in this widget: https://github.com/MoveOnOrg/Spoke/blob/main/src/components/CampaignContactsForm.jsx#L223-L244
2. There are two approaches to saving the data.  One would be to let texter_id and texter_email just stay custom field data.  The other would be to add a column in the `campaign_contacts` table.  That would mean you would edit these two files:
* update the model https://github.com/MoveOnOrg/Spoke/blob/main/src/server/models/campaign-contact.js
* add a migration https://github.com/MoveOnOrg/Spoke/blob/main/src/migrations/index.js
3. The current assignTexters method is here: https://github.com/MoveOnOrg/Spoke/blob/main/src/workers/jobs.js#L237 However, it might be easier just to make a separate method and then in the UI of texter assignment have a button that says 'Assign texters by texter_.. column'.  That widget would be here: https://github.com/MoveOnOrg/Spoke/blob/main/src/components/CampaignTextersForm.jsx but then you'll need to make a new 'mutation' -- i.e. an apollo api point.  If you do this, you'll need to work in [schema.js](https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/schema.js#L207)

If you want to implement this, it is probably good to describe your plan a bit and then we can give you some more guidance.  Or -- you can just dive in and set it up how you want!

**Comment by ibrand** [comment]
@schuyler1d what's the status of this one? Is this at all assisted by schema changes in v5.0?

**Comment by schuyler1d** [comment]
No progress. Don't know the priority of this

**Comment by Frydafly** [comment]
Following up to see if there's been any progress on this issue? Since there's been dynamic assignment and a few other changes to texter assignments since this issue was raised
@schuyler1d

**Comment by schuyler1d** [comment]
No progress.  I think unless we find an org that's interested in this, then we should consider closing. While interesting, assignment strategies have shifted to dynamic assignment which has greatly reduced the need to manual assignment of any kind. The easiest guidance would be to say "Create two campaigns -- one for spanish and other for english (probably a good idea for the script anyway!)" and then tell different texting groups to join one or the other campaign depending on what kind of texter they are.

**Comment by Frydafly** [comment]
Closing for now due to dynamic assignment shifting the need for any manual assignment, which this issue is suggesting.
