### ISSUE TITLE
Cache Texter Assignment and Campaign Contact Info

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#573]
Based on this [plan](https://github.com/MoveOnOrg/Spoke/blob/redis-plan/docs/HOWTO-scale-spoke-plan.md#server-side-optimization), we need to implement updateAssignments and save the campaign contact info. The preliminary goal is to just dump this data into the cache. 

Upon 'start campaign' call `if (r.redis) {...` should call a general method which:
 - [ ] loads in `contactinfo-<contact_cell>-<message_service_id>`
 - [ ] `newassignments-<texter_id>-<campaign_id>` for non-dynamic campaigns
 - [ ] `dynamicassignments-<campaign_id>` for dynamic assignment campaigns
 - [ ] `campaign-<campaign_id>` with campaign data needed when texters call getCampaign or getTodos or whatever.

Make sure you include any data that is needed for texter API calls somewhere, and if there's something missing flag it here, or implement something to save that data as well.

**Comment by schuyler1d** [comment]
contact info was cached.  We decided against caching assignment info because the assignment structure is too complex
