### ISSUE TITLE
Want option of opting out without a message

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#577]
Occasionally opting out without a message is called for. 

It would be good to allow opt-out without having to send a message.
This issue is probably entirely client-side.
In src/containers/AssignmentTexterContact:handleOptOut you'll notice that it sends a message and then createOptOut, etc.

We should have an additional button "Opt out without sending message" or something similar in the interface which createOptOut but without sending a message. Alternatively we could document that if no message content is included, then we don't send a message, but still opt them out.

**Comment by shakalee14** [comment]
more discussion here: 
https://github.com/MoveOnOrg/Spoke/issues/599

**Comment by joemcl** [comment]
Thx @shakalee14
