### ISSUE TITLE
OSDI record_attendance action handler

### ISSUE THREAD

**Issue by harpojaeger** [ProgressiveCoders/Spoke#596]
Action handlers need to expose `displayName`, `instructions`, `available` and `processAction` methods (see https://github.com/MoveOnOrg/Spoke/blob/main/src/server/action_handlers/actionkit-rsvp.js).
An OSDI `record_attendance` handler would enable automatically RSVPing contacts to VAN, AN, etc. events based on an external ID uploaded in the campaign contacts CSV.

**Comment by harpojaeger** [comment]
This is based on a discussion at Prog. Hack Night tonight. I'm planning to write this handler in June. Any notes or suggestions are welcome in the meantime!

**Comment by harpojaeger** [comment]
This might also involve requiring columns in the CSV for a _contact's_ external ID, e.g. VANID, to ensure accurate syncing.

**Comment by joemcl** [comment]
Hey @j-ro @deasterdaywfp @codygordon this would be really cool to have...  thanks @harpojaeger!

**Comment by joemcl** [comment]
@harpojaeger Action Network only needs email as a unique ID..

**Comment by joemcl** [comment]
But @harpojaeger being able to send first, last, zip,cell, an external voter ID to AN as well would be *really* handy

**Comment by harpojaeger** [comment]
Hmm, I think OSDI requires an email address in any representation of a person, but you can also do `system_name:id` fields. Not sure which we'd need here. But yes, the notion is for this module to be able to talk to any OSDI API.

**Comment by j-ro** [comment]
OSDI requires no fields -- every field in the spec is always optional -- but certain implementing servers will require certain fields in their implementation (Action Network requires email address, for example).

**Comment by harpojaeger** [comment]
Good to know.

**Comment by harpojaeger** [comment]
TODO: figure out if VAN generates a signup-confirmation email when someone is RSVPd using this endpoint. This function might be of limited utility to a campaign if not.

**Comment by harpojaeger** [comment]
Also consider whether this action handler should manage the case where a person is in Spoke but not in the target database (i.e. phone numbers were collected and uploaded directly into Spoke without an external ID, so the action handler can't match them).

**Comment by harpojaeger** [comment]
OSDI options (API key, what type of system it is [this might be necessary to handle different platform's differing implementations of the OSDI spec], base URL or whatever) should be configurable on a per-organization basis.

**Comment by joemcl** [comment]
Hey @j-ro - Action Network doc info says 
> Action Network can send event RSVPs to VAN as signups. Set up the connection here, and from then on, when you create events in Action Network you can enter a VAN ID for each, after which we will send all subsequent RSVPs to the corresponding VAN event as signups using VAN's OSDI-compliant API.

which uses the record_attendance action handler right, it's just not spelled out by VAN at https://developers.ngpvan.com/osdi#osdi that VAN supports record_attendance, is that it?

**Comment by j-ro** [comment]
VAN's events implementation is undocumented.

**Comment by harpojaeger** [comment]
Well, that throws a slight wrench in my plans – I thought VAN supported `record_attendance`. Guess I'm writing a VAN-specific attendance integration then, not an OSDI one (at least to start off with)!

**Comment by j-ro** [comment]
They do, it's just undocumented. Try it out, and you can see event endpoints on the AEP.

**Comment by j-ro** [comment]
Though there are some VAN-specific wrinkles, in the shift/role/etc..., again on the AEP and discoverable in the browser.

**Comment by harpojaeger** [comment]
Ah, interesting.

**Comment by joemcl** [comment]
Hey @harpojaeger - you should request a VAN developer API key on its developer site, so you can use it's sandbox instance. As well, you should ask the campaign to request an API key for it's live Votebuilder instance for you to use. FYI, I've also used curl to get info for role ID etc for test VAN events created in both the sandbox and a live Votebuilder instance.

**Comment by joemcl** [comment]
Yo @shaisachs some useful stuff that @harpojaeger is doing here. Any help for him is much appreciated. Can VAN update it's OSDI documentation? Would be really useful.

**Comment by joemcl** [comment]
In terms of relative ease, speed and immediate utility to a campaign - I'd start with sending Event RSVPs from a test Spoke campaign to an AN group test Event, and test that. Then, sending those RSVPs from AN to a corresponding test Event in a VoteBuilder My Campaign instance. After that, sending Event RSVPs directly to Votebuilder My Campaign.

**Comment by harpojaeger** [comment]
@j-ro I've been messing around with VAN's `record_attendance_helper` but haven't been able to solve some persistent errors on the VAN-specific fields (role, status & shift), and I haven't found anything on the AEP about the schema that endpoint expects. If you know of any other implementations of this I could use as a reference, I'd certainly appreciate a pointer!

**Comment by j-ro** [comment]
Here's the code that translates from VAN's proprietary API to the OSDI service: https://github.com/NGPVAN/osdi-service

**Comment by ibrand** [comment]
Closing due to VAN contact loaders (#1457) and action handlers (work in #1538) already being implemented
