### ISSUE TITLE
OSDI record_canvass_helper action handler

### ISSUE THREAD

**Issue by harpojaeger** [ProgressiveCoders/Spoke#597]
An OSDI `record_canvass` handler would connect conversations in Spoke to, e.g., survey questions in VAN.

Ultimately, this will entail updates to the database model for questions to accommodate an `external_id` for both questions and responses (see, e.g. https://developers.ngpvan.com/osdi#people-post-people--personid--record-canvass-helper).

**Comment by harpojaeger** [comment]
Also generated from a discussion at Prog. Hack Night. This is a more involved update than #596. To be production-ready, the questions UI would need to expose the `external_id` fields for editing, or, even better, use the OSDI questions collection GET endpoint (https://opensupporter.github.io/osdi-docs/questions.html#scenario-retrieving-a-collection-of-question-resources-get) to let the user graphically map the desired question into the script somehow.

**Comment by joemcl** [comment]
@harpojaeger really cool, cc: @deasterdaywfp @codygordon @j-ro

**Comment by harpojaeger** [comment]
I mostly created this issue to keep notes for myself on what this feature will ential, but I do want to build it (I think #596 would come first).

**Comment by harpojaeger** [comment]
When creating a new campaign, present the user with an option to import survey questions from an OSDI instance, and then automatically create questions on the Spoke script that map to OSDI questions.

**Comment by harpojaeger** [comment]
The quick-and-dirty version of how this works: 1) at campaign creation, give user a button that says something like "fetch OSDI questions" or whatever. 2) clicking the button fetches the questions. 3) probably provide some search/filter functionality to make it easier to find the desired question. 4) user can select a question and it's added into the script, along with the various question and response IDs necessary for an action handler to send responses back to the OSDI system.

**Comment by harpojaeger** [comment]
In order to map questions to OSDI survey questions, I need to store the question ID and response ID somewhere in the interaction steps. I can see three possible ways of doing this:

1. Use the question and response IDs as the interaction step IDs in Spoke. This is a bit hacky. It entails creating a `mapQuestion` function that, given an OSDI question object, creates new interaction steps and sets their IDs accordingly (probably entailing slight modifications to the current `addStep` function [here](https://github.com/MoveOnOrg/Spoke/blob/main/src/components/CampaignInteractionStepsForm.jsx#L64-L74), perhaps to add a default `newStepID` param or the like – it would be backwards-compatible).
**Pros of this approach**: Little changes to existing architecture, no DB schema updates.
**Cons of this approach**: There might be other parts of the app that depend on the interaction step IDs being formatted a particular way. Conceptually, this is a misuse of an existing field, which makes me nervous.

2. Creating new columns on `interaction_step` to hold these values (probably `osdi_mapped_question` and `osdi_mapped_response`).
**Pros of this approach**: Cleaner and less hacky.
**Cons of this approach**: Schema updates are involved. Also requires changes to some GraphQL mutations.

3. Creating a new table, `osdi_interaction_step_mappings` or the like. Similar to the `user_organization` table, this would map interaction steps to OSDI objects by ID.
**Pros of this approach**: Cleanest of the three. OSDI data is nicely hidden away from the rest of the app, which is consistent with this being an optional module, not a core application feature. New queries and mutations can be written to handle this data without needing to modify existing ones in place.
**Cons of this approach**: None that I've thought of so far.

Right now, 3 is the best option in my estimation.

**Comment by harpojaeger** [comment]
My intention at the moment is to have questions that are imported from OSDI be uneditable, or at least clearly indicate that changes made to their wording won't sync back to VAN, so that the OSDI system is the single source of truth.

**Comment by schuyler1d** [comment]
hm, so then the client needs to know if the script is editable.  In that case, I might lean toward 2 with three columns:
`source`, `external_question_id`, `external_response_id` -- and for you, source='osdi:<originSystem>' or something.

**Comment by harpojaeger** [comment]
Right, I guess adding new columns to an existing table has the advantage of keeping us at one query for a given interaction step, and still providing the information needed to render elements as editable or uneditable.

**Comment by harpojaeger** [comment]
Two questions that emerge for me based on the idea of a `source` column: in what other scenarios would this be used? And are there OSDI best practices in terms of terminology or how to store external identifiers here? Maybe that's a question for @j-ro.

**Comment by j-ro** [comment]
I think generally when you do sync (say sync of people) you'll want to store the remote's ID for the resource on the local and store the local's on the remote, but for different resources like this you may have different scenarios.

**Comment by harpojaeger** [comment]
AFAICT, I don't think there's any added value to sending Spoke interaction step IDs into an OSDI system at this point.

**Comment by j-ro** [comment]
For questions probably not, and it really only matters in the sync scenario, when you're trying to keep a record in sync and changes may happen on either side.

**Comment by harpojaeger** [comment]
@schuyler1d it looks like action handlers get the question response and interaction step objects – I'm assuming fields I add to those in the DB can be included in the queries? Want to make sure I'm not committing to a structure that will be hard to work with when I get to the point of actually making the OSDI API requests (which will entail a new action handler).

**Comment by harpojaeger** [comment]
Also @schuyler1d how does the `answer_actions` column work? Do I need to be setting that in the question-mapping function in order to invoke the right action handler down the line, or is that set after-the-fact somehow?

**Comment by harpojaeger** [comment]
Answering my own questions: yes, I can make those fields available to action handlers. Now I know how the `answer_actions` column works, and I will soon teach the question mapper to set it programatically when creating questions & responses.

Here's another cool idea, @schuyler1d: since we already use an env to enable or disable certain action handlers, I'll make visibility of the OSDI settings section conditional on that same env! All a site admin has to do is add `osdi-survey-question` to `ACTION_HANDLERS`, and the config options will be exposed to site owners. Such DRY. Very clean. Wow.

**Comment by harpojaeger** [comment]
(don't mind me, just getting myself excited about cool features.)

**Comment by harpojaeger** [comment]
(don't mind me, just getting myself excited about cool features.)

**Comment by schuyler1d** [comment]
I guess my flag on combining the settings is that stops me from setting the OSDI details for an org as a tech admin and enabling the actionhandler for my campaign admins to use.

I think you're still focusing on the use-case of an ADMIN being the same as the system admin of the site and the org.  In many orgs, those are very different people.  Even when they are the same, the setup for environment variables, etc is a single thing....

**Comment by harpojaeger** [comment]
Right, but setting the OSDI details themselves as envs prevents different organizations on the same Spoke instance from talking to different OSDI systems, which seems like a desirable feature.

**Comment by Frydafly** [comment]
checking in @harpojaeger & @schuyler1d whether the VAN integration & ActionNetwork action handlers resolve this issue?

**Comment by schuyler1d** [comment]
This should be resolved with https://github.com/MoveOnOrg/Spoke/pull/1667 which was merged.  Any remaining features should probably be separate bugs that target what additional changes are needed.
