### ISSUE TITLE
In admin panel, have Spoke show amount of unassigned texts by Spoke campaign 

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#604]
Currently, a Spoke admin must click on a campaign, click on edit, then click on "texters" in order see how many texts are left within the campaign.

To ensure a Spoke admin and volunteer superadmin can more quickly and efficiently assign texts, it would be ideal if Spoke showed the amount of texts that remain in each campaign in the admin panel, and would change dynamically as texts are sent out from that campaign.

Attached is a screen shot of the current admin panel. An example of where this feature could appear would be right next to where it says "unassigned texts" next to each campaign title.
![screen shot 2018-05-29 at 1 34 54 pm](https://user-images.githubusercontent.com/32142717/40675287-4d06d094-6345-11e8-8b3a-77638a4b3bf5.png)

**Comment by yolfer** [comment]
+1

**Comment by ibrand** [comment]
This was completed in work done in #1508 @yolfer !
