### ISSUE TITLE
Integration of Test Client

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#610]
SauceLabs and/or BrowserStack

**Comment by cp4r3z** [comment]
See my comment in the PR #647 about secure strings.

**Comment by cp4r3z** [comment]
Seems that loading multiple .env files would be a nice solution to the .env "override" but that was introduced in a later version of Foreman
https://github.com/strongloop/node-foreman/blob/e4d9e4316bd56a53cf09488d05249c0b4819fbf9/CHANGES.md

**Comment by cp4r3z** [comment]
Before this is Done, let's remember that I should update the badge so it's not pointing at my SauceLabs runs
