### ISSUE TITLE
Make Auth0 optional -- regular user/pass login

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#626]
Auth0 does some decent user/pw management, but the API keeps changing and it's a large burden and stumbling block for new developers getting the project up and running.

Instead there should be some option that sets up a login for the super-user at the beginning on start, and then allows users to set a user/pass just like updating their other account vars.

However, we should also maintain backwards compatibility and support Auth0 by default.  There would be an env variable that changes auth to use the new setup.

 - [x] Setup env variable AUTH_BACKEND='local' (if not set or if it's 'auth0' it falls back to Auth0)
 - [x] Modify [src/server/auth-passport.js](https://github.com/MoveOnOrg/Spoke/blob/main/src/server/auth-passport.js) to support both and do the right password testing.
 - [x] Load/config the above appropriately in src/server/index.js
 - [ ] Setup/switch the registration screen -- probably replacing the auth0 'booting' here (https://github.com/MoveOnOrg/Spoke/blob/main/src/server/middleware/render-index.js#L27) conditional on AUTH_BACKEND value
 - [ ] Probably adapt the [UserEdit.jsx container](https://github.com/MoveOnOrg/Spoke/blob/main/src/containers/UserEdit.jsx) for a registration view when appropriate.
 - [ ] Do something on first run, when there's no accounts -- sort of a default registration screen
 - [ ] Document the other backend and setup, and possibly make it the default suggested setup for development environments.
 - [ ] Move Auth0 docs to someplace more appropriate than polluting the README file.

**Comment by schuyler1d** [comment]
see PR for progress.

**Comment by ibrand** [comment]
I believe this is fully implemented since I've used local login before! If I'm wrong and this should be re-opened go ahead
