### ISSUE TITLE
Update Deploy to Heroku in docs to add detail re: AWS S3 bucket, Bucketeer, Mailgun 

### ISSUE THREAD

**Issue by joemcl** [ProgressiveCoders/Spoke#637]
Add text and detail to Deploy to Heroku doc in docs to walk new deployers through adding/connecting an AWS S3 bucket, which is necessary for Exports to work. One way is to add the Bucketeer add on in Heroku to set up an S3 bucket. 

Mailgun can be added in Heroku as well, and is necessary to set up to receive emails pointing an admin requesting an export to the AWS S3 link to download.

**Comment by harpojaeger** [comment]
@shakalee14 am I right that the minimum necessary envs to send email are the `MAILGUN_` ones, plus `EMAIL_FROM`? If so, I can probably whip up this documentation in 30 minutes, having just done it a few days ago.

**Comment by harpojaeger** [comment]
(Mailgun config/DNS setup is a separate part of the docs, and is also very simple.)

**Comment by shakalee14** [comment]
@harpojaeger - you need to include aws vars in order to send an export campaign link also - which is why people are mostly interested in emailing.

https://github.com/MoveOnOrg/Spoke/blob/8a7fc3313496e65099d325eade4cee76dfc154d4/docs/REFERENCE-environment_variables.md

**Comment by harpojaeger** [comment]
Oh right. Okay, I can write the docs for this - feel free to assign to me
if you want.

**Comment by joemcl** [comment]
thanks @harpojaeger !

**Comment by joemcl** [comment]
Thanks @harpojaeger.

**Comment by harpojaeger** [comment]
The PR hasn't been merged. Ultimately, it's up to @shakalee14 how to handle this, but the general rule is not to close issues until the PR has been acceptance tested and merged.

**Comment by shakalee14** [comment]
This was merged --> https://github.com/MoveOnOrg/Spoke/pull/652/files - so I believe this is safe to close.
