### ISSUE TITLE
Client-side cache-friendly calling

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#641]
Last changes client-side are these:
* git df 49f59a525de524f13dc15d24f7612c67d511abf9..8abfe56e63ed35eae549705aa3f8ced8061f8555
* Need to revisit this branch: decoupling-contactinfo
* and/or figure out what to do relative to the above one.

Also need:
 - [ ] Look for 'emptyQueue' property from https://github.com/MoveOnOrg/Spoke/blob/redis-plan/docs/HOWTO-scale-spoke-plan.md#workflows-using-data-structures in getNew

**Comment by ibrand** [comment]
Closing due to lack of clarity.
