### ISSUE TITLE
Archived campaigns 

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#645]
It is an inconvenience that archived campaigns cannot be opened, edited, viewed.

**Comment by shakalee14** [comment]
Archived campaigns can be unarchived by visiting that campaign and clicking `unarchive`

<img width="733" alt="screen shot 2018-07-21 at 3 47 55 pm" src="https://user-images.githubusercontent.com/16676323/43039546-8d8a4e5c-8cfd-11e8-9535-144a34ccc900.png">

**Comment by suegibson** [comment]
I want to be able to edit a campaign while it is archived so I can be sure that no texter is using it.
Sue Gibson

#WhiteSilenceIsViolence

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
