### ISSUE TITLE
Per-organization OSDI settings

### ISSUE THREAD

**Issue by harpojaeger** [ProgressiveCoders/Spoke#664]
A forthcoming PR will enable setting OSDI API URL and token on a per-organization business. Decisions that need to be made before this is ready:

1. Who can modify OSDI settings?
2. Who can see the current OSDI settings?
3. Should an environment variable be required to even expose the OSDI settings GUI in the first place?
4. Should sensitive OSDI information be displayed in the settings GUI, or should it disappear after being sent to the server?

**Comment by harpojaeger** [comment]
My proposed answers:

1. Admins and owneres
2. Admins and owners
3. No. The "enable OSDI integrations" boolean can default to FALSE. Since only admins and owners can see or modify these settings, requiring them to jump through the additional hoop of setting an environment variable seems like a waste of time (and it defeats the point of having a GUI for this, which is to _prevent_ users from needing to get into the details of the deploy to modify settings.
4. I'm agnostic about this. Masking the API token is a good idea from a data security perspective, but it adds technological and interface complexity.

**Comment by schuyler1d** [comment]
I'd like to counter propose:

1. Who can modify OSDI settings (assuming 3 is enabled)?
 - Owners only: If someone who is an admin should have this access, they can be upgraded to an owner.  Generally this is a one-time setup
2. Who can see the current OSDI settings?
 - No one -- it should be visible whether they are set.  If OSDI settings include auth credentials, the server should never leak them back to the client -- it exposes too much risk
3. Should an environment variable be required to even expose the OSDI settings GUI in the first place?
 - Yes. environment variables are set by the person hosting the system.  They know who their owners and admins are -- generally they are campaigners and know very little about systems.  Exposing this feature will only be appropriate for certain host systems.  It is not an 'extra' hoop -- whoever sets the system up makes a decision, and then there's no hoop for the owners/admins themselves.  I'm even fine with it being default off, but our default app.json for heroku setting it to ON.  I just don't want to expose something that existing systems may want/need to control.
4. Should sensitive OSDI information be displayed in the settings GUI, or should it disappear after being sent to the server?
 - I think my preference would be that it converts to a password field, to indicate that it will be secret from now on. But if you're talking about right after save on the screen of the person that entered the setting, I don't mind if it 'stays' on the screen before they navigate away.

**Comment by harpojaeger** [comment]
For reference, this is what the settings currently look like.
![screen shot 2018-06-21 at 3 35 54 pm](https://user-images.githubusercontent.com/4314013/41741377-e7430c24-7568-11e8-99e4-a1b8e5b64739.png)
![screen shot 2018-06-21 at 3 35 41 pm](https://user-images.githubusercontent.com/4314013/41741402-f867f474-7568-11e8-94c3-121c3acf2588.png)

**Comment by harpojaeger** [comment]
1. I'm fine with this just being owners as well.
2. Sure.
3. As I think about this, I'm not actually sure how this would work. The envs are set server-side – to conditionally render a component based on a server env requires messing with the Webpack config at a pretty granular level, unless I'm badly misunderstanding something here.
4. Setting the token field to be a password field is easy, but that's just a mask – the values are still being sent to the client. If we don't want them sent at all, I would probably change the interface so that the user must click a "edit" icon to expose the token field for editing.

**Comment by schuyler1d** [comment]
3. Environment variables that need to be available/known to the client are set here:
https://github.com/MoveOnOrg/Spoke/blob/main/src/server/middleware/render-index.js#L61-L75
4. nothing should EVER be sent to the client.  I thought you were talking about a person that pasted/wrote in the setting and just clicked 'Save' -- so the app state has the input.value.  No API should ever be sending cred properties of any kind to the client for anyone/anything -- even on the response to a save.  Think of it like saving a password -- the server never responds back with your password that you saved in plaintext.

**Comment by harpojaeger** [comment]
This has been addressed; OSDI settings are configurable per-organization, and the credentials are never relayed between FE and BE except when they are initially set.

If there is later a need to be able to set OSDI credentials for all organizations in a single instance of Spoke, I would consider that a separate issue (especially since discussion would be needed to decide whether global envs or per-org settings should take priority when both are present [I can see arguments for both]).

This issue should be closed once #597 is closed.

**Comment by Frydafly** [comment]
@harpojaeger checking in on the status of this issue?

**Comment by schuyler1d** [comment]
We have a different facility for org settings which can be leveraged by different contact loaders and action handlers, so any future work would just use that same stuff.
