### ISSUE TITLE
Need campaign number displayed on texters’ conversation screen

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#668]
RESOLVED with the addition of the Texting Hours button within each campaign. 
When I set out to reply in an Eastern Time zone campaign this morning, responses in campaigns in other time zones were auto-fed to me and I accidentally replied. 
I need campaigns to be kept separate so that a volunteer cannot click on one and get responses in another mixed in. It is a pain to have to archive all campaigns and pull them out again as each time zone opens. 
I want to be able to keep all active campaigns in Current Campaigns and put them to sleep/wake them daily by time zone and/or individual campaign.

**Comment by joemcl** [comment]
@suegibson you saw the other replies waiting in other campaigns in your Dashboard ? Like CO, which wasn't open yet? I think if we have ZIP codes in the uploaded contact list, Spoke will match zip to time zone and fix that.

**Comment by suegibson** [comment]
@joemcl @lperson It would be great to see campaign number on the texters’ conversation screen. They ask me a question about a Cabán campaign, I need the campaign number, they return to their dashboard, and they might have twenty Cabán campaigns there. It takes too much effort to figure out which campaign needs the edit or whatever.

**Comment by joemcl** [comment]
hey @suegibson  is this actually a new Issue - the new comment above? Because you wrote above at top "RESOLVED with the addition of the Texting Hours button within each campaign." re the original Issue title and description.
