### ISSUE TITLE
Spoke slowdowns acute when using "dynamically assign contacts" feature 

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#669]
The MoveOn text team volunteers are  noticing relatively consistent slowdowns with sending texts after a volunteer reaches about 3000 texts sent using the "dynamically assign contacts" feature. Send times appear to increase to 7-10 seconds both per initial send and per sending each response to replies.

**Comment by ibrand** [comment]
@joemcl have you all seen this as well? Is this still a problem in 2020?

**Comment by schuyler1d** [comment]
It is a problem and is blocked on scaling

**Comment by Frydafly** [comment]
checking in whether this is still blocked? cc: @schuyler1d

**Comment by schuyler1d** [comment]
we sure fixed this!
