### ISSUE TITLE
Implement a knexfile

### ISSUE THREAD

**Issue by harpojaeger** [ProgressiveCoders/Spoke#683]
Currently, migrations are written by hand in `/src/migrations/index.js'. Implementing a [Knexfile](https://knexjs.org/#knexfile) would have several advantages:

- ability to run `knex migrate:create` to get a migration stub file with all the necessary scaffolding,
- head off a lot of merge conflicts, since migration stub files are timestamped to the second,
- define production, staging and development databases centrally,
- possibly allow phasing out of `r.getCount()` (I haven't investigated this deeply, but it's a possibility)

This would be a big step towards completely removing the legacy DB system, which is a larger project.

Ultimately, I suspect the right way to do this is to write a single Knex "initial" migration that recreates the entire structure of the database as it currently exists. That would allow complete removal of the old migration system, and all future migrations would be done in Knex.

If there are reasons for preserving the existing migration system of which I'm not aware, I'd like to hear about them here! I think this is another issue under the "improve developer experience" heading.

**Comment by harpojaeger** [comment]
Once the `knexfile` is working, we'll be able to phase out the `PGSSLMODE` env var (#679) by setting `pg.defaults.ssl = true` (https://github.com/tgriesser/knex/issues/852#issuecomment-229502678)

**Comment by harpojaeger** [comment]
Reframing this to be about successfully implementing a knexfile, not just the migrations.

**Comment by harpojaeger** [comment]
Idea: write tests that compare `knexfile.js` access to the DB with that from `r.knex`. For this to work, we need access to the `rethink-knex-adapter` from inside `jest`. @lperson has observed race conditions when trying to do this before, related to Thinky's initializing of the DB when the models are `include`d. This would interfere with scaled attempts to test database schema. However, I think it can be overcome in this case, because the things I'm trying to test are more limited.

For the purpose of creating a knexfile, it will be enough to demonstrate that after running the application once (populating the database), and giving `r.knex` and vanilla `knex` access to the normal development database (_not_ the testing one), they can execute the same queries and get the same results. So for this one test, we can load the `development` database configuration. This test is going to be removed from the codebase after we're all sufficiently convinced that the new vanilla `knex` instance works right.

Down the line, I also need to find a way to test that the schema knex will generate from its initial "migration" (which will really just be reconstructing the existing schema) is the same as what's currently there. One step at a time, though.

**Comment by harpojaeger** [comment]
@schuyler1d and @shakalee14, also want to check with you that my above claim:

> it will be enough to demonstrate that after running the application once (populating the database), and giving r.knex and vanilla knex access to the normal development database (not the testing one), they can execute the same queries and get the same results.

is in fact accurate, and that it's a good metric for acceptance testing this change.

**Comment by harpojaeger** [comment]
I'm stuck in something of a horrible feedback loop: it's really difficult to get Thinky to reliably set up a test database, and without access to such a database, it's impossible to write a test verifying that Knex and Thinky are creating the same schema.

I think the best option may be doing the testing "by hand," that is, setting up Knex migrations that can successfully create a test database schema, and including in the PR evidence that the results of `pg_dump -s` are the same in the new system (and instructions on how to reproduce these results).

**Comment by harpojaeger** [comment]
Cool, I'm working now on the knexfile now. Closing in on it being able to replicate the existing schema, which would mean we'd be able to replace the current migration system. It may also be necessary to do some slightly hacky stuff with `dumbThinky`, so that `thinky.r.knex` (exposed to most parts of the app as `r.knex` is replaced with an instance of the 'vanilla' knex, i.e. the one using the knexfile, but I'm pretty sure I've figured out where to do that.

As to database portability, you can see my current Knexfile construction here: https://github.com/harpojaeger/Spoke/blob/knex-migrations/knexfile.js

**Comment by schuyler1d** [comment]
hm.  that doesn't look very db agnostic -- this looks like it just uses the dump commands for the native db? https://github.com/harpojaeger/Spoke/blob/knex-migrations/migrations/init.sql ?

**Comment by harpojaeger** [comment]
🎉 I totally spaced about that. So much for my snazzy time-saving innovation. Guess I'm rewriting all these schemas by hand!

**Comment by harpojaeger** [comment]
This also means replicating all the foreign keys that Thinky created for us automatically. I like the idea of these being more explicitly-defined (especially since I recently spent a while trying to solve a bug that wasn't actually a bug, but the result of the auto-foreign-key-creation behavior), but this is a very high level of complexity and I'd feel a _lot_ more comfortable if we could find a way of testing it. Short of actually being able to access real Thinky data inside a `jest` environment, @schuyler1d, do objects created with `thinky.createModel()` expose a method that returns a raw query string? This would (maybe) allow for at least a comparison of the queries used to generate each particular table. @lperson this approach is similar to your work in `assignment.test.js`, but that's all testing queries from `/src/server/api`.
