### ISSUE TITLE
Should we switch to a new ORM?

### ISSUE THREAD

**Issue by harpojaeger** [ProgressiveCoders/Spoke#706]
In a call today with @lperson, @schuyler1d & @bchrobot, some of the steps necessary to switch to a brand-new ORM were discussed. This issue is to centralize discussion of alternatives to the current `rethink-knex-adapter`/vanilla Knex system. @schuyler1d thinks not a whole lot will probably be done on this before the end of the 2018 cycle, so we're looking at November at the earliest. In the meantime, we can get a headstart evaluating some of the options.

[Bookshelf.js](http://bookshelfjs.org/) and [Sequelize](http://docs.sequelizejs.com/) are popular.

Anyone with experience using other ORMs or opinions about the pros/cons of the various options should definitely chime in here.

**Comment by bdatkins** [comment]
What is the motivation to move to a new ORM? Are there issues we are having with the current solution?

**Comment by schuyler1d** [comment]
MoveOn has had some bad experience using Sequelize (in https://github.com/MoveOnOrg/sharebandit )
but would be worth checking to see if it has evolved since then.

I also have flags that we should wait until both after Nov 2018 AND after a GraphQL/Apollo upgrade that may change the code structure/needs significantly, itself.

**Comment by harpojaeger** [comment]
@bdatkins We currently use an ORM that's a holdover from when Spoke ran on RethinkDB. After MoveOn took over the project and switched to a SQL DB, they wrote [rethink-knex-adapter](http:/github.com/MoveOnOrg/rethink-knex-adapter) to allow the Thinky ORM to talk to Postgres or SQLite (via knex). @schuyler1d, is that an accurate overview?

To my mind, the argument for switching is that it eliminates a layer (the adapter), removes at least one dependency, and replaces it with something more actively maintained.

**Comment by harpojaeger** [comment]
Also FTR I agree with Sky that this switch shouldn't happen during a cycle, and that the React 16 upgrade is higher priority (and may dictate new BE requirements).

**Comment by harpojaeger** [comment]
I'd like to restart discussion on this issue. I'm still working on the Knex migrations changes, but once those are merged, we could start replacing Thinky with a new ORM.

@bchrobot, do you have concerns about whether the React upgrade will impose new BE requirements? If so, let's try to get a sense of what that might look like.

Some features I think are desirable in a new ORM:

- Knex compatibility (so as to retain DB-agnosticism)
- Doesn't create its own migrations (i.e. models and migrations must be updated in tandem by developers). I think this is desirable for two reasons:
  1. It would make it easier for the new ORM to live side-by-side with the current Thinky setup, so we don't have to migrate the entire codebase in one fell swoop, but can instead move parts one at a time and test them carefully. The ORM doesn't know anything about the underlying DB, or whether another ORM is also accessing it elsewhere in the application.
  2. I _think_ it's more likely to break a test if something goes wrong, because it forces us to explicitly describe the way the database should look.
- Under active development.

In addition to the two ORMs mentioned above, [Objection.js](https://github.com/Vincit/objection.js) looks pretty neat.

**Comment by ibrand** [comment]
@harpojaeger @schuyler1d is this still something that folks are interested in?

**Comment by schuyler1d** [comment]
I think the current direction we're going is to use pure-knex with a few patterns to avoid pitfalls in knex for cross-db issues (e.g. `r.getCount()`) -- we could/should enhance/update the documentation that already exists at https://github.com/MoveOnOrg/Spoke/blob/main/docs/EXPLANATION-development-guidelines.md#understanding-dbormhttpsstackoverflowcomquestions1279613what-is-an-orm-and-where-can-i-learn-more-about-it-calls

but I think we don't need a full ORM.
