### ISSUE TITLE
UI improvements to Message Review

### ISSUE THREAD

**Issue by joemcl** [ProgressiveCoders/Spoke#713]
@lperson here's the list of some of the UI improvements to Message Review that would be really handy:

1. Be able to sort and filter by Campaign, Texter, To, Conversation Status and Latest Message 
2. Is Closed Message same as Skip Reply? 
3. Be able to sort Pick a Texter by first name, last name - the sort order looks like Descending by User ID 
4. Be able to sort in Pick a Campaign
5. Expand Pick a Campaign name box to see longer names
6. Be able to search message text
7. Texters re-assigned conversations can't see earlier parts of the convo by prior sender/texter or receiver

Cross referencing other Issues or PRs:
https://github.com/MoveOnOrg/Spoke/pull/687 

cc: @codygordon

**Comment by joemcl** [comment]
Also see #687 and it appears some of these feature requests are addressed in this PR: #708

**Comment by jclarkejr** [comment]
i'd like to work on this but need help getting Spoke running on my laptop and phone.

**Comment by joemcl** [comment]
Hi @jclarkejr that would be great. If you want to get a local instance set up on your laptop, go to [here](https://github.com/MoveOnOrg/Spoke/blob/main/README.md#getting-started). For using it on your phone, you'll want to perhaps do the Heroku one-click install and run it as an app, then go to that in your mobile browser. See the previous link. Also, it sounds like you've signed up as a text sender already, but if not, go to [here](https://front.moveon.org/join-moveon-text-team/ ) for MoveOn or [here](bit.ly/WFP4TheMany ) for Working Families and you can experience the texter/sender UI as a user on your laptop browser or mobile browser for some live campaigns.

**Comment by jclarkejr** [comment]
@joemcl thank you so much for the thorough answer. i'm working through the instructions now...

**Comment by jclarkejr** [comment]
@joemcl i believe that these [steps](https://github.com/MoveOnOrg/Spoke/blob/main/README.md#getting-started)  were already performed on my laptop... but I'm not a developer and am not sure how to get Spoke running at this point... Maybe i should ask someone to show me at Tuesday's Progressive Hacknite

**Comment by joemcl** [comment]
Hey @lperson here's the older list of UI requests for Message Review. cc: @suegibson @deasterdaywfp

**Comment by joemcl** [comment]
Updating this to reflect that thanks to the great work by @lperson on Message Review since the Issue was filed, I *believe* we can do all of the things requested in the initial list, with these exceptions - 
6. Be able to search message text
7. Texters re-assigned conversations can't see earlier parts of the convo by prior sender/texter or receiver 
cc: @deasterdaywfp @suegibson @ibrand @bdatkins

**Comment by arena** [comment]
Should this issue lead out to a bunch of other issues? Some of these seem a little broad, like the titles of feature requests... maybe those all exist or have been implemented. Let me know if you want help pulling any remaining items into their own detailed issues.

**Comment by joemcl** [comment]
@lperson I think with the exception of this - `Be able to search message text` - all these now exist in Message Review. I'll look again later. If so, I'll create a new Issue for `Be able to search message text`.   cc: @arena .

**Comment by ibrand** [comment]
@joemcl did you check this out? Should we close this?

**Comment by joemcl** [comment]
@ibrand yeah. closing
