### ISSUE TITLE
proposed U.I. for Volunteer Texter View

### ISSUE THREAD

**Issue by jclarkejr** [ProgressiveCoders/Spoke#717]
<img width="889" alt="screen shot 2018-07-17 at 8 29 09 pm" src="https://user-images.githubusercontent.com/3443283/42852727-1de9c258-8a00-11e8-9aa5-a851be62ffab.png">
hi all,
i'm interested in helping with U.I. issues. here is a proposed design for Volunteer Texter View. it might make better use of screen space than the existing single conversation screen. 
let me know if this is helpful,
John

**Comment by joemcl** [comment]
Hey @jclarkejr this is interesting. I know there is a strong preference to not include the receiver's full name. 
Also, to keep focus on completing initial sends, the default is to not show any replies until the sender has completed an assignment of sending X number,or, if the campaign is using dynamic assignments, chooses to go back to the sender Home to field replies. 
I agree the single convo screen is not ideal, however, and kinda prefer the sender interface that Relay uses. 
But we may want to be cautious in updating the UI in the near future. 
Also, how would this (I'm not sure it would, actually) work, and look, on a mobile browser?  Would be pretty tough to read on a phone.

**Comment by jclarkejr** [comment]
i would imagine a single pane on mobile that would thumb-swipe left and right.
would it be helpful to mockup any of your feedback, or is this screen a non-issue at this point and I should focus elsewhere?

**Comment by jclarkejr** [comment]
thanks @shakalee14 i will check it out :)

**Comment by schuyler1d** [comment]
I like the direction here! @jclarkejr .  Another missing that exists now (and probably if anything it would expand) are the additional options that a texter does after receiving messages for reply/response:
1. Marking how they answered a question (there's a drop down)
2. Opting-out someone (with possible message)
3. Choosing a 'Canned Reply' (drop down)
Those already exist.  People have discussed other things here like:
* an emoji / image library
* tagging a resonse (sort of related to 1.)

**Comment by jclarkejr** [comment]
@schuyler1d thanks for the feedback. i'm getting Spoke up and running on my phone and laptop today to be better able to address your comments

**Comment by arena** [comment]
@jclarkejr Is this a visual design recommendation for a single screen in 3 different states, or is this a suggestion to have a 3-way split screen?

**Comment by arena** [comment]
Also, this issue has a pretty broad title --- it would be helpful if you could narrow it down to the part of the ui you want to redesign --- let me know if you'd like some help thinking through a more specific design recommendation. Otherwise, if I don't hear back from you, I'm going to suggest that we move all the design issues under an umbrella and give them specific titles and descriptions. I'm going to be adding a lot of little suggestions and I want to make sure that something as big as the entire texter ui isn't in a single issue without all the complex, interconnected features and edge cases.

**Comment by arena** [comment]
I suggest that we archive this issue since it doesn't seem active. It has some interesting ideas in it but not enough granular detail to be actionable

**Comment by ibrand** [comment]
Agreed with @arena. I'm going to close this, but feel free to reference it in future design issues!
