### ISSUE TITLE
Texter Assignment Alert Email Should Be Configurable By App

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#719]
You should be able to use .env to change the email body sent to texters when an assignment is ready.

**Comment by harpojaeger** [comment]
Which parameters of the email should be configurable? If it's just, say, a reply-to address, an env could work. If we want to let people modify subjects and bodies, maybe there should be an admin interface for this?

**Comment by shakalee14** [comment]
An admin interface would be nice - for v1 and our purposes, I'm thinking this is ok. This message _doesnt need to_ get updated often in our use case.

And this is my proposed change => 
https://github.com/MoveOnOrg/Spoke/pull/720/files

**Comment by shakalee14** [comment]
Two options :

1) Make the notification email  set via .env
2) Make the notification email set per organization and configurable in settings.jsx

Code points: 
https://github.com/MoveOnOrg/Spoke/blob/9078ef59606e2608817bdb8a56a8fce5e4992256/src/server/notifications.js#L37

https://github.com/MoveOnOrg/Spoke/blob/49431299cf16554d61600063b546341656f959a6/src/containers/Settings.jsx

Currently is hard coded here:

**Comment by ibrand** [comment]
@schuyler1d this one is finished, right?

**Comment by schuyler1d** [comment]
looks like!
