### ISSUE TITLE
admin can't change campaign texting hours

### ISSUE THREAD

**Issue by azuzunaga** [ProgressiveCoders/Spoke#733]
When texting hours are enabled, admins can't change the texting hours:
* can't change end and start time at the same time
* can't change end time by itself
* can't change start time by itself

**Comment by joemcl** [comment]
Did you turn off Enforce texting hours in Settings then try to edit the campaign?

**Comment by azuzunaga** [comment]
Yes, no problem there. I should say that I am talking about spoke-stage.

**Comment by ibrand** [comment]
Closing because this seems to be fixed now!
