### ISSUE TITLE
Changing the OPT OUT text message for MoveOn

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#741]
As we head into election season, I would like to more clearly ID to contacts that we are opting them out of  our texts but that, since we are using the voter file, other groups may still text them. Often, contacts don't distinguish between the groups texting them.

Here's my idea:

"I am opting you out of texts from MoveOn immediately. Have a great day."

**Comment by joemcl** [comment]
@ErikKirkstein this is related - https://github.com/MoveOnOrg/Spoke/issues/632

**Comment by schuyler1d** [comment]
I commented on architecture options here: https://github.com/MoveOnOrg/Spoke/issues/632#issuecomment-409370547

Code points can be seen from @joemcl 's PR:
https://github.com/WorkingFamilies/Spoke/pull/14/files

If you opt to set it per-organization, then you could do that here:
* client-side: This file https://github.com/MoveOnOrg/Spoke/blob/main/src/containers/Settings.jsx#L171  (see above for interface, and that place for the mutation)
* server-side: we would probably add a mutation similar to texting-hours here: https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/schema.js#L472-L482 (note accessRequired 'OWNER') in that method and then you would save it in a json blob features: https://github.com/MoveOnOrg/Spoke/blob/main/src/server/models/organization.js#L10
  
* note we'll probably be caching org metadata including anything that can be customized by org, so this would then be cached during our scaling work.
If it's just an env variable, then we wouldn't need to cache it.
