### ISSUE TITLE
Spoke not functional for supervolunteers using iPad

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#748]
Unable to edit Interactions and add Canned Replies while campaign is running.

**Comment by joemcl** [comment]
See @lperson work in progress at #754 cc: @codygordon @suegibson @deasterdaywfp

**Comment by suegibson** [comment]
More information re: need for iPad optimization. 
I am told by others that Spoke is nearly impossible to load using android phone as well as iPad. @lperson

**Comment by lperson** [comment]
@suegibson I need more information.  What does "nearly impossible to load" mean?  Can you describe what happens?

**Comment by lperson** [comment]
@suegibson what happens when you try to edit running campaigns?

**Comment by deasterdaywfp** [comment]
@lperson do you have any additional insight on this?

**Comment by lperson** [comment]
@deasterdaywfp I don't have enough context.  Here are some questions:  Is this an issue with message review?  Are other aspects of spoke impacted?  What does "I haven't been able to load" mean?  Do the things that don't work on iPad work on desktop web?

**Comment by lperson** [comment]
@deasterdaywfp maybe we should do a video thing where someone can demonstrate what doesn't work?  Not tonight though, I'l be too busy 🤮 during the SOTU.
