### ISSUE TITLE
Spoke reply interface on iPhone 5 needs readability adjsutments

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#775]
Here's a snapshot of where the buttons are aligning on iPhone 5 devices:

![image from ios 1](https://user-images.githubusercontent.com/32142717/44007980-d222b14c-9e6b-11e8-8f5f-0a89644c1769.jpg)

**Comment by ErikKirkstein** [comment]
Hi team, adding a note here about this issue also appearing on iPhone 7. The texter says this a new issue, as they have always used their phone for texting,

**Comment by joemcl** [comment]
@ErikKirkstein @lperson @shakalee14 this is related - #754

**Comment by joemcl** [comment]
and @ErikKirkstein Android phones have similar real estate issues...
