### ISSUE TITLE
New texters reporting Spoke login issues when using Google Chrome

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#776]
A handful of new MoveOn texters are reporting an issue setting up their Spoke accounts using Google Chrome as their web browser.

Each texter says that when the attempt to login after creating their account, Spoke just sends them back to the login screen again, and this repeats no matter how many times they try to login. They do not see a message saying their is anything wrong with their username or password.

**Comment by joemcl** [comment]
@ErikKirkstein is it an https:// issue maybe?

**Comment by shakalee14** [comment]
Can you let me know what versions of chrome they're running and if they have anything turned on like [privacy badger](https://www.eff.org/privacybadger) or [adblock](https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom?hl=en-US) turned on?

**Comment by jlegrone** [comment]
Another thing to check for is whether cookies are being blocked through chrome settings.

If this is happening, an icon will be shown in the status bar:

<img width="332" alt="screen shot 2019-01-30 at 5 12 13 pm" src="https://user-images.githubusercontent.com/6752382/52016966-ffbf8c00-24b3-11e9-9daa-1f82d99d5613.png">

Exceptions can be made for the Spoke instance and auth0 domains, or users can change their settings at chrome://settings/content/cookies from "Blocked" to "Allow sites to save and read cookie data".

"Block third-party cookies" and "Keep local data only until you quit your browser" options can both remain enabled.
