### ISSUE TITLE
Sometimes Assignment Creation in Admin Menu gets Stuck

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#779]
- Usually happens on campaigns where assignments are with 10 or more texters
- Current work around is deleting the job request in the db. After deletion, the texter assignments still remain and the Admin can save. Sometimes this has to happen several times & other times, this "resolves itself".

**Comment by Frydafly** [comment]
checking if this is still an issue? if it is, would be helpful to see screenshots or instructions for reproducing the bug! @shakalee14

**Comment by schuyler1d** [comment]
I believe this was resolved, and also largely mitigated with dynamic assignment altogether.  This might also have related somewhat to this issue https://github.com/MoveOnOrg/Spoke/pull/1805
