### ISSUE TITLE
Move sendMessage to Cacheable Queries

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#791]
### sendMessage - 

- [ ] Implement sendMessage with the following cycle:
  1. If status is needsMessage then confirm that it's the first item in `conversation-<contact_cell>-<message_service_id>`, otherwise, do not (re)send message.
  2. LPUSH `conversation-<contact_cell>-<message_service_id>`
  3. LPUSH `message-write-queue`

NOTE
Code Points: 
- Find the backend code [here](https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/schema.js#L855)
- Find the frontend code [here](https://github.com/MoveOnOrg/Spoke/blob/main/src/containers/AssignmentTexterContact.jsx#L993)

**Comment by azuzunaga** [comment]
@shakalee14 what should I store as the value in either list?
