### ISSUE TITLE
Move updateQuestionResponses to Cacheable Queries

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#792]
### updateQuestionResponses - 
- [ ] Implement updateQuestionResponses in cacheable queries with the following work flow 
- HSET `contactinfo-<campaign_contact_id>-<interaction_step_id>`

NOTES:
- Code points here for [backend code](https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/schema.js#L971) and [frontend code](https://github.com/MoveOnOrg/Spoke/blob/main/src/containers/AssignmentTexterContact.jsx#L980)

**Comment by schuyler1d** [comment]
closing with #921
