### ISSUE TITLE
Move updateAssignments to Cacheable Queries

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#793]
### updateAssignments
- [ ] Implement updateAssignments in cacheable queries with the following work flow
- LPUSH `newassignments-<texter_id>-<campaign_id>` OR `dynamicassignments-<campaign_id>`

NOTES:
- Code points
- Backend code: [1](https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/schema.js#L155-L187), [2](https://github.com/MoveOnOrg/Spoke/blob/main/src/workers/jobs.js#L364)
- Frontend code [here](https://github.com/MoveOnOrg/Spoke/blob/main/src/components/CampaignTextersForm.jsx#L122)

**Comment by shakalee14** [comment]
This should be separated out into a different task to account for dynamic assignments.

**Comment by schuyler1d** [comment]
closing -- deciding, for now, that this is out-of-scope
