### ISSUE TITLE
Remove "Add All" button on Texters admin page 

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#795]
Does anyone have use for the Add All button when making texting assignments? Because we don’t in #text4resistance, and it’s just annoying when all users get assigned without consent. 
@codygordon @lperson

**Comment by ibrand** [comment]
@deasterdaywfp @jeffm2001 @schuyler1d do any of you use the "Add All" button? If so, I'll close this. Otherwise maybe we should deprecate it

**Comment by suegibson** [comment]
We do not use it at WFP and would like for it to be gone. @ibrand

**Comment by jeffm2001** [comment]
I'm fine with removing it

**Comment by deasterdaywfp** [comment]
Yes please get rid of it and banish to hell

**Comment by ibrand** [comment]
Let's remove the Add All button! This is ready for someone to take on

**Comment by schuyler1d** [comment]
going to claim this as part of work in https://github.com/MoveOnOrg/Spoke/issues/1533

**Comment by ryanjcrump** [comment]
I hope we're still getting rid of this!!

**Comment by Frydafly** [comment]
checking in on the status of this since https://github.com/MoveOnOrg/Spoke/issues/1533 was closed?

**Comment by schuyler1d** [comment]
this still needs to be done.  This would be a very easy PR removing these lines:
https://github.com/MoveOnOrg/Spoke/blob/main/src/components/CampaignTextersForm.jsx#L475-L481

**Comment by ryanjcrump** [comment]
Is this done? I'm still seeing Add All after all these years :)

**Comment by crayolakat** [comment]
It will be closed in Spoke release 12 :)
