### ISSUE TITLE
Revisit SQS Incoming Message Code/Functionality

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#806]
Last year, we added SQS functionality to handle incoming twilio messages, as suggested by [Twilio](https://www.twilio.com/blog/2017/07/handling-high-volume-inbound-sms-and-webhooks-with-twilio-functions-and-amazon-sqs.html). We should test/revisit this code and create a plan to test it in staging/production. 

Code Points:
https://github.com/MoveOnOrg/Spoke/blob/2eaa5c15857d79d9cc44267858aac51edd0891e2/src/workers/jobs.js#L65

**Comment by ibrand** [comment]
There's also an issue open for documenting SQS set up that feels like a companion to this one: #384

**Comment by Frydafly** [comment]
@schuyler1d checking in whether this can be closed or should remain open? given the latest documentation updates on SQS

**Comment by schuyler1d** [comment]
yup.  The code works.  We could revise documentation and reconsider whether this should be the recommended setup or just something for advanced or fallback config.
