### ISSUE TITLE
Please move the # of texts indicator and # of rows drop-down to top of field

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#807]
Still needed
![d5b5f944-1e55-4837-8e98-74d43abc53c7](https://user-images.githubusercontent.com/39012138/44567057-5ae79880-a736-11e8-9e60-308e5c73ac42.png)
Please move the # of texts indicator and # of rows drop-down menu seen here in lower left corner to above rather than below the rows. 
@codygordon @lperson

**Comment by harpojaeger** [comment]
@suegibson, could you explain this request in a little more depth? What problem with the current design are you hoping to solve?

**Comment by harpojaeger** [comment]
This is solidly @lperson's domain, but as a general note, it's standard in almost all applications to have pagination controls at the bottom of a list, and I would encourage us to avoid violating that standard unless absolutely necessary. Maybe more powerful bulk reassignment would solve this problem without jeopardizing UI consistency?

**Comment by suegibson** [comment]
Thank you, @harpojaeger. Ability to reassign *all* rather than just a page at a time would be even better!
cc: @lperson

**Comment by joemcl** [comment]
@suegibson we can close this right? Feature request is in latest stuff from @lperson .
