### ISSUE TITLE
Please clarify re: heroku

### ISSUE THREAD

**Issue by stevecoh1** [ProgressiveCoders/Spoke#808]
I am just getting started with this, and I notice that heroku is prominently mentioned as a deployment environment.

Please clarify: is heroku required for deployment, strongly recommended, or just simpler, or can other environments, such as AWS be used for deployment.  

It would be good to mention this somewhere in the docs but it's possible I've just missed it.  

Thanks.

**Comment by harpojaeger** [comment]
The docs cover deploying to [Lambda](https://github.com/MoveOnOrg/Spoke/blob/main/docs/DEPLOYING_AWS_LAMBDA.md) and [Heroku](https://github.com/MoveOnOrg/Spoke/blob/main/docs/HOWTO_HEROKU_DEPLOY.md). Heroku is definitely simpler (using the deploy template from the README page gives you a nice setup wizard, too). Depending on the size of the organization you're deploying for, you might choose to use Lambda for better scaling.
