### ISSUE TITLE
Reassigned replies needing texter response appear to be missing 

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#810]
I reassigned all convos (ten) that need texter response to myself, but can’t find them. Receipts attached. Refreshed screen multiple times. They are not in Past Messages. Thank you!
![a2185122-2631-48eb-8201-72adc4542fad](https://user-images.githubusercontent.com/39012138/44631953-03654a80-a939-11e8-9b6f-0143d58461ae.png)
![0662e2f0-3029-4c16-91b1-6b986708dd50](https://user-images.githubusercontent.com/39012138/44631955-03654a80-a939-11e8-89d3-bd70c1c8814f.png)

**Comment by joemcl** [comment]
So @suegibson these are probably opt outs that replied back, right, and so when reassigned to you, would not appear in your list as needing a response.
