### ISSUE TITLE
Sqlite backend broken from campaigns query

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#817]
Using sqlite as a backend, loading a campaign from the admin screen (or anywhere that dueBy or createdAt is passed) yields a graphQL 'field is not a Date' value error.  (Create a campaign, then go to the 'campaigns' section and see that campaigns don't load)

This is likely due to
66c7a51456b54ad04a8a3848959f7e2447fa4745 in organization.js where it moves from the rethink-knex-adapter to a pure knex select('*') and thus does not convert date fields.

It probably needs to either implement a custom `dueBy` method instead of relying on the generic mapFieldsToModel (i.e. add a method and then convert any integer into a date type) OR refactor the changes to the db query back to rethink-knex-adapter getAll, etc.
https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/campaign.js#L74

cc @lperson @harpojaeger for philosophical thoughts on best practices here.

**Comment by dzeez** [comment]
working on this

**Comment by ibrand** [comment]
@dzeez and @shakalee14 looks like this was merged on Sep 12th 2018. Did that PR fully address this issue? If so, I'm going to close.

**Comment by ibrand** [comment]
Closing this since this is no longer a problem -- there happens to be another error causing campaigns not to load on sqlite at the moment, but that's unrelated
