### ISSUE TITLE
Bug : Max Contacts on Dynamic Assignment Does Not Work

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#828]
When an admin attempts to set a max contacts value for a texter a few things happens:
- If the value is not 0, it is set in the DB
- If the value is 0, it sets in the db as an empty string
- The texter can still text above the max contacts value

**Comment by sandramchung** [comment]
Code points: 
[dynamically assigns new contacts in dynamic assignment mode](https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/schema.js#L701)
[assignment creation and updating](https://github.com/MoveOnOrg/Spoke/blob/main/src/workers/jobs.js#L364)

**Comment by sandramchung** [comment]
Order of operations is: 
1) make zero mean zero for max contacts. 
2) ensure that max contacts always saves (I couldn't always get max = 0 to save on my local)

We also brought up the issue of simplifying this code, which is a mess.
There's a conversation to be had about whether and how to support switching between dynamic and standard assignment modes in a given campaign - that will inform future work on assignment functionality and probably the assignment UI.

**Comment by shakalee14** [comment]
Conversation with Erik about switching between dynamic and standard assignments - here is when the switching happens:

1) Erik creates a campaign, it's dynamic and texters have no limits on the amount of contacts they can text (so max_contacts is null)
2) Texters start texting, but it's slow (the loading between contacts)
3) Erik switches back to non-dynamic and sets assignments (to fix the loading issue)
4) This potentially improves performance/load times (?)

**Comment by joemcl** [comment]
adding a cross reference here to #1066 - think there's still some stuff to figure out on Dynamic, though I've figured out a solution to it not working for us recently.

**Comment by joemcl** [comment]
I *think* this should be re-opened since it's not actually fixed... see #1066 re the workaround... cc: @ibrand

**Comment by Frydafly** [comment]
@joemcl checking in if this is still an issue?
