### ISSUE TITLE
Add an {election_days} {election_week} tags in the message

### ISSUE THREAD

**Issue by theochino** [ProgressiveCoders/Spoke#829]
Add a timer in the custom message.

**Comment by joemcl** [comment]
@theochino you can upload whatever you want as custom fields with the .csv of contacts.

**Comment by joemcl** [comment]
@theochino yeah in theory a custom field to do date calcs in pgsql would work, but have not tried it, and not sure what besides plain text can go in a token like {texterFirst_Name} . @shakalee14 @schuyler1d thoughts?
