### ISSUE TITLE
Add a clear text button inside the Opt Out menu

### ISSUE THREAD

**Issue by theochino** [ProgressiveCoders/Spoke#839]
When a user send the text "STOP", twillio actually prevent communication.
A button to clean up the text inside would be great.

**Comment by joemcl** [comment]
@theochino as you note, that response will not get sent by Twilio anyway, if the reply from the contact is only the word STOP or UNSUBSCRIBE. So, the texter does not need to delete the message text. One less step.

**Comment by DinahSanders** [comment]
Using "texter" (the person from our organization sending initial texts) and "contact" (the target receiving that initial text) would be much clearer in these issues than "user".

Also, using "reply" (a message to a texter from a contact; 'them to us') and "response" (a message to a contact from a texter; 'us to them') would help avoid confusion.

**Comment by joemcl** [comment]
@dinahsanders sure, so I edited my comment. But user/sender/texter are used pretty interchangeably in these Issues, and Slack discussion, as well as    'reply'.

**Comment by DinahSanders** [comment]
Thanks! I'm just sharing the experience of writing 50+ pages of front-end user*  documentation for our team and hoping the vocabulary clarity we achieved there to speed up our team's work will help here too. :)

(*both ordinary texters and our leaders who support them, assign texts, etc.)

**Comment by DinahSanders** [comment]
(Oops, and I think you have reply and response backwards. They reply to us, we respond to them.)

**Comment by DinahSanders** [comment]
Note: it is still good that replies which are only the word 'STOP' or 'UNSUBSCRIBE' appear for texters to take action on. This is an opportunity for us to clean up our lists of contacts for future campaigns.

**Comment by joemcl** [comment]
@DinahSanders - 
1. reply v response updated above. 
2. Cool that you have a lot of user documentation written. Could you contribute that back to the community via a pull request in /docs? 
3. Also I've been promising a start to an FAQ for admins for awhile via a pull request in /docs, interested in contributing to that :) ?

**Comment by DinahSanders** [comment]
We're currently in final review stage on our that, with a few texters giving us feedback, but after we get through that, I'd like to look at what parts of it can be generalizable to any organization using Spoke, yes.

However that and working on any other docs will have to wait until after the midterm elections. Eyes on the prize! Do ask me again in November, though. :)

**Comment by joemcl** [comment]
@DinahSanders just throw it in a Google Doc and share the link, allow comments/editing. Wisdom of the crowd and all that. We're at E-61 and any useful knowledge to get stuff done quicker and/or better is appreciated..

**Comment by theochino** [comment]
@joemcl On "stop", Twilio doesn't pass it but still bill the campaign for the attempt to Send it.

**Comment by ibrand** [comment]
Closing because the new texter UI has a button for opting a contact out without sending a message #1493
