### ISSUE TITLE
Stuck on Skipping Opt Out.

### ISSUE THREAD

**Issue by theochino** [ProgressiveCoders/Spoke#841]
The user is stuck on skipping opt-out.

![image](https://user-images.githubusercontent.com/5959961/44948404-d0b0cb80-adea-11e8-9fd0-25ac5684205e.png)

_(Currently looking for work around.)_

**Comment by theochino** [comment]
The workaround for texters that are stuck in the "Skipping Opt Out" is to remove the assigned text, save, wait for the list to be processed, and then go back into the campaign and reassign them work.

(There is a bug, the workaround did not work.)

**Comment by theochino** [comment]
**This is two bugs in one issue.**

It seems that the bug is because something is not updating the campaign_contact table with is_opted_out = true so when the campaign it a is_opted_out = false but the number is in the opt_out table, then the screen freeze.

First Step: SELECT campaign_contact.id FROM public.campaign_contact
LEFT JOIN opt_out ON (opt_out.cell = campaign_contact.cell)
WHERE opt_out.id is not null and campaign_contact.is_opted_out = false

Second Step: UPDATE campaign_contact set is_opted_out = true where id =  <ID from above> ;

**Comment by ibrand** [comment]
Closing because this is a bit old and doesn't seem to have come up since
