### ISSUE TITLE
The Interactions are not copy on the second copy of a campaign.

### ISSUE THREAD

**Issue by theochino** [ProgressiveCoders/Spoke#854]
When you go into a campaign and click Copy Campaign, the interactions are copied the first time. If you click a second-time Copy Campaign, it will copy the second (and subsequent) campaign but will not copy the interactions associated with that campaign.

**Comment by schuyler1d** [comment]
I haven't replicated this, but I added a test in #1130
which tries to verify that it's not an issue.  This issue might be worth closing unless someone can confirm that it's still an issue.

**Comment by ibrand** [comment]
Closing since this is now a duplicate of #1141
