### ISSUE TITLE
Move optOut to cacheable queries

### ISSUE THREAD

**Issue by azuzunaga** [ProgressiveCoders/Spoke#856]
Fill in below and replace optOut instances in [schema](https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/schema.js):

https://github.com/MoveOnOrg/Spoke/blob/aa744b550291fc8352618e48bfacebab9761fb20/src/server/models/cacheable_queries/opt-out.js#L1-L22

**Comment by schuyler1d** [comment]
this was done!
