### ISSUE TITLE
Invite logic needs updating in knex

### ISSUE THREAD

**Issue by sreynen** [ProgressiveCoders/Spoke#86]
Currently the invite link is going to /invite/null because it's not getting the ID back on creation. But even if it does get the ID back, we need to use something other than the ID for the URL, because IDs in PostgreSQL are not obscure hashes like they are in RethinkDB, they're easily guessable numbers.

**Comment by hiemanshu** [comment]
RethinkDB used UUIDs as the primary key, you can have postgresql (using pgcrypto extension) or sqlite (using a plugin) generate and use UUIDs as their primary key. Postgresql has a [uuid](https://www.postgresql.org/docs/9.1/static/datatype-uuid.html) type, Sqlite can use string or binary blob to store UUIDs (binary blobs are faster, but less human readable)

**Comment by schuyler1d** [comment]
it looks like knex queries have uuid for each query, as well, so maybe we can use those to fill those in.  might be worth trying to add it in rethink-knex-adapter (but as a separate field, in most cases).  invite though could be a primary field.

**Comment by sreynen** [comment]
FYI https://github.com/MoveOnOrg/Spoke/tree/wip-86-invite-links has work in progress on this.

**Comment by sreynen** [comment]
This should be resolved now.
