### ISSUE TITLE
Duplicate initial messages sent in the same campaign w/i a short timespan

### ISSUE THREAD

**Issue by deasterdaywfp** [ProgressiveCoders/Spoke#873]
See thread

![robyn](https://user-images.githubusercontent.com/35743690/45237425-a492c000-b2ac-11e8-9e61-5db765b41055.jpg)

**Comment by deasterdaywfp** [comment]
@schuyler1d Have you seen this before? cc: @joemcl

**Comment by deasterdaywfp** [comment]
#705 https://github.com/MoveOnOrg/Spoke/pull/705

**Comment by ErikKirkstein** [comment]
Hi team, I want to affirm this is also happening with MoveOn in recent days. I though at first it could have been something amiss with the voter file data or the way the lists were cut, but seeing this report makes me think it could be systemic.

Possible that duplicate scrubbing is not happening in total when data is loaded in Spoke?

**Comment by joemcl** [comment]
@ErikKirkstein can you jump in on Spoke channel and post a screenshot of a recent convo, like @deasterdaywfp did?

**Comment by joemcl** [comment]
@deasterdaywfp thanks and also something we want to bump up for a fix cc: @ErikKirkstein

**Comment by ibrand** [comment]
@deasterdaywfp and @joemcl do you still see this? We stopped seeing it on our end and I want to know if I should close it

**Comment by ibrand** [comment]
Closing since @deasterdaywfp said he doesn't see it anymore
