### ISSUE TITLE
Feature request: color code to indicate when all initial texts in a Spoke campaign are assigned but not sent

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#875]
Hi team,

As we head into election season and the volume of campaigns in Spoke increases, it is becoming increasingly challenging to ensure that all initial texts within each Spoke campaign are sent after they are assigned.

To assist team managers and super volunteers, I would like to propose a third color code be added to the Spoke admin panel that can indicate quickly without opening a campaign that all initial texts have been assigned but not sent.

Example:

After all available texts in Campaign X have been assigned, the campaign title in the admin panel turns from orange to (purple, blue, etc) to signal that all initial texts are assigned, but not sent. Once all are sent, the color would switch to Green, indicating that both all initial texts have been assigned AND sent.

**Comment by azuzunaga** [comment]
Notes from conversation with @ErikKirkstein:

Demoed current implementation:
![image](https://user-images.githubusercontent.com/17498598/45438365-ceacff00-b66b-11e8-84c2-ff2f130c70a2.png)

Color coding would make identifying the campaigns with unsent initial messages easier. Explore the following options:

1. Color code title of campaign **OR** color code background of `Unsent initial messages` tag
2. Use caps in tag label
