### ISSUE TITLE
Query to figure out what campaign need to be finished.

### ISSUE THREAD

**Issue by theochino** [ProgressiveCoders/Spoke#878]
This sort of query needs to get an overview of the campaign's progress.
Just dumping this query here so it can be added in the Admin screen to monitor things.

```
SELECT 
campaign_id, 
campaign.title, 
count(*) FROM campaign_contact 
LEFT JOIN campaign ON (campaign.id = campaign_contact.campaign_id)
WHERE message_status = 'needsMessage' AND is_opted_out = false AND is_archived = false
AND (campaign_id = X OR campaign_id = X OR campaign_id = X) 
group by campaign_contact.campaign_id, campaign.title
ORDER BY campaign_id
```

_You can assign the ticket to me as I will work on this later and push it._

**Comment by ibrand** [comment]
Closing now that we have a [doc for recording useful queries](https://github.com/MoveOnOrg/Spoke/blob/main/docs/TEXTER_ACTIVITY_QUERIES.md)
