### ISSUE TITLE
Feature: Environment variable for Opt-Outs to be shared across all organizations on the instance

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#884]
Sometimes a single real organization will have a spoke instance, but want to divide camaigns and texters for management purposes.

The current blocker is that opt-outs are only per-organization, so an opt-out that occurs from one organization will not get opted-out on another campaign.

Thus we should have an environment variable
OPTOUTS_SHARE_ALL_ORGS
when true:
* Opt-out queries will not filter by organization
* creating an opt-out should mark all current contacts across organizations ([not just across campaigns](https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/schema.js#L776), like now)

One possibility while working on this would be to remove/ignore the `campaign_contact.is_opted_out` column and change all queries to JOIN on `opt_out` by cell instead.

Also please be conscious of parallel scaling work that has begun:
https://github.com/MoveOnOrg/Spoke/pull/869

**Comment by shakalee14** [comment]
Fixed with #901
