### ISSUE TITLE
Twilio disabling my account/flagging for opt-in violation

### ISSUE THREAD

**Issue by johnflynnCMG** [ProgressiveCoders/Spoke#886]
Twilio recently flagged my account being used for a campaign using public voter data. They said a hard opt-in process is required even though it was peer-to-peer. They would not explain why they allow Hustle/Relay to do this but flagged our Spoke app. Anyone run into this and have ideas for how to get around it?

**Comment by kwhinnery** [comment]
It sounds like you have/had a ticket open with Twilio support? I can follow up and get some clarification - if you could, please e-mail me the ticket number at kwhinnery at twilio dot com. Will update this issue when I have further information.

**Comment by johnflynnCMG** [comment]
Hi Kevin,

I had messaged in github earlier about a twilio issue with spoke. I believe
my original ticket may have closed but its number was: # 1463985

**Comment by joemcl** [comment]
Hey @johnflynnCMG you should join progcode and the Spoke channel in its Slack - start at http://progco.de/join .

**Comment by kwhinnery** [comment]
Hey team,

Just to close the loop here - there was some internal education that needed to happen at Twilio about the peer-to-peer use case. Our internal support teams have been briefed about the nature of this use case, and will work more closely with the Twilio.org team to make case-by-case decisions on P2P messaging accounts. This should prevent false positives on accounts doing P2P messaging from public voter file data.

If you run into this happening with your account, send an e-mail to help@twilio.com and we can get it sorted out.

**Comment by johnflynnCMG** [comment]
Thank you so much Kevin!

**Comment by ibrand** [comment]
Closing since this was completed!
