### ISSUE TITLE
Arizona time incorrectly displayed as MDT instead of MST

### ISSUE THREAD

**Issue by ZevH** [ProgressiveCoders/Spoke#907]
When texting, Spoke displays the current time next to the contact's name. The time is in the contact's time zone.

The time is incorrect for contacts in Arizona. Arizona is in Mountain Time, but the state does not observe Daylight Saving Time. For this reason, Arizona is in Mountain Standard Time (MST, UTC-7) all year long. Spoke is currently treating Arizona like the other states in Mountain Time, displaying Mountain Daylight Time (MDT, UTC-6). As a result, the time displayed is one hour later than the actual time.

The attached screenshot was taken today at 12:43pm Arizona time (MST, UTC-7) = 12:43 PDT = 3:43 EDT.
![spoke arizona page at 12_43pm mst](https://user-images.githubusercontent.com/43025028/45466535-452f1880-b6cf-11e8-89d5-4bbc0528d632.png)

**Comment by ZevH** [comment]
This problem will resolve on November 4, when Daylight Saving Time Ends, but will recur again next spring when Daylight Saving Time begins.

**Comment by lperson** [comment]
@ZevH, @schuyler1d Arizona zip codes should have timezone_info =  `7_0` **not** `6_1` or `7_1`. Using texting hours per campaign, one of the supported timezones is ARIZONA, so contacts without zip codes in campaigns that override organization defaults will have texting hours applied correctly.

**Comment by ZevH** [comment]
Thank you, @lperson . Do I understand correctly that timezone_info is a field we are responsible for setting in the data we upload to Spoke, and therefore this is not a fix to Spoke itself? If so, then this issue can be considered resolved.

**Comment by ibrand** [comment]
@lperson can this one be closed?

**Comment by lperson** [comment]
@ibrand I believe this will work correctly.  If a contact is supplied with a ZIP code and no timezone info, Spoke should calculate the timezone correctly.  If a contact is imported with timezone_info, it is the user's responsibility to set it to indicate "no DST," which would be the case in Arizona.  Timezones for campaigns are specified by name (such as US/Arizona or US/New_York) and Spoke will correctly calculate texting hours for the campaign.

**Comment by ibrand** [comment]
Awesome. Thanks @lperson ! Closing for now, and @ZevH if this comes up in any other context, feel free to comment here / reopen
