### ISSUE TITLE
Slow Loading Times for Individual Campaigns View

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#946]
Page: https://spoke.../admin/{orgId}/campaigns/{campaignId}

Erik reports slow loading times (especially in the morning) for campaigns. Could be something related to the `getCampaign` graphql call taking time? 

Some things -- if we are loading data for a campaign, you can load campaign from cache if/when available with `loaders.campaign.load(id)`, which will also return the cached version of interactionSteps, etc.

Currently cache doesn't really activate until the campaign is started and not archived -- it might be worth reconsidering that, and just let that data be cached and used by the admin, as well.
If you are working on this, please use branch `scaling-messages`

Some code points:
https://github.com/MoveOnOrg/Spoke/blob/main/src/containers/AdminCampaignStats.jsx#L275-L323
theres recently been code changes toward abstraction there with 
https://github.com/MoveOnOrg/Spoke/blob/main/src/server/api/campaign.js#L5
(might be fine, just a place where change has occurred)

this shouldnt be changed too much but cache code points are:
https://github.com/MoveOnOrg/Spoke/blob/scaling-messages/src/server/models/index.js#L104
https://github.com/MoveOnOrg/Spoke/blob/scaling-messages/src/server/models/cacheable_queries/campaign.js#L56
however feel free once you've reasoned through the edit cycle to remove any condition around starting, etc.
and maybe loading some of the stats/counts from cache -- some of them will be easy to query from there.

**Comment by jparkrr** [comment]
@schuyler1d and I looked through this, and it seems a lot of the heavy queries here are solved by caching work already in flight (assignments and interaction-steps), so hopefully that will fix everything!

**Comment by ibrand** [comment]
@schuyler1d is this fixed afterall?

**Comment by schuyler1d** [comment]
I'm going to close this based on the time this was filed (connected to operation issues in 9/2018) also considering we have/are-planning some filters on campaign lists which will also help and have helped.
