### ISSUE TITLE
Refactor campaign_contacts table to be organization_contacts (oriented)

### ISSUE THREAD

**Issue by schuyler1d** [ProgressiveCoders/Spoke#95]
for Datawarehouse loading contacts in #22 and other future work, it will be valuable to move 'campaign_contacts' into organization_contacts with a join table for specific campaigns

**Comment by shakalee14** [comment]
An organization should have contacts and the manager can invite those contacts to a campaign - that is what we are aiming for.

**Comment by mathemagica** [comment]
We want to accumulate a full list of both texters and contacts to text both at the organization level and the campaign level, so that every time we run a new campaign, we can add total texters and contacts to a big pool we can reuse in the future across campaigns.

**Comment by ibrand** [comment]
Closing due to staleness
