### ISSUE TITLE
New priority: Alphabetize People or provide a Search field

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#969]
I am legit desperate for an easier way to find a single texter among >1000. 
![19cb8c62-018a-49d8-8f04-739d63fc5d5d](https://user-images.githubusercontent.com/39012138/46603698-842b7080-cab9-11e8-8ec5-90a55fd23950.png)

**Comment by suegibson** [comment]
Resolved

**Comment by harpojaeger** [comment]
Sue, do you mean that this is no longer a problem for you? If so, can you close the issue? Also, you might want to edit your first comment here and remove the image that contains email addresses of your volunteers. GitHub is accessible to anybody in the world.

**Comment by suegibson** [comment]
@harpojaeger I haven’t been able to figure out how to close an issue.
