### ISSUE TITLE
Texting hours per campaign 

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#973]
So grateful for this feature! Will you make it the default setting? Right now, it’s something we have to remember or remind others to do. Under what circumstances would we toggle either switch off?
Please explain to me basically how texting hours are determined: By state name? Arizona is Mountain Time six months of the year and Pacific Time the other six months. Will that be automatically recognized? A few states are split between two time zones; how about them?
cc: @lperson @joemcl Thank you!

**Comment by lperson** [comment]
Hi Sue.

If texting hours per campaign is set to `override organization texting hours` and `texting hours enforced?` is toggled on:

1. Texting hours start and end apply on a per-campaign basis
2. Each contact's timezone is determined by their zip code if one is provided
3. If no zip code is provided, the campaign will assume the contact is in the timezone specified per campaign.

> Under what circumstances would we toggle either switch off?

You would bottle `override campaign texting hours` off if you want to use the organization defaults.

You would toggle `texting hours enforced` off if the organization enforces texting hours but you want texting hours to not be enforced by a specific campaign.

> Please explain to me basically how texting hours are determined: By state name? 

Current time is determined for each contact.  It's either based on the contact's zip code if one is provided, and if not, by timezone set for the campaign if `override campaign texting hours` and `texting hours enforced` are both set for the campaign.  

> Arizona is Mountain Time six months of the year and Pacific Time the other six months. Will that be automatically recognized? A few states are split between two time zones; how about them?

Spoke will correctly resolve zip codes to timezone, including in states like Arizona (no DST) and Indiana (2 time zones), among others.

The list of timezones supported for campaign texting hours is 

```
const timezones = [
      'US/Alaska',
      'US/Aleutian',
      'US/Arizona',
      'US/Central',
      'US/East-Indiana',
      'US/Eastern',
      'US/Hawaii',
      'US/Indiana-Starke',
      'US/Michigan',
      'US/Mountain',
      'US/Pacific',
      'US/Samoa',
      'America/Puerto_Rico',
      'America/Virgin'
    ]
```
