### ISSUE TITLE
Texters order

### ISSUE THREAD

**Issue by suegibson** [ProgressiveCoders/Spoke#974]
Can texters please be listed in alpha order regardless of whether they have capitalized the first letter in their name? Thank you!
@joemcl 
@lperson 
![a156c1a9-4bf0-47ab-83a7-ad8e886e4696](https://user-images.githubusercontent.com/39012138/46732266-a86e8500-cc52-11e8-8bf2-e8ecebd111c6.jpeg)

**Comment by joemcl** [comment]
Hey @lperson noticing that this is also an issue in People - so how about just making sorting by name in People and Texters case-insensitive ? cc: @azuzunaga

**Comment by lperson** [comment]
@joemcl when you say it's an issue in People do you mean the people page?

**Comment by lperson** [comment]
Because the people page in WFP staging is sort case insensitively.

**Comment by joemcl** [comment]
> Because the people page in WFP staging is sort case insensitively.

@lperson yes in People and I just tried it - I changed my first name from Joe to joe and joe appears first in sort , changed back to Joe and it sorts correctly.

**Comment by lperson** [comment]
@joemcl the people page in your staging right now is doing a correct case insensitive sort.  Look at Joyce, Judith and Julie.

<img width="42" alt="Screen Shot 2019-06-28 at 12 55 47 AM" src="https://user-images.githubusercontent.com/1637288/60318055-8b442880-993f-11e9-9d47-e25de984777d.png">

**Comment by joemcl** [comment]
@lperson just changed my first name on our staging from Joe to joe. Sorted by first name. Now my name with lowercase joe and upper case McL is sorted before Joe D. 

![38bd71e0-88af-4d11-b674-46e4af4514c7](https://user-images.githubusercontent.com/3912434/60318325-6f348d00-9927-11e9-93e4-2e793f68618a.jpg)

**Comment by joemcl** [comment]
I changed it back to Joe and now it sorts correctly - Joe McL comes after Joe D.

**Comment by lperson** [comment]
@joemcl  Oy gevault.  I'll fix the people page but let's keep the issue open for texter order in campaign edit.

**Comment by lperson** [comment]
@joemcl https://github.com/WorkingFamilies/Spoke/pull/110 takes care of the people page problems.  To reiterate I did not address the sort of testers in the assignment tool at this time.

**Comment by lperson** [comment]
https://github.com/WorkingFamilies/Spoke/pull/114

**Comment by ibrand** [comment]
@lperson How much of this issue is fixed on MoveOn's main repo? I'm a little lost on where this all landed

**Comment by lperson** [comment]
This is fixed in commit 50aa0b51d22e67e71c0465c92d4abc16f735b374 in the WFP fork.  It hasn't been merged into MoveOn's fork yet but it's #1330 and it's in the [WFP parity project.](https://github.com/MoveOnOrg/Spoke/projects/14)

**Comment by ibrand** [comment]
Awesome. I'm closing this one since that other issue will get that work merged in. Thanks @lperson !
