### ISSUE TITLE
UI improvement to help solve 'texters aren't using current question menu' problem

### ISSUE THREAD

**Issue by DinahSanders** [ProgressiveCoders/Spoke#980]
**Problem**: we are needing to do extra training to make sure even our less-experienced texters all understand that they must select something in the 'Current Question' menu in the Spoke reply screen to log replies (e.g., 'YES' when someone says "yes"). They seem to be much more focused on the 'Canned Responses' menu.

**Goal**: greater texter compliance with expected steps to categorize replies (and initiate any automatic next steps from some of those replies)

**Suggested solution** (for after midterm elections, definitely!): 
- change name from 'Current Question' to 'Log Their Answer'
- add button-like box around 'Log Their Answer' in UI as seen now on 'Skip Reply' and 'Canned Responses'
- change name from 'Canned Responses' to 'Other Responses' (see #981)

At some point (June 4th?) this last bullet of mine had been changed by someone else to
- change name from 'Canned Responses' to <strike>'Other Responses'</strike> Canned Replies (see #981)
but that is incorrect. Unfortunately I only just noticed the edit which would give the name its opposite meaning (i.e. change it from referring to our messages to contacts to referring to messages to us from contacts).
-- Dinah, September 13, 2019

**Comment by schuyler1d** [comment]
MoveOn mobile team has signed off on this language.

**Comment by schuyler1d** [comment]
Note that the backend tables/columns should not be renamed, so this should only be language in the components and containers.

**Comment by ibrand** [comment]
@zhaluza how's progress going on this issue? I'm cleaning up our `good first issues`s and wanted to check in! I'm going to label it as `in progress` for now since you've claimed it.

**Comment by zhaluza** [comment]
Hi @ibrand — Got a little sidetracked this week, but I started working on this today and made pull requests for the first and third tasks:

- "Current Question" to "Log Their Answer"
- "Canned Responses" button to "Canned Replies"

As I mentioned in my pull request for the first issue, I wanted some clarification for the second issue. I'm unfamiliar with Material UI's style options, so is there any particular style that would be preferred for the box around "Log Their Answer"? Applying the same "Raised Button" style as the "Skip Reply" and "Canned Replies" buttons would make users think it's a clickable/tappable button, so I didn't want to go ahead and make that change just yet.

This is my first open source contribution, so feel free to let me know if there's anything I should be doing differently!

**Comment by DinahSanders** [comment]
Hi,
Just catching up here, but it looks like this got sidetracked somewhere along the way and a new label has been added which has the exact OPPOSITE MEANING of what it should be.

My original message above was edited incorrectly and I unfortunately did not see this until now.

To reiterate: 

> Reply
> A text sent by a contact to a texter; that is, what they say to us. Remember: They reply to our initial text; we respond to their replies.
> 
> Response
> A text sent by a texter to a contact; that is, what we say to them after the initial message. Remember: They reply to our initial text; we respond to their replies.
> 

So again, as I originally wrote, "change name from 'Canned Responses' to 'Other Responses'.

**Comment by zhaluza** [comment]
Thanks for bringing that to my attention, Dinah. I’m at work now, but I’ll send out another pull request to correct the response/reply issue later today.

**Comment by DinahSanders** [comment]
Thanks so much, @zhaluza!

**Comment by zhaluza** [comment]
@DinahSanders Made a new pull request for this issue!
