### ISSUE TITLE
Canned Responses button is labeled "Canned Replies" on small devices

### ISSUE THREAD

**Issue by ZevH** [ProgressiveCoders/Spoke#981]
On at least some small-screen devices, the "Canned Responses" menu button is incorrectly labeled "Canned Replies". The attached screenshot shows Spoke running on an iPhone 6.

This should be changed to "Canned Responses" for accuracy and consistency across devices.

![spoke on ios iphone 6](https://user-images.githubusercontent.com/43025028/46921506-1dbeba80-cfb1-11e8-9daa-d05eaffcab63.jpg)

**Comment by schuyler1d** [comment]
Should this just be "Canned Replies" everywhere for shortness and consistency?

**Comment by DinahSanders** [comment]
No, see logic described here: https://github.com/MoveOnOrg/Spoke/pull/852

They reply to our initial text; we respond to their replies.

**Comment by ibrand** [comment]
@DinahSanders and @ZevH  I'm cleaning up our `good first issues`s and want to know if this one was completed (since it's pretty old) or if it's open for new contributors to claim!

**Comment by DinahSanders** [comment]
@ibrand Making sure our language across all devices is consistent with this concept would be good.

> Reply
> A text sent by a contact to a texter; that is, what they say to us. Remember: They reply to our initial text; we respond to their replies.

> Response
> A text sent by a texter to a contact; that is, what we say to them after the initial message. Remember: They reply to our initial text; we respond to their replies.

**Comment by bdatkins** [comment]
Updated label.  Dipping my toe in the Spoke waters! :)

**Comment by ibrand** [comment]
Thank you for working on this barbara! I'm closing it though because of a newer issue that requires different wording that was just closed: #980
