### ISSUE TITLE
knex bugs: newly joined texted not listed in the contacts dropdown on the create campaign screen right after joining

### ISSUE THREAD

**Issue by mathemagica** [ProgressiveCoders/Spoke#99]
Create an admin account on spoke, and create a texter account. Sign in as the texter from one browser, then sign in as admin on another and create a campaign. In the Texters section of the newly created campaign, you should see the name of the newly created texter in the auto-populated dropdown, but currently this isn't showing up. Fix this

**Comment by schuyler1d** [comment]
This was fixed with this:
https://github.com/MoveOnOrg/Spoke/commit/e7996bedec5221735cd24834e72e18949123fa80
(before it was looking for an existing user, but the result back was an empty array, which evaluated to true)
