### ISSUE TITLE
[Bug] Sometimes Creates Double Assignments For Texters - with unique contact lists

### ISSUE THREAD

**Issue by shakalee14** [ProgressiveCoders/Spoke#990]
This issue came up in a recent round of testing/qa on main. A texter who was assigned 500 texts in the admin assignment tab is then assigned 2 sets of 500 texts. Checking with the db, these lists are distinct contacts (1000) but still a programmatic issue. We need to identify when/why this happens (is it while editing assignments for other people?) and a potential workaround to remove unwanted additional texts.

**Comment by ibrand** [comment]
Closing due to no longer seeing this
