### ISSUE TITLE
Longtime texters can not longer log into Spoke via iPhone/Firefox/Chrome

### ISSUE THREAD

**Issue by ErikKirkstein** [ProgressiveCoders/Spoke#995]
A growing challenge we are seeing is team members with existing Spoke accounts no longer being able to log in to Spoke via their regular devices or browsers.

In nearly all cases, they attempt to log in and just get sent back to the login screen. This process just repeats, and cache and cookie clearing does not solve the issue.

In some cases, even changing browsers does not help, and in some cases it does.

This seems most acute with iPhone users and FireFox desktop users.

**Comment by shakalee14** [comment]
Can you make sure folks seeing this issue on FireFox do not have any ad blockers turned on?

**Comment by shakalee14** [comment]
I added `spoke_url.org/app/org_id/todos` to our allowed login callbacks in auth0 - we will see if this works as a stop gap until we figure out the root issue.
